"""Conteúdo Transversal — métodos de demonstração e indução.

Baseado em Rosen 6ª ed. (seções 1.6 e 1.7) e no resumo da disciplina.
unit = 0. topics: 1 = Demonstrações, 2 = Indução.
"""
from __future__ import annotations

from app.seed.blocks._shared import EASY, HARD, MEDIUM, concept, graded, practice

CONTEUDO_TRANSVERSAL = (
    concept(
        id="dem-intro",
        title="Introdução a demonstrações",
        unit=0,
        topic=1,
        prerequisites=(),
        content="""## Intuição
Uma **demonstração** (ou prova) é um argumento válido que estabelece a verdade de uma sentença matemática. Ela parte de coisas já aceitas — **axiomas**, **definições** e **teoremas** já provados — e, por **regras de inferência**, chega à conclusão. Em computação isso aparece o tempo todo: verificação de programas, segurança, IA, consistência de especificações.

## Definição formal
- **Teorema:** afirmação importante que pode ser mostrada verdadeira. Teoremas menores são **proposições**.
- **Axioma (postulado):** afirmação assumida como verdadeira sem prova.
- **Lema:** teorema auxiliar usado para provar outros resultados.
- **Corolário:** resultado que decorre diretamente de um teorema já provado.
- **Conjectura:** afirmação proposta como verdadeira, mas ainda não demonstrada.

Teoremas costumam ser afirmações **gerais** (com quantificador universal implícito). "Se `x > y`, com `x, y` reais positivos, então `x² > y²`" significa, na verdade, "**para todos** os reais positivos `x` e `y`, …". Para prová-los, escolhe-se um elemento **arbitrário** do domínio e mostra-se que ele satisfaz a propriedade — a *generalização universal* conclui que vale para todos.

## Exemplo resolvido
A frase "Toda dízima periódica é um número racional" é um teorema (afirmação geral). Já "A dízima `1,333…` é racional" **não** é um teorema típico — é um caso particular. Provas tratam do caso geral.

## Erros comuns
- Confundir **definição** (convenção) com **teorema** (precisa de prova).
- Tratar um exemplo como prova do caso geral.
- Esquecer o quantificador universal implícito no enunciado.""",
        questions=(
            graded("dem-intro-q1", "dem-intro",
                   "Uma afirmação assumida como verdadeira **sem** demonstração é chamada de:",
                   ["Teorema", "Axioma", "Corolário", "Conjectura"], 1,
                   "Axioma (ou postulado) é o que assumimos como verdade de partida. Teorema/corolário são provados; conjectura ainda não foi provada.",
                   EASY),
            graded("dem-intro-q2", "dem-intro",
                   "Um resultado que decorre **diretamente** de um teorema já demonstrado é um:",
                   ["Lema", "Axioma", "Corolário", "Conjectura"], 2,
                   "Corolário = consequência imediata de um teorema. O lema, ao contrário, é provado ANTES e serve de apoio para o teorema.",
                   MEDIUM),
            graded("dem-intro-q3", "dem-intro",
                   "Por que 'Se x > y (reais positivos), então x² > y²' é, a rigor, uma afirmação sobre **todos** os pares x, y?",
                   ["Porque x e y são constantes fixas",
                    "Porque há um quantificador universal implícito sobre o domínio",
                    "Porque é um axioma",
                    "Porque é apenas um exemplo"], 1,
                   "A convenção matemática omite o 'para todo', mas ele está implícito: o teorema vale para QUAISQUER reais positivos x, y. Por isso a prova começa tomando x, y arbitrários.",
                   MEDIUM),
            graded("dem-intro-q4", "dem-intro",
                   "Um **teorema auxiliar** usado para apoiar a demonstração de um resultado maior é chamado de:",
                   ["Corolário", "Conjectura", "Lema", "Axioma"], 2,
                   "Lema é um resultado intermediário (geralmente técnico) provado antes do teorema principal, servindo de apoio para ele.",
                   EASY),
            graded("dem-intro-q5", "dem-intro",
                   "Qual a diferença fundamental entre um axioma e um teorema?",
                   ["Axiomas são mais importantes que teoremas",
                    "Axiomas são aceitos sem demonstração; teoremas precisam de prova",
                    "Teoremas são mais simples que axiomas",
                    "Não há diferença — são sinônimos"], 1,
                   "Axiomas são pontos de partida assumidos como verdadeiros; teoremas são afirmações cuja verdade deve ser estabelecida por uma demonstração formal.",
                   MEDIUM),
            graded("dem-intro-q6", "dem-intro",
                   "Para provar um teorema do tipo '∀x ∈ D, P(x)', o procedimento padrão é:",
                   ["Testar P para três valores de x",
                    "Tomar um elemento arbitrário de D e mostrar que ele satisfaz P",
                    "Supor que P é falsa para todo x",
                    "Exibir o maior x do domínio"], 1,
                   "Toma-se um elemento arbitrário do domínio, mostra-se que ele satisfaz P, e pela generalização universal conclui-se que vale para todos.",
                   MEDIUM),
            graded("dem-intro-q7", "dem-intro",
                   "A Conjectura de Goldbach ('todo par ≥ 4 é soma de dois primos') é classificada como conjectura porque:",
                   ["Foi provada recentemente",
                    "É falsa",
                    "Acredita-se ser verdadeira, mas não há demonstração completa",
                    "É um axioma da aritmética"], 2,
                   "Uma conjectura é uma afirmação proposta como verdadeira mas ainda não demonstrada. A de Goldbach permanece sem prova desde 1742, apesar de verificada computacionalmente para valores enormes.",
                   HARD),
        ),
        practice=(
            practice("dem-intro-p1", "dem-intro",
                     "Uma afirmação proposta como verdadeira, mas ainda não demonstrada, é uma:",
                     ["Proposição", "Conjectura", "Lema", "Definição"], 1,
                     "Conjectura: acreditamos ser verdadeira, mas falta prova (ex.: Conjectura de Goldbach).",
                     EASY),
            practice("dem-intro-p2", "dem-intro",
                     "Qual é o papel de um **lema** numa demonstração?",
                     ["É a conclusão final do teorema",
                      "É um teorema auxiliar provado para apoiar a prova de outro resultado",
                      "É uma afirmação assumida sem prova",
                      "É um contraexemplo"], 1,
                     "O lema é um resultado intermediário, geralmente técnico, provado para depois ser usado no teorema principal.",
                     MEDIUM),
            practice("dem-intro-p3", "dem-intro",
                     "Os ingredientes legítimos de uma demonstração são:",
                     ["Apenas exemplos numéricos",
                      "Axiomas, definições, teoremas já provados e regras de inferência",
                      "Apenas a intuição do autor",
                      "Somente a conclusão desejada"], 1,
                     "Uma prova encadeia axiomas, definições e resultados anteriores por meio de regras de inferência até a conclusão.",
                     EASY),
            practice("dem-intro-p4", "dem-intro",
                     "Verificar que `P(x)` vale para `x = 1, 2, 3` constitui uma demonstração de `∀x. P(x)`?",
                     ["Sim, três casos bastam",
                      "Não — exemplos particulares não provam afirmações universais",
                      "Sim, desde que x seja natural",
                      "Depende do valor de P"], 1,
                     "Exemplos confirmam mas não provam o caso geral. Pode falhar no caso não testado. Provas exigem argumento sobre elementos arbitrários.",
                     MEDIUM),
            practice("dem-intro-p5", "dem-intro",
                     "Uma **proposição**, no vocabulário das provas, é:",
                     ["Uma afirmação assumida sem prova",
                      "Um teorema de menor importância",
                      "A negação de um teorema",
                      "Um sinônimo de conjectura"], 1,
                     "Proposição é um teorema menos importante — isto é, uma afirmação verdadeira que pode ser demonstrada, mas de alcance menor que um teorema principal.",
                     EASY),
            practice("dem-intro-p6", "dem-intro",
                     "Se um resultado decorre imediatamente de um lema (e não de um teorema), ele é chamado de:",
                     ["Outro lema ou corolário do lema",
                      "Axioma",
                      "Conjectura",
                      "Definição"], 0,
                     "Um corolário pode decorrer de qualquer resultado já provado (teorema ou lema). Na prática, resultados que decorrem diretamente de um lema também são classificados como corolários ou como lemas auxiliares.",
                     HARD),
        ),
    ),
    concept(
        id="dem-direta",
        title="Demonstração direta",
        unit=0,
        topic=1,
        prerequisites=("dem-intro",),
        content="""## Intuição
A **demonstração direta** de uma condicional `p → q` é construída **assumindo que `p` é verdadeira** e, por passos válidos (definições + álgebra + inferência), mostrando que `q` também é. `p` é a **hipótese**; `q` é a **conclusão**. (Quando `p` é falsa, a condicional já é verdadeira por vacuidade, então nem precisamos nos preocupar.)

## Definição formal
Para provar `p → q` diretamente: suponha `p`; aplique definições e resultados conhecidos; conclua `q`.

Definições úteis: um inteiro `n` é **par** se existe `k ∈ ℤ` com `n = 2k`; é **ímpar** se existe `k ∈ ℤ` com `n = 2k + 1`.

## Exemplo resolvido
**Teorema:** se `n` é um inteiro ímpar, então `n²` é ímpar.
*Prova (direta):* suponha `n` ímpar. Então `n = 2k + 1` para algum `k ∈ ℤ`. Logo
`n² = (2k+1)² = 4k² + 4k + 1 = 2(2k² + 2k) + 1`.
Como `2k² + 2k ∈ ℤ`, `n²` tem a forma `2m + 1`, ou seja, é ímpar. ∎

## Erros comuns
- Começar assumindo `q` (a conclusão) — isso é petição de princípio.
- Usar um valor específico de `n` em vez de um `k` genérico.
- Esquecer de **declarar** a definição usada (par/ímpar, racional, etc.).""",
        questions=(
            graded("dem-direta-q1", "dem-direta",
                   "Numa demonstração direta de `p → q`, o primeiro passo é:",
                   ["Supor que q é verdadeira", "Supor que p é verdadeira",
                    "Supor que p é falsa", "Exibir um contraexemplo"], 1,
                   "Demonstração direta: assume-se a hipótese p e deduz-se a conclusão q por passos válidos.",
                   EASY),
            graded("dem-direta-q2", "dem-direta",
                   "Provando que se n é ímpar então n² é ímpar, escrevemos n = 2k+1 e obtemos n² =",
                   ["2(2k² + 2k)", "2(2k² + 2k) + 1", "4k²", "2k + 1"], 1,
                   "(2k+1)² = 4k²+4k+1 = 2(2k²+2k)+1, que é da forma 2m+1 — ímpar.",
                   MEDIUM),
            graded("dem-direta-q3", "dem-direta",
                   "Para provar diretamente 'a soma de dois pares é par', começamos escrevendo os números como:",
                   ["2a+1 e 2b+1", "2a e 2b", "a² e b²", "a/2 e b/2"], 1,
                   "Pares: m = 2a, n = 2b. Então m+n = 2(a+b), que é par. Usar 2a+1/2b+1 seria para ímpares.",
                   EASY),
            graded("dem-direta-q4", "dem-direta",
                   "Provando diretamente que 'o produto de dois racionais é racional', se `x = a/b` e `y = c/d`, o produto é:",
                   ["(a+c)/(b+d)", "(ad+bc)/(bd)", "(ac)/(bd)", "a/c + b/d"], 2,
                   "x·y = (a/b)·(c/d) = ac/(bd). Como a,b,c,d ∈ ℤ e bd ≠ 0, o resultado é razão de inteiros — racional.",
                   MEDIUM),
            graded("dem-direta-q5", "dem-direta",
                   "Se `m` e `n` são quadrados perfeitos (`m = a²`, `n = b²`), então `mn` é:",
                   ["Sempre primo", "Sempre um quadrado perfeito",
                    "Sempre ímpar", "Sempre par"], 1,
                   "mn = a²b² = (ab)². Como ab ∈ ℤ, o produto é um quadrado perfeito. Esta é uma prova direta clássica do Rosen.",
                   MEDIUM),
            graded("dem-direta-q6", "dem-direta",
                   "Se `m + n` e `n + p` são pares (com `m, n, p ∈ ℤ`), prove diretamente que `m + p` é par. O argumento-chave é:",
                   ["m + p = (m+n) + (n+p)",
                    "m + p = (m+n) + (n+p) − 2n",
                    "m + p = 2m + 2p",
                    "m + p é ímpar"], 1,
                   "m+n = 2a e n+p = 2b. Somando: m+2n+p = 2a+2b ⇒ m+p = 2(a+b−n) = 2(a+b) − 2n. Ou diretamente: m+p = (m+n)+(n+p)−2n = 2a+2b−2n = 2(a+b−n), que é par.",
                   HARD),
            graded("dem-direta-q7", "dem-direta",
                   "Qual erro invalida uma tentativa de demonstração direta?",
                   ["Usar a definição de número par",
                    "Começar assumindo a conclusão q como verdadeira",
                    "Tomar um k genérico",
                    "Aplicar álgebra à hipótese"], 1,
                   "Assumir a conclusão é petição de princípio (raciocínio circular). Numa demonstração direta, assume-se apenas a hipótese p e deduz-se q por passos válidos.",
                   EASY),
        ),
        practice=(
            practice("dem-direta-p1", "dem-direta",
                     "O produto de dois inteiros ímpares é:",
                     ["Sempre par", "Sempre ímpar", "Às vezes par", "Sempre primo"], 1,
                     "(2a+1)(2b+1) = 4ab+2a+2b+1 = 2(2ab+a+b)+1 — ímpar. Direta.",
                     MEDIUM),
            practice("dem-direta-p2", "dem-direta",
                     "Se n é um inteiro par, então n² é:",
                     ["Ímpar", "Par", "Primo", "Negativo"], 1,
                     "n = 2k ⇒ n² = 4k² = 2(2k²), que é par.",
                     EASY),
            practice("dem-direta-p3", "dem-direta",
                     "A soma de dois números racionais é:",
                     ["Sempre irracional", "Sempre racional",
                      "Às vezes irracional", "Nunca um inteiro"], 1,
                     "a/b + c/d = (ad+bc)/(bd), razão de inteiros com bd ≠ 0 — racional.",
                     MEDIUM),
            practice("dem-direta-p4", "dem-direta",
                     "Se `n` é par, então `n + 2` é:",
                     ["Ímpar", "Par", "Primo", "Irracional"], 1,
                     "n = 2k ⇒ n+2 = 2k+2 = 2(k+1), que é par. Prova direta imediata.",
                     EASY),
            practice("dem-direta-p5", "dem-direta",
                     "Para provar 'se `x` é racional e `y` é inteiro, então `x + y` é racional', escrevemos `x = a/b` e:",
                     ["Concluímos que x + y é irracional",
                      "Calculamos x + y = (a + yb)/b, razão de inteiros",
                      "Usamos contrapositiva",
                      "Precisamos de indução"], 1,
                     "x + y = a/b + y = (a + yb)/b. Como a, b, y ∈ ℤ e b ≠ 0, o resultado é racional.",
                     MEDIUM),
            practice("dem-direta-p6", "dem-direta",
                     "Provando que 'se `a | b` e `b | c`, então `a | c`' (divisibilidade), o argumento direto usa:",
                     ["b = ka e c = lb, logo c = lka, ou seja a | c",
                      "Contradição",
                      "Contrapositiva",
                      "Contra-exemplo"], 0,
                     "Se a | b, então b = ka para algum k ∈ ℤ. Se b | c, então c = lb para algum l ∈ ℤ. Logo c = l(ka) = (lk)a, e como lk ∈ ℤ, concluímos a | c.",
                     HARD),
        ),
    ),
    concept(
        id="dem-contrapos",
        title="Demonstração por contrapositiva",
        unit=0,
        topic=1,
        prerequisites=("dem-direta",),
        content="""## Intuição
Às vezes provar `p → q` diretamente "empaca". A **contrapositiva** `¬q → ¬p` é **logicamente equivalente** a `p → q`, então prová-la prova o original. Cuidado: a contrapositiva (`¬q → ¬p`, equivalente) é diferente da **recíproca** (`q → p`, **não** equivalente).

## Definição formal
Para provar `p → q`, prove `¬q → ¬p`: suponha `¬q` e deduza `¬p`.

## Exemplo resolvido
**Teorema:** se `n²` é par, então `n` é par.
Tentar direto (de `n² = 2k` extrair que `n` é par) é desajeitado. Use a contrapositiva: "se `n` é ímpar, então `n²` é ímpar" — que já provamos! Logo o original vale. ∎

**Outro:** "se `3n + 2` é ímpar, então `n` é ímpar." Direto empaca (`3n+2 = 2k+1 ⇒ 3n+1 = 2k`, sem conclusão). Contrapositiva: suponha `n` par, `n = 2k`. Então `3n+2 = 6k+2 = 2(3k+1)`, par. Logo, se `n` é par, `3n+2` é par — exatamente `¬q → ¬p`. ∎

## Erros comuns
- Trocar contrapositiva (`¬q → ¬p`) por recíproca (`q → p`).
- Negar errado: a negação de `p → q` é `p ∧ ¬q`, não `¬p → ¬q`.""",
        questions=(
            graded("dem-contrapos-q1", "dem-contrapos",
                   "A contrapositiva de `p → q` é:",
                   ["q → p", "¬p → ¬q", "¬q → ¬p", "p ∧ ¬q"], 2,
                   "Contrapositiva = ¬q → ¬p, logicamente equivalente a p → q. (q → p é a recíproca, NÃO equivalente.)",
                   EASY),
            graded("dem-contrapos-q2", "dem-contrapos",
                   "Qual frase é **equivalente** a 'se chove, a rua fica molhada'?",
                   ["Se a rua está molhada, choveu",
                    "Se a rua não está molhada, não choveu",
                    "Se não chove, a rua não molha",
                    "Chove e a rua não molha"], 1,
                   "Equivalente = contrapositiva ¬q → ¬p: 'se a rua NÃO está molhada (¬q), então NÃO choveu (¬p)'.",
                   MEDIUM),
            graded("dem-contrapos-q3", "dem-contrapos",
                   "Para provar 'se 3n+2 é ímpar, então n é ímpar', a contrapositiva a demonstrar é:",
                   ["se n é ímpar, então 3n+2 é ímpar",
                    "se n é par, então 3n+2 é par",
                    "se 3n+2 é par, então n é par",
                    "se n é par, então 3n+2 é ímpar"], 1,
                   "p: 3n+2 ímpar; q: n ímpar. Contrapositiva ¬q → ¬p: 'se n é par, então 3n+2 é par'. E de fato 3n+2 = 2(3k+1).",
                   HARD),
            graded("dem-contrapos-q4", "dem-contrapos",
                   "A contrapositiva de 'se n² é ímpar, então n é ímpar' é:",
                   ["se n é ímpar, então n² é ímpar",
                    "se n é par, então n² é par",
                    "se n² é par, então n é par",
                    "se n é par, então n² é ímpar"], 1,
                   "p: n² ímpar; q: n ímpar. Contrapositiva ¬q → ¬p: 'se n é par, então n² é par'. E n = 2k ⇒ n² = 4k² = 2(2k²), par.",
                   MEDIUM),
            graded("dem-contrapos-q5", "dem-contrapos",
                   "A **inversa** de `p → q` é `¬p → ¬q`. Ela é equivalente a:",
                   ["p → q (a original)",
                    "¬q → ¬p (a contrapositiva)",
                    "q → p (a recíproca)",
                    "p ∧ ¬q (a negação)"], 2,
                   "A inversa ¬p → ¬q é logicamente equivalente à recíproca q → p (pois a contrapositiva de q → p é ¬p → ¬q). Nenhuma delas é equivalente ao original.",
                   HARD),
            graded("dem-contrapos-q6", "dem-contrapos",
                   "Para provar 'se `x` é irracional, então `1/x` é irracional', a contrapositiva assume:",
                   ["1/x é racional e mostra que x é racional",
                    "x é racional e mostra que 1/x é racional",
                    "x é irracional e mostra que 1/x é irracional",
                    "1/x é irracional e mostra que x é racional"], 0,
                   "Contrapositiva: 'se 1/x é racional (¬q), então x é racional (¬p)'. Se 1/x = a/b, então x = b/a, razão de inteiros — racional.",
                   MEDIUM),
            graded("dem-contrapos-q7", "dem-contrapos",
                   "A prova por contrapositiva é preferível quando:",
                   ["A conclusão q é fácil de trabalhar diretamente",
                    "A hipótese p leva naturalmente a q",
                    "Partir de ¬q dá mais informação utilizável do que partir de p",
                    "Sempre — é superior à prova direta"], 2,
                   "A contrapositiva é útil quando a hipótese p é 'fraca' (difícil de explorar) e a negação da conclusão ¬q é 'forte' (rica em informação). Nem sempre é necessária.",
                   EASY),
        ),
        practice=(
            practice("dem-contrapos-p1", "dem-contrapos",
                     "A **recíproca** de `p → q` é:",
                     ["¬q → ¬p", "q → p", "¬p → ¬q", "p ∧ ¬q"], 1,
                     "Recíproca = q → p. Não é equivalente ao original (não confundir com a contrapositiva ¬q → ¬p).",
                     MEDIUM),
            practice("dem-contrapos-p2", "dem-contrapos",
                     "Provar a contrapositiva funciona porque ela é:",
                     ["A negação do teorema",
                      "Logicamente equivalente ao teorema",
                      "Mais fraca que o teorema",
                      "A recíproca do teorema"], 1,
                     "p → q ≡ ¬q → ¬p. Provando uma, prova-se a outra.",
                     EASY),
            practice("dem-contrapos-p3", "dem-contrapos",
                     "A negação de `p → q` é:",
                     ["¬p → ¬q", "q → p", "p ∧ ¬q", "¬p ∧ q"], 2,
                     "p → q é falsa exatamente quando p é verdadeira e q é falsa: p ∧ ¬q.",
                     HARD),
            practice("dem-contrapos-p4", "dem-contrapos",
                     "Para provar 'se `n²` é par, então `n` é par', por que a prova direta 'empaca'?",
                     ["Porque n² = 2k não permite concluir facilmente a forma de n",
                      "Porque n sempre é ímpar",
                      "Porque não sabemos fatorar",
                      "Porque a conclusão é falsa"], 0,
                     "De n² = 2k, não conseguimos extrair diretamente que n = 2m. A contrapositiva (n ímpar → n² ímpar) é muito mais natural.",
                     MEDIUM),
            practice("dem-contrapos-p5", "dem-contrapos",
                     "A contrapositiva de 'se `x + y` é ímpar, então `x` é par ou `y` é par' é:",
                     ["se x é ímpar e y é ímpar, então x + y é par",
                      "se x é par ou y é par, então x + y é ímpar",
                      "se x + y é par, então x e y são ímpares",
                      "se x é par, então x + y é ímpar"], 0,
                     "p: x+y ímpar; q: x par ∨ y par. ¬q: x ímpar ∧ y ímpar. ¬p: x+y par. Contrapositiva: 'se x e y são ímpares, então x+y é par'. De fato (2a+1)+(2b+1) = 2(a+b+1).",
                     HARD),
            practice("dem-contrapos-p6", "dem-contrapos",
                     "Quantas formas relacionadas a `p → q` existem (original, contrapositiva, recíproca, inversa)?",
                     ["2", "3", "4", "5"], 2,
                     "São 4: original (p→q), contrapositiva (¬q→¬p), recíproca (q→p), inversa (¬p→¬q). Original ≡ contrapositiva; recíproca ≡ inversa.",
                     EASY),
        ),
    ),
    concept(
        id="dem-contradicao",
        title="Demonstração por contradição (absurdo)",
        unit=0,
        topic=1,
        prerequisites=("dem-direta",),
        content="""## Intuição
Na **demonstração por contradição** (redução ao absurdo), supomos que a afirmação é **falsa** e, a partir disso, deduzimos uma **contradição lógica** — algo da forma `A ∧ ¬A`. Como uma contradição é impossível, a suposição estava errada, logo a afirmação é verdadeira.

## Definição formal
Para provar `S`: suponha `¬S`; derive uma contradição; conclua `S`.

## Exemplo resolvido
**Teorema:** `√2` não é racional.
*Prova (absurdo):* suponha que `√2` seja racional, `√2 = p/q` com a fração **irredutível** (`mdc(p,q)=1`). Então `2q² = p²`, logo `p²` é par, logo `p` é par (`p = 2r`). Daí `2q² = 4r² ⇒ q² = 2r²`, então `q²` é par e `q` é par. Mas então `p` e `q` são ambos pares — contradiz `mdc(p,q)=1`. Absurdo. Logo `√2` é irracional. ∎

## Erros comuns
- Confundir com **contrapositiva**: na contradição supomos `¬S` e buscamos *qualquer* contradição; na contrapositiva provamos `¬q → ¬p` diretamente.
- Esquecer de explicitar **qual** contradição foi obtida.""",
        questions=(
            graded("dem-contradicao-q1", "dem-contradicao",
                   "Na demonstração por contradição, começamos supondo que a afirmação é:",
                   ["Verdadeira", "Falsa", "Um axioma", "Um corolário"], 1,
                   "Supõe-se a NEGAÇÃO da afirmação e busca-se uma contradição lógica (A ∧ ¬A).",
                   EASY),
            graded("dem-contradicao-q2", "dem-contradicao",
                   "A prova de que √2 é irracional chega a uma contradição ao mostrar que:",
                   ["p é primo",
                    "p e q são ambos pares, contradizendo mdc(p,q)=1",
                    "q = 0",
                    "√2 = 1"], 1,
                   "Assumindo √2 = p/q irredutível, conclui-se que p e q são pares — impossível se a fração é irredutível.",
                   MEDIUM),
            graded("dem-contradicao-q3", "dem-contradicao",
                   "Uma 'contradição lógica' tem a forma:",
                   ["A → B", "A ∧ ¬A", "A ∨ ¬A", "¬A → A"], 1,
                   "Contradição = afirmar A e ¬A simultaneamente. (A ∨ ¬A é uma tautologia, o oposto.)",
                   MEDIUM),
            graded("dem-contradicao-q4", "dem-contradicao",
                   "Na prova por contradição de que √2 é irracional, por que se exige que a fração `p/q` seja irredutível?",
                   ["Para simplificar a álgebra",
                    "Para que a contradição (p e q ambos pares) funcione — sem irredutibilidade não há absurdo",
                    "Porque toda fração é irredutível",
                    "Para garantir que p > q"], 1,
                   "Se não exigíssemos mdc(p,q)=1, o fato de p e q serem ambos pares não seria contradição (qualquer fração pode ter numerador e denominador pares). A irredutibilidade é essencial para o absurdo.",
                   HARD),
            graded("dem-contradicao-q5", "dem-contradicao",
                   "Para provar 'se `n = ab` com `a,b` inteiros positivos, então `a ≤ √n` ou `b ≤ √n`' por contradição, supomos:",
                   ["a ≤ √n e b ≤ √n",
                    "a > √n e b > √n",
                    "a = b",
                    "n é primo"], 1,
                   "Supomos a negação: a > √n E b > √n. Então ab > √n · √n = n, contradizendo n = ab.",
                   MEDIUM),
            graded("dem-contradicao-q6", "dem-contradicao",
                   "Pelo menos 4 de quaisquer 22 dias caem no mesmo dia da semana. Esse resultado se prova por:",
                   ["Indução",
                    "Contradição (supor que cada dia da semana aparece no máximo 3 vezes leva a ≤ 21 dias)",
                    "Contrapositiva",
                    "Prova direta"], 1,
                   "Há 7 dias da semana. Se cada aparecesse no máximo 3 vezes: 7 × 3 = 21 < 22 — contradição. Logo, ao menos um dia aparece ≥ 4 vezes (princípio da casa dos pombos).",
                   MEDIUM),
            graded("dem-contradicao-q7", "dem-contradicao",
                   "Na prova por contradição, se a suposição `¬S` **não** leva a contradição, podemos concluir que:",
                   ["S é verdadeira",
                    "S é falsa",
                    "Nada — a técnica simplesmente não funcionou; S pode ser verdadeira ou falsa",
                    "S é um axioma"], 2,
                   "Não chegar a uma contradição não prova nem refuta S. Significa apenas que essa abordagem não foi bem-sucedida; outro método pode funcionar.",
                   EASY),
        ),
        practice=(
            practice("dem-contradicao-p1", "dem-contradicao",
                     "Para mostrar que √3 é irracional, o método natural é:",
                     ["Demonstração direta", "Indução",
                      "Redução ao absurdo", "Contagem"], 2,
                     "Mesma estratégia de √2: supor √3 = p/q irredutível e chegar a p, q ambos divisíveis por 3.",
                     MEDIUM),
            practice("dem-contradicao-p2", "dem-contradicao",
                     "A diferença central entre contradição e contrapositiva é:",
                     ["São idênticas",
                      "Na contradição supõe-se ¬S e busca-se qualquer contradição; na contrapositiva prova-se ¬q → ¬p diretamente",
                      "A contrapositiva não usa hipóteses",
                      "A contradição só vale para números"], 1,
                     "É um ponto de confusão clássico citado no resumo da disciplina.",
                     HARD),
            practice("dem-contradicao-p3", "dem-contradicao",
                     "Se supor ¬S leva a uma contradição, concluímos que:",
                     ["¬S é verdadeira", "S é verdadeira",
                      "S é indecidível", "nada se conclui"], 1,
                     "Se a negação é impossível, a afirmação original S deve ser verdadeira.",
                     EASY),
            practice("dem-contradicao-p4", "dem-contradicao",
                     "Para provar por contradição que `√3` é irracional, a contradição obtida é:",
                     ["p e q são ambos divisíveis por 3, contradizendo mdc(p,q)=1",
                      "p + q = 0",
                      "√3 = 1",
                      "p = q"], 0,
                     "Supondo √3 = p/q irredutível: 3q² = p² ⇒ 3|p ⇒ p = 3r ⇒ q² = 3r² ⇒ 3|q. Ambos divisíveis por 3 contradiz mdc(p,q)=1.",
                     HARD),
            practice("dem-contradicao-p5", "dem-contradicao",
                     "A prova por contradição de `p → q` supõe:",
                     ["¬p", "¬q", "p ∧ ¬q", "¬p ∧ q"], 2,
                     "A negação de p → q é p ∧ ¬q. Então supõe-se que p é verdadeira e q é falsa, e busca-se uma contradição.",
                     MEDIUM),
            practice("dem-contradicao-p6", "dem-contradicao",
                     "Qual a relação entre prova por contradição e prova por contrapositiva?",
                     ["São idênticas",
                      "Contradição supõe ¬S e busca qualquer contradição; contrapositiva prova ¬q → ¬p diretamente",
                      "Contrapositiva é um caso especial de indução",
                      "Contradição só funciona para números"], 1,
                     "Na contrapositiva, o alvo é preciso: provar ¬q → ¬p. Na contradição, supõe-se ¬S e qualquer contradição serve — é mais geral.",
                     MEDIUM),
        ),
    ),
    concept(
        id="dem-equivalencia",
        title="Equivalência: se e somente se",
        unit=0,
        topic=1,
        prerequisites=("dem-direta",),
        content="""## Intuição
Muitos teoremas têm a forma "`p` **se, e somente se**, `q`" (`p ↔ q`). Provar uma equivalência é provar **duas** implicações: a **ida** `p → q` e a **volta** `q → p`. Só com as duas a equivalência fica estabelecida.

## Definição formal
`p ↔ q` é verdadeira sse `p → q` **e** `q → p` são ambas verdadeiras. Para várias afirmações `p₁, p₂, …, pₙ` "todas equivalentes", basta provar um **ciclo** de implicações `p₁ → p₂ → … → pₙ → p₁`.

## Exemplo resolvido
**Teorema:** `n` é ímpar **se, e somente se,** `n²` é ímpar.
- *Ida* (`n` ímpar → `n²` ímpar): já feito por prova direta.
- *Volta* (`n²` ímpar → `n` ímpar): contrapositiva — se `n` é par, `n²` é par. ∎

Para `p₁: n` é par; `p₂: n−1` é ímpar; `p₃: n²` é par — mostra-se `p₁ → p₂ → p₃ → p₁`, fechando o ciclo.

## Erros comuns
- Provar só **uma** das implicações e achar que a equivalência está completa.
- Em "todas equivalentes", esquecer de **fechar o ciclo**.""",
        questions=(
            graded("dem-equivalencia-q1", "dem-equivalencia",
                   "Para provar 'p se, e somente se, q' é necessário demonstrar:",
                   ["Apenas p → q", "Apenas q → p",
                    "p → q e q → p", "p ∧ q"], 2,
                   "Equivalência exige as duas implicações: a ida (p → q) e a volta (q → p).",
                   EASY),
            graded("dem-equivalencia-q2", "dem-equivalencia",
                   "Para mostrar que p₁, p₂, p₃ são todas equivalentes, a estratégia mais econômica é provar:",
                   ["as 6 implicações possíveis",
                    "um ciclo p₁ → p₂ → p₃ → p₁",
                    "apenas p₁ → p₂",
                    "apenas p₁ ↔ p₂"], 1,
                   "Um ciclo de implicações conecta todas: de qualquer pᵢ chega-se a qualquer pⱼ seguindo o ciclo.",
                   MEDIUM),
            graded("dem-equivalencia-q3", "dem-equivalencia",
                   "Na equivalência 'n é ímpar ↔ n² é ímpar', a **volta** (n² ímpar → n ímpar) sai bem por:",
                   ["indução", "contrapositiva (n par → n² par)",
                    "contagem", "contraexemplo"], 1,
                   "A volta direta é difícil; sua contrapositiva 'n par → n² par' é imediata.",
                   MEDIUM),
            graded("dem-equivalencia-q4", "dem-equivalencia",
                   "Para provar que as afirmações `p₁, p₂, p₃, p₄` são todas equivalentes por ciclo, quantas implicações são necessárias?",
                   ["6", "4", "12", "2"], 1,
                   "Um ciclo p₁→p₂→p₃→p₄→p₁ fecha com exatamente 4 implicações, em vez das 12 (= 4×3) que seriam necessárias sem o ciclo.",
                   EASY),
            graded("dem-equivalencia-q5", "dem-equivalencia",
                   "As afirmações '3x+2 é par', 'x+5 é ímpar' e 'x² é par' são equivalentes. Para provar isso por ciclo, uma ordem válida é:",
                   ["Provar cada uma isoladamente",
                    "p₁ → p₂ → p₃ → p₁",
                    "Provar apenas p₁ → p₂",
                    "Provar p₁ ↔ p₃ e ignorar p₂"], 1,
                   "O ciclo p₁→p₂→p₃→p₁ prova que todas são equivalentes. Cada implicação pode usar prova direta ou contrapositiva conforme convenha.",
                   MEDIUM),
            graded("dem-equivalencia-q6", "dem-equivalencia",
                   "Se provarmos `p → q`, `q → r` e `r → p`, concluímos que:",
                   ["Apenas p → r",
                    "p, q e r são todas equivalentes entre si",
                    "Apenas p ↔ q",
                    "p é falsa"], 1,
                   "O ciclo p→q→r→p permite deduzir qualquer implicação entre as três (por transitividade via o ciclo), logo p↔q↔r.",
                   MEDIUM),
            graded("dem-equivalencia-q7", "dem-equivalencia",
                   "A equivalência `n é par ↔ n² é par` exige provar a ida e a volta. A **ida** (n par → n² par) é:",
                   ["Difícil — requer contradição",
                    "Direta: n = 2k ⇒ n² = 4k² = 2(2k²)",
                    "Impossível de provar",
                    "Feita por indução"], 1,
                   "n = 2k ⇒ n² = (2k)² = 4k² = 2(2k²), que é par. É uma prova direta imediata.",
                   EASY),
        ),
        practice=(
            practice("dem-equivalencia-p1", "dem-equivalencia",
                     "O símbolo de 'se e somente se' é:",
                     ["→", "↔", "∧", "∨"], 1,
                     "↔ (bicondicional). → é a condicional simples.",
                     EASY),
            practice("dem-equivalencia-p2", "dem-equivalencia",
                     "Se provamos apenas p → q de uma equivalência p ↔ q, então:",
                     ["a equivalência está completa",
                      "falta provar a volta q → p",
                      "provamos q → p automaticamente",
                      "p e q são falsas"], 1,
                     "Uma implicação não dá a outra; é preciso provar q → p também.",
                     MEDIUM),
            practice("dem-equivalencia-p3", "dem-equivalencia",
                     "Dizer 'a ida' numa prova de equivalência refere-se a:",
                     ["q → p", "p → q", "¬p → ¬q", "p ∧ q"], 1,
                     "Convenção do curso: ida = p → q; volta = q → p.",
                     EASY),
            practice("dem-equivalencia-p4", "dem-equivalencia",
                     "Se só provamos `p → q` e `q → r`, sem `r → p`, podemos concluir que:",
                     ["p, q, r são equivalentes",
                      "Apenas p → r (por transitividade), mas NÃO a equivalência completa",
                      "r → p automaticamente",
                      "Nenhuma das afirmações é verdadeira"], 1,
                     "Sem fechar o ciclo (r → p), apenas sabemos p → q → r (e portanto p → r), mas não as voltas r → q, q → p, etc.",
                     MEDIUM),
            practice("dem-equivalencia-p5", "dem-equivalencia",
                     "Na equivalência 'x é racional ↔ x/2 é racional', a volta (x/2 racional → x racional) se prova por:",
                     ["Contradição",
                      "Prova direta: se x/2 = a/b, então x = 2a/b, razão de inteiros",
                      "Contra-exemplo",
                      "Indução"], 1,
                     "Se x/2 = a/b com a,b ∈ ℤ e b ≠ 0, então x = 2a/b, que é razão de inteiros — logo racional.",
                     EASY),
            practice("dem-equivalencia-p6", "dem-equivalencia",
                     "Para 5 afirmações equivalentes, o método do ciclo exige quantas implicações?",
                     ["10", "5", "20", "25"], 1,
                     "O ciclo p₁→p₂→p₃→p₄→p₅→p₁ tem exatamente 5 implicações, contra 20 (= 5×4) sem o ciclo.",
                     HARD),
        ),
    ),
    concept(
        id="dem-casos",
        title="Demonstração por casos",
        unit=0,
        topic=1,
        prerequisites=("dem-direta",),
        content="""## Intuição
Quando o argumento depende de situações distintas, dividimos em **casos** que cobrem **todas** as possibilidades (exaustivos) e provamos a afirmação em cada um. Se vale em todos os casos, vale sempre.

## Definição formal
Para provar `S`, encontre casos `C₁, …, Cₙ` com `C₁ ∨ … ∨ Cₙ` sempre verdadeiro e prove `S` sob cada `Cᵢ`. Sobreposição entre casos é permitida; **lacuna** (caso não coberto) invalida a prova.

## Exemplo resolvido
**Teorema:** `n² ≥ n` para todo inteiro `n`.
*Prova (casos):*
- `n = 0`: `0 ≥ 0`. ✓
- `n ≥ 1`: multiplicando `n ≥ 1` por `n > 0`, `n² ≥ n`. ✓
- `n ≤ −1`: então `n² ≥ 0 ≥ n` (quadrado é ≥ 0 e `n` é negativo). ✓
Os três casos cobrem todo `ℤ`. ∎

## Erros comuns
- Casos que **não** cobrem tudo (deixam lacuna).
- Provar só o caso "fácil" e generalizar.""",
        questions=(
            graded("dem-casos-q1", "dem-casos",
                   "A exigência essencial sobre os casos numa demonstração por casos é que eles sejam:",
                   ["Em número par", "Exaustivos (cobrem todas as possibilidades)",
                    "Mutuamente exclusivos", "Independentes da hipótese"], 1,
                   "O que não pode faltar é cobrir TODAS as possibilidades. Sobreposição é tolerada; lacuna não.",
                   EASY),
            graded("dem-casos-q2", "dem-casos",
                   "Para provar n² ≥ n em ℤ, uma divisão de casos que funciona é:",
                   ["n primo / n composto",
                    "n = 0 / n ≥ 1 / n ≤ −1",
                    "n par / n ímpar",
                    "n racional / n irracional"], 1,
                   "Esses três casos cobrem todos os inteiros e cada um é fácil de verificar.",
                   MEDIUM),
            graded("dem-casos-q3", "dem-casos",
                   "Provar que n(n+1) é sempre par é natural dividindo em casos pela:",
                   ["primalidade de n", "paridade de n",
                    "magnitude de n", "racionalidade de n"], 1,
                   "Se n é par, o produto é par; se n é ímpar, n+1 é par e o produto é par. Os dois casos (par/ímpar) cobrem tudo.",
                   MEDIUM),
            graded("dem-casos-q4", "dem-casos",
                   "Para provar `(n+1)³ ≥ 3n` para inteiros positivos `n ≤ 4`, a divisão natural é:",
                   ["n par / n ímpar",
                    "Verificar cada valor n = 1, 2, 3, 4 individualmente",
                    "n primo / n composto",
                    "n < 0 / n ≥ 0"], 1,
                   "São apenas 4 valores (n=1,2,3,4). Verifica-se cada um: 8≥3, 27≥9, 64≥27, 125≥81. Todos verdadeiros.",
                   EASY),
            graded("dem-casos-q5", "dem-casos",
                   "Se `x, y, z ∈ ℤ` e `x + y + z` é ímpar, então pelo menos um deles é ímpar. A prova por casos considera:",
                   ["x > 0 ou x ≤ 0",
                    "As combinações de paridade: se todos fossem pares, a soma seria par — contradição",
                    "x = y = z",
                    "Apenas x ímpar"], 1,
                   "Se todos fossem pares: 2a+2b+2c = 2(a+b+c), par — contradição. Se exatamente dois são pares e um ímpar, ou se todos são ímpares, a soma é ímpar. Logo, ao menos um é ímpar.",
                   HARD),
            graded("dem-casos-q6", "dem-casos",
                   "A propriedade `|xy| = |x|·|y|` é tipicamente provada dividindo em:",
                   ["2 casos",
                    "4 casos (sinais de x e y: ++, +−, −+, −−)",
                    "3 casos",
                    "Nenhum caso — é axiomática"], 1,
                   "Consideram-se os 4 casos de sinal: x≥0 e y≥0; x≥0 e y<0; x<0 e y≥0; x<0 e y<0. Em cada um verifica-se a igualdade.",
                   MEDIUM),
            graded("dem-casos-q7", "dem-casos",
                   "Para provar que `max(x, y) + min(x, y) = x + y` para quaisquer reais `x, y`, dividimos em:",
                   ["x racional / x irracional",
                    "x ≥ y ou x < y",
                    "x > 0 ou x ≤ 0",
                    "x = y ou x ≠ y"], 1,
                   "Caso x ≥ y: max=x, min=y, soma = x+y. Caso x < y: max=y, min=x, soma = y+x = x+y. Dois casos exaustivos.",
                   MEDIUM),
        ),
        practice=(
            practice("dem-casos-p1", "dem-casos",
                     "Uma prova por casos com uma possibilidade não coberta está:",
                     ["Correta", "Incorreta (há uma lacuna)",
                      "Correta se os outros casos valem", "Correta por vacuidade"], 1,
                     "Se os casos não são exaustivos, a afirmação pode falhar justamente no caso esquecido.",
                     MEDIUM),
            practice("dem-casos-p2", "dem-casos",
                     "|x| (valor absoluto) é tipicamente tratado por casos segundo:",
                     ["x racional ou não", "x ≥ 0 ou x < 0",
                      "x inteiro ou não", "x primo ou não"], 1,
                     "Definição por casos: |x| = x se x ≥ 0, e |x| = −x se x < 0.",
                     EASY),
            practice("dem-casos-p3", "dem-casos",
                     "Casos que se **sobrepõem** (mas cobrem tudo) tornam a prova:",
                     ["Inválida", "Ainda válida",
                      "Circular", "Vacuamente verdadeira"], 1,
                     "Sobreposição é permitida; o que importa é a exaustividade.",
                     MEDIUM),
            practice("dem-casos-p4", "dem-casos",
                     "Para provar que `n³ − n` é divisível por 3 para todo `n ∈ ℤ`, podemos dividir em:",
                     ["n primo / n composto",
                      "n ≡ 0, 1, 2 (mod 3)",
                      "n positivo / n negativo",
                      "n par / n ímpar"], 1,
                     "Dividindo por resto mod 3: se n≡0: n³−n ≡ 0; se n≡1: 1−1 = 0; se n≡2: 8−2 = 6 ≡ 0. Em todos os casos, 3 divide n³−n.",
                     HARD),
            practice("dem-casos-p5", "dem-casos",
                     "A prova por casos da desigualdade triangular `|a + b| ≤ |a| + |b|` costuma usar:",
                     ["Indução",
                      "4 casos baseados nos sinais de a e b",
                      "Contradição",
                      "Contra-exemplo"], 1,
                     "Os 4 casos de sinal (a≥0 e b≥0, a≥0 e b<0, etc.) cobrem todas as possibilidades e permitem verificar cada um separadamente.",
                     MEDIUM),
            practice("dem-casos-p6", "dem-casos",
                     "Numa prova por casos com 3 casos, é necessário provar a afirmação em:",
                     ["Apenas 2 dos 3 casos",
                      "Todos os 3 casos",
                      "Apenas o caso mais difícil",
                      "Nenhum — basta mostrar os casos"], 1,
                     "Todos os casos devem ser verificados. Omitir um caso invalida a demonstração (pode falhar justamente no caso esquecido).",
                     EASY),
        ),
    ),
    concept(
        id="dem-contraexemplo",
        title="Contra-exemplo (refutação)",
        unit=0,
        topic=1,
        prerequisites=("dem-intro",),
        content="""## Intuição
Para **refutar** uma afirmação universal ("para todo `x`, `P(x)`"), basta exibir **um** caso onde ela falha: um **contra-exemplo**. Um único contra-exemplo derruba a afirmação geral — mas um exemplo que *confirma* **não** prova o caso geral.

## Definição formal
A negação de `∀x. P(x)` é `∃x. ¬P(x)`. Logo, refutar `∀x. P(x)` é exibir um `x₀` com `¬P(x₀)`.

## Exemplo resolvido
**Afirmação:** "Todo número primo é ímpar." **Falsa:** `2` é primo e par. ∎ (um contra-exemplo basta)

**Afirmação:** "O produto de dois irracionais é irracional." **Falsa:** `√2 · √2 = 2`, racional. ∎

## Erros comuns
- Tentar refutar uma afirmação universal com argumento geral quando um contra-exemplo resolve.
- Achar que confirmar a afirmação em vários casos a **prova** (não prova; só não a refuta).""",
        questions=(
            graded("dem-contraexemplo-q1", "dem-contraexemplo",
                   "Para mostrar que 'para todo x, P(x)' é **falsa**, basta:",
                   ["provar P para vários x", "exibir um x com ¬P(x)",
                    "usar indução", "supor P verdadeira"], 1,
                   "A negação de ∀x.P(x) é ∃x.¬P(x): um único contra-exemplo refuta a afirmação universal.",
                   EASY),
            graded("dem-contraexemplo-q2", "dem-contraexemplo",
                   "Um contra-exemplo para 'todo número primo é ímpar' é:",
                   ["9", "2", "7", "15"], 1,
                   "2 é primo e par — derruba a afirmação. (9 e 15 são ímpares e nem primos; 7 é primo ímpar, confirma.)",
                   EASY),
            graded("dem-contraexemplo-q3", "dem-contraexemplo",
                   "Confirmar 'para todo x, P(x)' em 100 exemplos:",
                   ["prova a afirmação", "não prova a afirmação geral",
                    "refuta a afirmação", "é um contra-exemplo"], 1,
                   "Exemplos confirmatórios nunca provam um universal (pode falhar no 101º). Só um contra-exemplo decide a falsidade.",
                   MEDIUM),
            graded("dem-contraexemplo-q4", "dem-contraexemplo",
                   "Para refutar 'todo inteiro positivo pode ser escrito como soma de dois quadrados', um contra-exemplo válido é:",
                   ["4 = 0 + 4", "3 (pois 3 ≠ a² + b² para quaisquer a, b ∈ ℤ)",
                    "5 = 1 + 4", "9 = 0 + 9"], 1,
                   "3 não pode ser escrito como soma de dois quadrados: as possibilidades são 0+0=0, 0+1=1, 1+1=2, 0+4=4, ... Nenhuma dá 3.",
                   MEDIUM),
            graded("dem-contraexemplo-q5", "dem-contraexemplo",
                   "A afirmação 'a soma de dois irracionais é sempre irracional' é:",
                   ["Verdadeira",
                    "Falsa — contra-exemplo: (√2) + (−√2) = 0",
                    "Indecidível",
                    "Verdadeira por vacuidade"], 1,
                   "√2 e −√2 são ambos irracionais, mas sua soma é 0, que é racional. Um contra-exemplo basta para refutar.",
                   HARD),
            graded("dem-contraexemplo-q6", "dem-contraexemplo",
                   "Para refutar uma afirmação **existencial** `∃x. P(x)`, devemos:",
                   ["Exibir um contra-exemplo",
                    "Provar que ∀x. ¬P(x)",
                    "Dar um exemplo de P(x)",
                    "Usar indução"], 1,
                   "Refutar 'existe x com P(x)' exige provar que NENHUM x satisfaz P, ou seja, ∀x.¬P(x). Um contra-exemplo só refuta universais.",
                   HARD),
            graded("dem-contraexemplo-q7", "dem-contraexemplo",
                   "Qual das afirmações pode ser refutada com o contra-exemplo `n = 6`?",
                   ["Todo inteiro par é primo",
                    "Todo inteiro par é positivo",
                    "Todo número composto é ímpar",
                    "Todo inteiro maior que 1 é primo"], 0,
                   "6 é par e não é primo, refutando 'todo inteiro par é primo'. (6 também refuta 'todo composto é ímpar', pois 6 é composto e par, mas a opção A é a mais direta.)",
                   EASY),
        ),
        practice=(
            practice("dem-contraexemplo-p1", "dem-contraexemplo",
                     "A negação de `∀x. P(x)` é:",
                     ["∀x. ¬P(x)", "∃x. ¬P(x)", "∃x. P(x)", "¬∃x. P(x)"], 1,
                     "Negar 'para todo' dá 'existe um que não'.",
                     MEDIUM),
            practice("dem-contraexemplo-p2", "dem-contraexemplo",
                     "Contra-exemplo para 'o produto de dois irracionais é irracional':",
                     ["π · 2", "√2 · √2 = 2", "√2 · √3", "e · π"], 1,
                     "√2 · √2 = 2 é racional, refutando a afirmação.",
                     MEDIUM),
            practice("dem-contraexemplo-p3", "dem-contraexemplo",
                     "Refutar 'todo inteiro positivo é soma de dois quadrados' pode ser feito com:",
                     ["um contra-exemplo, p.ex. 3",
                      "indução",
                      "prova direta",
                      "uma equivalência"], 0,
                     "3 não é soma de dois quadrados (0+1=1, 1+1=2, 1+4=5...). Um contra-exemplo basta.",
                     HARD),
            practice("dem-contraexemplo-p4", "dem-contraexemplo",
                     "A afirmação 'todo quadrado perfeito é par' é:",
                     ["Verdadeira",
                      "Falsa — contra-exemplo: 9 = 3²",
                      "Indeterminada",
                      "Verdadeira por indução"], 1,
                     "9 é quadrado perfeito (3²) e é ímpar. Refuta a afirmação universal com um único contra-exemplo.",
                     EASY),
            practice("dem-contraexemplo-p5", "dem-contraexemplo",
                     "Para mostrar que uma afirmação universal é **verdadeira**, um contra-exemplo:",
                     ["É suficiente", "É irrelevante — precisamos de uma demonstração geral",
                      "Prova o resultado", "Substitui a indução"], 1,
                     "Contra-exemplos servem apenas para REFUTAR universais. Para PROVAR, é necessária uma demonstração que cubra todos os casos.",
                     MEDIUM),
            practice("dem-contraexemplo-p6", "dem-contraexemplo",
                     "A afirmação 'se `n` é par, então `n/2` é par' é:",
                     ["Verdadeira",
                      "Falsa — contra-exemplo: n = 2, pois 2/2 = 1 é ímpar",
                      "Verdadeira por contrapositiva",
                      "Indecidível"], 1,
                     "Para n = 2 (par), n/2 = 1, que é ímpar. O contra-exemplo n = 2 refuta a afirmação.",
                     MEDIUM),
        ),
    ),
    concept(
        id="dem-existencial",
        title="Demonstrações existenciais",
        unit=0,
        topic=1,
        prerequisites=("dem-direta",),
        content="""## Intuição
Afirmações de **existência** (`∃x. P(x)`) podem ser provadas de dois modos: **construtivo** — exibindo um `x` concreto com a propriedade (uma *testemunha*) — ou **não-construtivo** — garantindo que existe sem necessariamente exibi-lo.

## Definição formal
- *Construtiva:* apresente `a` e verifique `P(a)`.
- *Não-construtiva:* mostre que a inexistência é impossível, ou use um argumento (casos, contagem) que garanta existência sem determinar o objeto.

## Exemplo resolvido
**Construtiva:** "existe um par ≥ 4 que é soma de dois primos." Exibimos `4 = 2 + 2`. ∎

**Não-construtiva (clássico):** "existem irracionais `x, y` com `xⁱ = x^y` racional." Considere `√2^√2`. Se for racional, tome `x = y = √2`. Se for irracional, tome `x = √2^√2` e `y = √2`: então `x^y = (√2^√2)^√2 = √2² = 2`, racional. Em **algum** dos casos o par existe — sem sabermos qual! ∎

## Erros comuns
- Achar que toda prova de existência precisa exibir o objeto.
- Numa prova construtiva, afirmar a existência sem realmente **verificar** a propriedade na testemunha.""",
        questions=(
            graded("dem-existencial-q1", "dem-existencial",
                   "Uma demonstração existencial **construtiva** de `∃x. P(x)` consiste em:",
                   ["supor que não existe x e chegar a absurdo",
                    "exibir um valor concreto a e verificar P(a)",
                    "provar a contrapositiva",
                    "dar um contra-exemplo"], 1,
                   "Construtiva = mostrar a testemunha explicitamente e checar que ela satisfaz P.",
                   EASY),
            graded("dem-existencial-q2", "dem-existencial",
                   "A prova de que 'existem irracionais x,y com x^y racional' usando √2^√2 é:",
                   ["construtiva (exibe o par)",
                    "não-construtiva (garante existência sem dizer qual par serve)",
                    "por indução",
                    "por contra-exemplo"], 1,
                   "Ela conclui que UM dos dois pares funciona, sem determinar qual — logo é não-construtiva.",
                   HARD),
            graded("dem-existencial-q3", "dem-existencial",
                   "Uma prova construtiva de 'existe par ≥ 4 soma de dois primos' é:",
                   ["mostrar que todo par é soma de primos",
                    "exibir 4 = 2 + 2",
                    "supor que não existe",
                    "usar contrapositiva"], 1,
                   "Basta uma testemunha: 4 = 2+2, ambos primos. (Note: NÃO precisamos do caso geral — é só existência.)",
                   MEDIUM),
            graded("dem-existencial-q4", "dem-existencial",
                   "Para provar construtivamente 'existe um inteiro `n > 1` tal que `n² + n + 41` **não** é primo', basta:",
                   ["Provar para todo n",
                    "Exibir n = 41: 41² + 41 + 41 = 41·43, que é composto",
                    "Usar indução",
                    "Provar a contrapositiva"], 1,
                   "Para n = 41: n² + n + 41 = 41² + 41 + 41 = 41(41+1+1) = 41·43. Como 41·43 é composto, a testemunha n = 41 prova a existência.",
                   HARD),
            graded("dem-existencial-q5", "dem-existencial",
                   "A diferença entre prova construtiva e não-construtiva é que na construtiva:",
                   ["Usamos contradição",
                    "Exibimos explicitamente o objeto que satisfaz a propriedade",
                    "Não verificamos a propriedade",
                    "Provamos o caso universal"], 1,
                   "Na construtiva, a testemunha é apresentada explicitamente e verificada. Na não-construtiva, garante-se a existência sem necessariamente identificar o objeto.",
                   EASY),
            graded("dem-existencial-q6", "dem-existencial",
                   "Para provar 'existe inteiro `n` tal que `n³ = n`' de forma construtiva, uma testemunha válida é:",
                   ["n = 2", "n = 1 (pois 1³ = 1)", "n = 3", "n = 4"], 1,
                   "1³ = 1 = 1. Logo n = 1 é uma testemunha. (0 e −1 também serviriam: 0³=0, (−1)³=−1.)",
                   EASY),
            graded("dem-existencial-q7", "dem-existencial",
                   "Numa prova não-construtiva, sabemos que o objeto existe mas:",
                   ["Sabemos exatamente qual é",
                    "Não necessariamente sabemos qual é",
                    "Ele não existe de verdade",
                    "Precisamos de infinitos exemplos"], 1,
                   "Provas não-construtivas garantem existência por argumento lógico (contradição, casos) sem determinar o objeto específico. O exemplo clássico é x,y irracionais com x^y racional.",
                   MEDIUM),
        ),
        practice=(
            practice("dem-existencial-p1", "dem-existencial",
                     "O quantificador de uma afirmação existencial é:",
                     ["∀", "∃", "¬", "↔"], 1,
                     "∃ = 'existe'. ∀ = 'para todo'.",
                     EASY),
            practice("dem-existencial-p2", "dem-existencial",
                     "Uma testemunha, numa prova construtiva, é:",
                     ["um contra-exemplo",
                      "o elemento concreto que satisfaz a propriedade",
                      "a hipótese do teorema",
                      "a negação da tese"], 1,
                     "A testemunha é o objeto exibido que comprova a existência.",
                     MEDIUM),
            practice("dem-existencial-p3", "dem-existencial",
                     "Para mostrar que uma afirmação existencial `∃x.P(x)` é **falsa**, devemos provar:",
                     ["∃x. ¬P(x)", "∀x. ¬P(x)", "∀x. P(x)", "um exemplo de P(x)"], 1,
                     "Negar 'existe' dá 'para todo, não': ∀x.¬P(x).",
                     HARD),
            practice("dem-existencial-p4", "dem-existencial",
                     "Uma prova construtiva de '∃n ∈ ℕ tal que n é par e primo' é:",
                     ["Supor que não existe tal n",
                      "Exibir n = 2, que é par e primo",
                      "Provar por indução",
                      "Usar contrapositiva"], 1,
                     "n = 2 é par (2 = 2·1) e primo (divisível apenas por 1 e por si). A testemunha foi exibida e verificada.",
                     EASY),
            practice("dem-existencial-p5", "dem-existencial",
                     "A prova de que '∃ irracional x com x² racional' pode ser feita construtivamente com:",
                     ["x = 2", "x = √2, pois (√2)² = 2",
                      "x = π", "x = e + √2"], 1,
                     "√2 é irracional e (√2)² = 2 é racional. A testemunha é explícita — prova construtiva.",
                     MEDIUM),
            practice("dem-existencial-p6", "dem-existencial",
                     "Na prova não-construtiva dos irracionais x,y com x^y racional, quantos candidatos são considerados?",
                     ["1", "2 (os pares (√2,√2) e (√2^√2, √2))",
                      "Infinitos", "Nenhum"], 1,
                     "O argumento considera dois candidatos: se √2^√2 é racional, o par (√2,√2) serve; senão, o par (√2^√2, √2) serve. Em algum dos dois casos a existência é garantida, mas não sabemos qual.",
                     HARD),
        ),
    ),
    concept(
        id="inducao",
        title="Indução matemática",
        unit=0,
        topic=2,
        prerequisites=("dem-direta",),
        content="""## Intuição
A **indução matemática** prova que `P(n)` vale para todos os naturais a partir de dois passos: mostrar que vale no início (**passo base**) e que, valendo para um `k` qualquer, vale para `k+1` (**passo indutivo**). É o efeito dominó: a primeira peça cai e cada peça derruba a seguinte.

## Definição formal
Para provar `P(n)` para todo `n ≥ a` (`a ∈ ℕ`):
1. **Base:** verifique `P(a)`.
2. **Passo indutivo:** suponha `P(k)` verdadeira para um `k ≥ a` (**hipótese de indução**) e prove `P(k+1)`.
Concluídos os dois, `P(n)` vale para todo `n ≥ a`.

## Exemplo resolvido
**Teorema:** `1 + 2 + … + n = n(n+1)/2`.
- *Base* (`n=1`): `1 = 1·2/2 = 1`. ✓
- *Passo:* suponha `1+…+k = k(k+1)/2`. Então
`1+…+k+(k+1) = k(k+1)/2 + (k+1) = (k+1)(k+2)/2`,
que é a fórmula em `k+1`. ∎

## Erros comuns
- **Esquecer a base** (erro mais comum citado no resumo).
- Usar a tese já para `k+1` (a hipótese vale só para `k`).
- Não escrever explicitamente a **hipótese de indução**.""",
        questions=(
            graded("inducao-q1", "inducao",
                   "Uma prova por indução sobre ℕ exige demonstrar:",
                   ["apenas o passo base",
                    "o passo base e o passo indutivo P(k) → P(k+1)",
                    "apenas o passo indutivo",
                    "a contrapositiva da tese"], 1,
                   "Indução = base + passo. Sem a base, o dominó nunca começa; sem o passo, não se propaga.",
                   EASY),
            graded("inducao-q2", "inducao",
                   "A etapa mais comumente esquecida numa indução é:",
                   ["enunciar a tese", "provar o caso base",
                    "usar ℕ", "escrever a recíproca"], 1,
                   "O resumo destaca: o erro clássico é pular o passo base.",
                   EASY),
            graded("inducao-q3", "inducao",
                   "No passo indutivo de `1+2+…+n = n(n+1)/2`, partimos da hipótese e somamos (k+1), obtendo:",
                   ["k(k+1)/2", "(k+1)(k+2)/2", "(k+1)²/2", "k(k+2)/2"], 1,
                   "k(k+1)/2 + (k+1) = [k(k+1) + 2(k+1)]/2 = (k+1)(k+2)/2 — a fórmula avaliada em k+1.",
                   MEDIUM),
            graded("inducao-q4", "inducao",
                   "Na indução para `1 + 2 + 2² + … + 2ⁿ = 2ⁿ⁺¹ − 1`, o caso base `n = 0` dá:",
                   ["0 = 0", "1 = 2¹ − 1 = 1", "2 = 2", "1 = 0"], 1,
                   "Para n=0: lado esquerdo = 2⁰ = 1; lado direito = 2¹ − 1 = 1. ✓",
                   EASY),
            graded("inducao-q5", "inducao",
                   "Para provar `n < 2ⁿ` por indução, no passo indutivo usamos a hipótese `k < 2ᵏ` e mostramos que:",
                   ["k+1 < 2ᵏ",
                    "k+1 ≤ k+1 ≤ 2ᵏ + 1 ≤ 2ᵏ + 2ᵏ = 2ᵏ⁺¹",
                    "k+1 = 2ᵏ⁺¹",
                    "2ᵏ < k"], 1,
                   "k+1 < 2ᵏ + 1 ≤ 2ᵏ + 2ᵏ = 2·2ᵏ = 2ᵏ⁺¹ (pois 1 ≤ 2ᵏ para k ≥ 0). Logo k+1 < 2ᵏ⁺¹.",
                   HARD),
            graded("inducao-q6", "inducao",
                   "Para provar `n³ − n` é divisível por 3 por indução, no passo indutivo calculamos `(k+1)³ − (k+1) =`:",
                   ["k³ + 1",
                    "k³ + 3k² + 3k + 1 − k − 1 = (k³ − k) + 3k² + 3k",
                    "k³ − k + 1",
                    "3k² + 3k"], 1,
                   "(k+1)³ − (k+1) = k³+3k²+3k+1−k−1 = (k³−k) + 3(k²+k). Por hipótese 3|(k³−k), e 3|3(k²+k), logo 3 divide a soma.",
                   MEDIUM),
            graded("inducao-q7", "inducao",
                   "Para provar `2ⁿ < n!` para `n ≥ 4`, qual é o caso base?",
                   ["n = 0: 1 < 1", "n = 1: 2 < 1",
                    "n = 4: 16 < 24", "n = 3: 8 < 6"], 2,
                   "O caso base é n = 4: 2⁴ = 16 < 24 = 4!. Note que a desigualdade NÃO vale para n < 4 (ex.: n=3 dá 8 > 6), por isso o base é n=4.",
                   MEDIUM),
        ),
        practice=(
            practice("inducao-p1", "inducao",
                     "A 'hipótese de indução' é a suposição de que P vale para:",
                     ["n+1", "k (um valor genérico)", "todo n", "n = 0 apenas"], 1,
                     "Supõe-se P(k) para um k arbitrário e prova-se P(k+1).",
                     MEDIUM),
            practice("inducao-p2", "inducao",
                     "Provar `1 + 3 + 5 + … + (2n−1) = n²` por indução: o caso base (n=1) dá:",
                     ["0 = 0", "1 = 1", "2 = 1", "1 = 2"], 1,
                     "Para n=1: lado esquerdo = 1; lado direito = 1² = 1. ✓",
                     EASY),
            practice("inducao-p3", "inducao",
                     "A indução matemática prova proposições sobre, principalmente:",
                     ["números reais", "os números naturais",
                      "conjuntos finitos só", "funções bijetoras"], 1,
                     "É a técnica padrão para afirmações P(n) com n ∈ ℕ.",
                     EASY),
            practice("inducao-p4", "inducao",
                     "No passo indutivo de `1² + 2² + … + n² = n(n+1)(2n+1)/6`, somamos `(k+1)²` à hipótese e obtemos:",
                     ["k(k+1)(2k+1)/6",
                      "(k+1)(k+2)(2k+3)/6",
                      "(k+1)²(k+2)/6",
                      "k(k+2)(2k+1)/6"], 1,
                     "k(k+1)(2k+1)/6 + (k+1)² = (k+1)[k(2k+1) + 6(k+1)]/6 = (k+1)(2k²+7k+6)/6 = (k+1)(k+2)(2k+3)/6.",
                     HARD),
            practice("inducao-p5", "inducao",
                     "Se o passo base falha mas o passo indutivo é válido, a proposição:",
                     ["Está provada para todo n",
                      "NÃO está provada — ambos os passos são necessários",
                      "Está provada a partir de n = 1",
                      "Pode ser provada por contradição"], 1,
                     "Sem o passo base, o 'dominó' nunca começa. Ambos os passos (base e indutivo) são indispensáveis.",
                     MEDIUM),
            practice("inducao-p6", "inducao",
                     "Na indução para `1 + 3 + 5 + … + (2n−1) = n²`, o passo indutivo soma `2(k+1)−1 = 2k+1` e obtém:",
                     ["k² + 2k + 1 = (k+1)²", "k² + k", "k² + 2k", "k² + 1"], 0,
                     "k² + (2k+1) = k² + 2k + 1 = (k+1)². A fórmula vale para k+1.",
                     MEDIUM),
        ),
    ),
)
