"""Unidade 1 — Teoria dos Conjuntos e Funções.

Baseado em Rosen 6ª ed. (cap. 2) e Menezes; segue a notação do resumo da
disciplina. unit = 1. topics: 3 = Conjuntos, 4 = Funções, 5 = Sequências e
Somatório, 6 = Cardinalidade.
"""
from __future__ import annotations

from app.seed.blocks._shared import EASY, HARD, MEDIUM, concept, graded, practice

UNIDADE_1 = (
    # ───────────────────────── Conjuntos (topic 3) ─────────────────────────
    concept(
        id="conj-basico",
        title="Conjuntos: pertinência, vazio e cardinalidade",
        unit=1,
        topic=3,
        prerequisites=("dem-intro",),
        content="""## Intuição
Um **conjunto** é uma coleção *desordenada* de objetos *distintos* (os **elementos**). Não há ordem nem repetição: `{7,8,9} = {9,8,7}` e `{7,8,7} = {7,8}`.

## Definição formal
- **Por extensão:** listando os elementos — `V = {a,e,i,o,u}`.
- **Por compreensão (intensional):** por uma propriedade — `P = {x : x é par} = {x : ∃y, x = 2y}`.
- **Pertinência:** `a ∈ V` (pertence), `z ∉ V` (não pertence).
- **Conjunto vazio:** `∅` (ou `{ }`) não tem elementos. Atenção: `{∅}` **não** é vazio — tem **um** elemento (o conjunto vazio). Analogia: `∅` é uma pasta vazia; `{∅}` é uma pasta contendo uma pasta vazia.
- **Cardinalidade:** `|S|` é a quantidade de elementos. `|{a,e,i,o,u}| = 5`, `|∅| = 0`, `|{∅}| = 1`.

## Exemplo resolvido
Seja `F = {∅, {∅}}`. Então `|F| = 2`: os elementos são `∅` e `{∅}`. Note `∅ ∈ F` e `{∅} ∈ F`.

## Erros comuns
- Tratar `∅` e `{∅}` como iguais (cardinalidades 0 e 1).
- Contar repetições: `{1,1,2}` tem cardinalidade 2.
- Confundir `∈` (elemento) com `⊆` (subconjunto).""",
        questions=(
            graded("conj-basico-q1", "conj-basico",
                   "Qual é a cardinalidade de `{∅, {∅}}`?",
                   ["0", "1", "2", "3"], 2,
                   "Os elementos são ∅ e {∅} — dois elementos distintos. Logo a cardinalidade é 2.",
                   MEDIUM),
            graded("conj-basico-q2", "conj-basico",
                   "Sobre `∅` e `{∅}`, é correto afirmar:",
                   ["São iguais",
                    "{∅} tem um elemento; ∅ não tem nenhum",
                    "Ambos têm um elemento",
                    "∅ tem um elemento"], 1,
                   "∅ é vazio (|∅|=0). {∅} contém um elemento — o conjunto vazio — então |{∅}|=1.",
                   MEDIUM),
            graded("conj-basico-q3", "conj-basico",
                   "O conjunto `{7, 8, 7, 6}` é igual a:",
                   ["{7, 8, 6}", "{7, 8, 7, 6} apenas", "{7, 8}", "{6}"], 0,
                   "Conjuntos não contam repetição nem ordem: {7,8,7,6} = {6,7,8}.",
                   EASY),
            graded("conj-basico-q4", "conj-basico",
                   "Qual das seguintes é verdadeira?",
                   ["∅ ∈ ∅", "{∅} = ∅", "∅ ∈ {∅}", "∅ ∉ {∅, {∅}}"], 2,
                   "∅ é um elemento de {∅}, pois {∅} é o conjunto cujo único elemento é ∅. Já ∅ ∈ ∅ é falso (∅ não tem elementos).",
                   MEDIUM),
            graded("conj-basico-q5", "conj-basico",
                   "A cardinalidade de `{1, {2, 3}}` é:",
                   ["1", "2", "3", "4"], 1,
                   "Os elementos são 1 e {2,3} — dois elementos distintos. {2,3} conta como um único elemento.",
                   EASY),
            graded("conj-basico-q6", "conj-basico",
                   "O conjunto `{x ∈ ℤ : x² + 4 = 0}` é:",
                   ["{−2, 2}", "{2i, −2i}", "∅", "{4}"], 2,
                   "x² = −4 não tem solução em ℤ (nem em ℝ), então o conjunto é vazio.",
                   MEDIUM),
            graded("conj-basico-q7", "conj-basico",
                   "Seja `F = {∅, {∅}, {{∅}}}`. Qual é `|F|`?",
                   ["0", "1", "2", "3"], 3,
                   "F tem três elementos distintos: ∅, {∅} e {{∅}}. Logo |F| = 3.",
                   HARD),
        ),
        practice=(
            practice("conj-basico-p1", "conj-basico",
                     "`{0, 1, 2, …, 9}` por compreensão é:",
                     ["{x ∈ ℕ : x ≤ 9}", "{x ∈ ℤ : x < 0}", "{x : x é par}", "∅"], 0,
                     "São os naturais de 0 a 9: {x ∈ ℕ : x ≤ 9} (ou x < 10).",
                     MEDIUM),
            practice("conj-basico-p2", "conj-basico",
                     "Qual conjunto é vazio?",
                     ["{x ∈ ℕ : x² = 9}", "{x ∈ ℕ : 2 < x < 3}",
                      "{x ∈ ℤ : x = 0}", "{x ∈ ℝ : x² = 5}"], 1,
                     "Não há natural entre 2 e 3, então {x ∈ ℕ : 2 < x < 3} = ∅. (x²=9 dá 3; x=0 dá {0}; x²=5 dá ±√5.)",
                     MEDIUM),
            practice("conj-basico-p3", "conj-basico",
                     "`|{x ∈ ℤ : x² < 17}|` vale:",
                     ["7", "8", "9", "infinito"], 2,
                     "x ∈ {−4,−3,−2,−1,0,1,2,3,4} pois 4²=16<17 e 5²=25>17. São 9 elementos.",
                     HARD),
            practice("conj-basico-p4", "conj-basico",
                     "A determinação por extensão de `{x ∈ ℕ : x < 1}` é:",
                     ["{0, 1}", "∅", "{0}", "{{0}}"], 2,
                     "O único natural menor que 1 é 0, logo {x ∈ ℕ : x < 1} = {0}.",
                     MEDIUM),
            practice("conj-basico-p5", "conj-basico",
                     "Sobre `5 ∈ {{5}}`, é correto dizer que:",
                     ["é verdadeiro", "é falso, pois o elemento é {5}, não 5",
                      "é falso, pois {{5}} é vazio", "é verdadeiro se 5 ∈ ℕ"], 1,
                     "{{5}} contém um único elemento: {5}. O número 5 não é elemento de {{5}} — apenas {5} é.",
                     HARD),
            practice("conj-basico-p6", "conj-basico",
                     "Se `A = {1, 2, 3}` e `B = {3, 2, 1}`, então:",
                     ["A ≠ B pois a ordem é diferente", "A = B",
                      "A ⊊ B", "|A| ≠ |B|"], 1,
                     "Conjuntos não consideram ordem: {1,2,3} = {3,2,1}.",
                     EASY),
        ),
    ),
    concept(
        id="conj-subconjunto",
        title="Subconjunto, igualdade e conjunto das partes",
        unit=1,
        topic=3,
        prerequisites=("conj-basico",),
        content="""## Intuição
`A` é **subconjunto** de `B` quando todo elemento de `A` está em `B`. Dois conjuntos são **iguais** quando têm exatamente os mesmos elementos — o que equivale a cada um ser subconjunto do outro.

## Definição formal
- **Subconjunto:** `A ⊆ B ⟺ ∀x (x ∈ A → x ∈ B)`.
- **Igualdade:** `A = B ⟺ (A ⊆ B ∧ B ⊆ A)` ⟺ `∀x (x ∈ A ↔ x ∈ B)`.
- **Próprio:** `A ⊊ B ⟺ A ⊆ B ∧ A ≠ B`.
- Para todo `S`: `∅ ⊆ S` e `S ⊆ S`.
- **Conjunto das partes:** `P(S)` (ou `2^S`) é o conjunto de **todos** os subconjuntos de `S`. Se `|S| = n`, então `|P(S)| = 2ⁿ`.

## Exemplo resolvido
`A = {1,2,3}` ⟹ `P(A) = {∅, {1}, {2}, {3}, {1,2}, {1,3}, {2,3}, {1,2,3}}`, com `|P(A)| = 2³ = 8`.
Por que `∅ ⊆ S`? Precisaríamos achar `x ∈ ∅` com `x ∉ S` para negar — impossível, pois `∅` não tem elementos. Verdadeiro por **vacuidade**.

## Erros comuns
- Confundir `∈` com `⊆`: `1 ∈ {1,2}` mas `{1} ⊆ {1,2}`.
- Esquecer que `∅` e o próprio `S` são subconjuntos de `S`.
- Trocar `|P(S)|` por `n` em vez de `2ⁿ`.""",
        questions=(
            graded("conj-subconjunto-q1", "conj-subconjunto",
                   "Se `|S| = 4`, então `|P(S)|` é:",
                   ["4", "8", "16", "24"], 2,
                   "|P(S)| = 2^|S| = 2⁴ = 16.",
                   MEDIUM),
            graded("conj-subconjunto-q2", "conj-subconjunto",
                   "A definição de `A = B` em termos de inclusão é:",
                   ["A ⊆ B apenas", "A ⊆ B e B ⊆ A",
                    "A ⊊ B", "A ∈ B e B ∈ A"], 1,
                   "Dupla inclusão: A = B sse A ⊆ B e B ⊆ A. É a estratégia padrão para provar igualdade de conjuntos.",
                   MEDIUM),
            graded("conj-subconjunto-q3", "conj-subconjunto",
                   "Por que `∅ ⊆ S` para todo conjunto S?",
                   ["Porque ∅ ∈ S sempre",
                    "Por vacuidade: não há x ∈ ∅ que viole x ∈ S",
                    "Porque S é vazio",
                    "Porque |S| = 0"], 1,
                   "Para negar ∅ ⊆ S precisaríamos de x ∈ ∅ com x ∉ S; como ∅ não tem elementos, a inclusão vale vacuamente.",
                   HARD),
            graded("conj-subconjunto-q4", "conj-subconjunto",
                   "Se `A = {1, 2}`, qual é `|P(P(A))|`?",
                   ["4", "8", "16", "32"], 2,
                   "|A| = 2, logo |P(A)| = 4. Então |P(P(A))| = 2⁴ = 16.",
                   HARD),
            graded("conj-subconjunto-q5", "conj-subconjunto",
                   "Qual das seguintes é verdadeira para `A = {1, 2, 3}`?",
                   ["{1, 2} ∈ A", "{1, 2} ⊆ A",
                    "1 ⊆ A", "{1, 2, 3, 4} ⊆ A"], 1,
                   "{1,2} ⊆ A pois 1 ∈ A e 2 ∈ A. Já {1,2} ∈ A é falso (A contém números, não conjuntos). 1 ⊆ A não faz sentido (1 não é conjunto).",
                   MEDIUM),
            graded("conj-subconjunto-q6", "conj-subconjunto",
                   "`A ⊊ B` significa:",
                   ["A = B", "A ⊆ B e A ≠ B",
                    "A ∈ B", "B ⊆ A"], 1,
                   "Subconjunto próprio: A está contido em B mas não é igual a B — existe algo em B que não está em A.",
                   EASY),
            graded("conj-subconjunto-q7", "conj-subconjunto",
                   "Se `A ⊆ B` e `B ⊆ C`, o que podemos concluir?",
                   ["A = C", "C ⊆ A", "A ⊆ C", "A ∩ C = ∅"], 2,
                   "A relação ⊆ é transitiva: todo x ∈ A está em B (por A ⊆ B), e todo x ∈ B está em C (por B ⊆ C), logo x ∈ C.",
                   MEDIUM),
        ),
        practice=(
            practice("conj-subconjunto-p1", "conj-subconjunto",
                     "Quantos elementos tem `P(∅)`?",
                     ["0", "1", "2", "infinito"], 1,
                     "|∅| = 0, então |P(∅)| = 2⁰ = 1. O único subconjunto de ∅ é ∅, logo P(∅) = {∅}.",
                     MEDIUM),
            practice("conj-subconjunto-p2", "conj-subconjunto",
                     "Qual afirmação é verdadeira?",
                     ["{1} ∈ {1, 2, 3}", "1 ⊆ {1, 2, 3}",
                      "{1} ⊆ {1, 2, 3}", "{1} = 1"], 2,
                     "{1} ⊆ {1,2,3} (todo elemento de {1} está em {1,2,3}). {1} ∈ {1,2,3} é falso (o elemento é 1, não {1}).",
                     MEDIUM),
            practice("conj-subconjunto-p3", "conj-subconjunto",
                     "Se `A ⊆ B` e `B ⊆ A`, então:",
                     ["A ⊊ B", "A = B", "A = ∅", "B = ∅"], 1,
                     "Dupla inclusão é exatamente a definição de igualdade de conjuntos.",
                     EASY),
            practice("conj-subconjunto-p4", "conj-subconjunto",
                     "`P({a, b})` é igual a:",
                     ["{∅, {a}, {b}}", "{∅, {a}, {b}, {a,b}}",
                      "{{a}, {b}, {a,b}}", "{a, b}"], 1,
                     "Os subconjuntos de {a,b} são ∅, {a}, {b} e {a,b}. Logo P({a,b}) = {∅, {a}, {b}, {a,b}}.",
                     MEDIUM),
            practice("conj-subconjunto-p5", "conj-subconjunto",
                     "Se `A ⊆ B` e `C ⊆ A`, então:",
                     ["C ⊆ B", "B ⊆ C", "A = C", "C = ∅"], 0,
                     "Pela transitividade de ⊆: C ⊆ A e A ⊆ B implicam C ⊆ B.",
                     MEDIUM),
            practice("conj-subconjunto-p6", "conj-subconjunto",
                     "Verdadeiro ou falso: `{1} ∈ P({1, 2, 3})`?",
                     ["Verdadeiro", "Falso",
                      "Depende da cardinalidade", "Indeterminado"], 0,
                     "{1} é subconjunto de {1,2,3}, logo {1} é elemento de P({1,2,3}). Todo subconjunto de S é elemento de P(S).",
                     EASY),
        ),
    ),
    concept(
        id="conj-produto",
        title="Produto cartesiano",
        unit=1,
        topic=3,
        prerequisites=("conj-basico",),
        content="""## Intuição
O **produto cartesiano** `A × B` reúne todos os **pares ordenados** `(a, b)` com `a ∈ A` e `b ∈ B`. Aqui a **ordem importa**: `(1,a) ≠ (a,1)`. É a base de relações e funções.

## Definição formal
`A × B = {(a, b) : a ∈ A ∧ b ∈ B}`. Se `A` e `B` são finitos, `|A × B| = |A| · |B|`. Em geral `A × B ≠ B × A`.

## Exemplo resolvido
`A = {1,2}`, `B = {a,b,c}`:
`A × B = {(1,a),(1,b),(1,c),(2,a),(2,b),(2,c)}` — `|A × B| = 2·3 = 6`.
`B × A = {(a,1),(a,2),(b,1),(b,2),(c,1),(c,2)}` — mesmo tamanho, pares diferentes.

## Erros comuns
- Tratar pares como não-ordenados (`(a,b) = (b,a)` é falso em geral).
- Esquecer que `|A × B| = |A|·|B|`.
- Achar que `A × B = B × A`.""",
        questions=(
            graded("conj-produto-q1", "conj-produto",
                   "Se `|A| = 3` e `|B| = 4`, então `|A × B|` é:",
                   ["7", "12", "1", "16"], 1,
                   "|A × B| = |A|·|B| = 3·4 = 12 pares ordenados.",
                   EASY),
            graded("conj-produto-q2", "conj-produto",
                   "O produto cartesiano `A × B` é formado por:",
                   ["subconjuntos de A", "pares ordenados (a,b) com a ∈ A, b ∈ B",
                    "elementos comuns a A e B", "a união de A e B"], 1,
                   "A × B = {(a,b) : a ∈ A ∧ b ∈ B} — todos os pares ordenados.",
                   EASY),
            graded("conj-produto-q3", "conj-produto",
                   "Em geral, sobre `A × B` e `B × A`:",
                   ["são sempre iguais",
                    "têm o mesmo tamanho, mas pares diferentes (ordem importa)",
                    "B × A é vazio",
                    "|A × B| ≠ |B × A|"], 1,
                   "|A×B| = |B×A| = |A||B|, mas os pares são distintos pois a ordem importa: (1,a) ≠ (a,1).",
                   MEDIUM),
            graded("conj-produto-q4", "conj-produto",
                   "Se `A = {1, 2, 3}` e `B = {a, b}`, quantos elementos tem `B × A`?",
                   ["5", "6", "9", "8"], 1,
                   "|B × A| = |B|·|A| = 2·3 = 6. Mesmo tamanho que A × B, mas com pares diferentes.",
                   EASY),
            graded("conj-produto-q5", "conj-produto",
                   "O par `(1, 2)` pertence a `{1, 2} × {1, 2}`?",
                   ["Sim, pois 1 ∈ {1,2} e 2 ∈ {1,2}",
                    "Não, pois 1 ≠ 2",
                    "Sim, apenas se A = B",
                    "Não, pares não pertencem a produtos"], 0,
                   "(1,2) ∈ A × B sse 1 ∈ A e 2 ∈ B. Como ambos estão em {1,2}, o par pertence ao produto.",
                   MEDIUM),
            graded("conj-produto-q6", "conj-produto",
                   "`|A × B × C|` com `|A| = 2`, `|B| = 3`, `|C| = 4` é:",
                   ["9", "14", "24", "12"], 2,
                   "|A × B × C| = |A|·|B|·|C| = 2·3·4 = 24 triplas ordenadas.",
                   MEDIUM),
            graded("conj-produto-q7", "conj-produto",
                   "Se `A × B = B × A` e `A ≠ B`, podemos afirmar que:",
                   ["A = ∅ ou B = ∅ ou A = B",
                    "isso nunca ocorre",
                    "|A| = |B| necessariamente",
                    "A ⊆ B sempre"], 0,
                   "A × B = B × A ocorre nos casos triviais: A = B, A = ∅, ou B = ∅. Como A ≠ B, resta A = ∅ ou B = ∅.",
                   HARD),
        ),
        practice=(
            practice("conj-produto-p1", "conj-produto",
                     "O par ordenado `(a, b)` é igual a `(b, a)` quando:",
                     ["sempre", "nunca", "a = b", "a ≠ b"], 2,
                     "(a,b) = (b,a) sse a = b (a ordem só deixa de importar quando as coordenadas coincidem).",
                     MEDIUM),
            practice("conj-produto-p2", "conj-produto",
                     "Se `A = {1,2}`, quantos elementos tem `A × A`?",
                     ["2", "3", "4", "8"], 2,
                     "|A × A| = 2·2 = 4: {(1,1),(1,2),(2,1),(2,2)}.",
                     EASY),
            practice("conj-produto-p3", "conj-produto",
                     "Se `A = ∅`, então `A × B` é:",
                     ["B", "∅", "{∅}", "A ∪ B"], 1,
                     "Sem elementos em A não há pares (a,b); logo ∅ × B = ∅.",
                     MEDIUM),
            practice("conj-produto-p4", "conj-produto",
                     "O elemento `(2, 1)` pertence a `{1, 2} × {1, 2}`?",
                     ["Sim", "Não", "Só se 2 = 1", "Indeterminado"], 0,
                     "2 ∈ {1,2} e 1 ∈ {1,2}, logo (2,1) ∈ {1,2} × {1,2}.",
                     EASY),
            practice("conj-produto-p5", "conj-produto",
                     "Liste os elementos de `{a} × {1, 2, 3}`:",
                     ["{(a,1), (a,2), (a,3)}", "{(1,a), (2,a), (3,a)}",
                      "{a, 1, 2, 3}", "{(a,a), (1,1)}"], 0,
                     "Para cada b ∈ {1,2,3}, forma-se o par (a,b): {(a,1),(a,2),(a,3)}.",
                     EASY),
            practice("conj-produto-p6", "conj-produto",
                     "Se `(x, y) = (3, 5)`, então `x` e `y` valem:",
                     ["x = 5, y = 3", "x = 3, y = 5",
                      "x = 3, y = 3", "x = 5, y = 5"], 1,
                     "Pares ordenados são iguais sse as coordenadas correspondentes são iguais: x = 3 e y = 5.",
                     EASY),
        ),
    ),
    concept(
        id="conj-operacoes",
        title="Operações sobre conjuntos e De Morgan",
        unit=1,
        topic=3,
        prerequisites=("conj-subconjunto", "dem-direta"),
        content="""## Intuição
Combinamos conjuntos (dentro de um universo `U`): **união** junta, **interseção** pega o comum, **diferença** remove, **complementar** inverte em relação a `U`.

## Definição formal
- `A ∪ B = {x : x ∈ A ∨ x ∈ B}`
- `A ∩ B = {x : x ∈ A ∧ x ∈ B}`
- `A − B = {x : x ∈ A ∧ x ∉ B}`
- `Aᶜ = U − A`
- **Leis de De Morgan:** `(A ∪ B)ᶜ = Aᶜ ∩ Bᶜ` e `(A ∩ B)ᶜ = Aᶜ ∪ Bᶜ`.
- Identidades úteis: `A ∩ (A ∪ B) = A` (absorção), `A − (A ∩ B) = A − B`, `A ⊆ B ⟹ A ∪ B = B`.

## Exemplo resolvido
`U = {1,…,6}`, `A = {1,2,3}`, `B = {2,3,4}`:
`A ∪ B = {1,2,3,4}`, `A ∩ B = {2,3}`, `A − B = {1}`, `Aᶜ = {4,5,6}`.
De Morgan: `(A ∪ B)ᶜ = {5,6}` e `Aᶜ ∩ Bᶜ = {4,5,6} ∩ {1,5,6} = {5,6}`. ✓

## Erros comuns
- Trocar a direção de `A − B` (é o que está em `A` e não em `B`).
- Errar De Morgan (o complemento troca `∪` por `∩` e vice-versa).""",
        questions=(
            graded("conj-operacoes-q1", "conj-operacoes",
                   "Com `A = {1,2,3}` e `B = {2,3,4}`, `A − B` é:",
                   ["{2,3}", "{1}", "{4}", "{1,2,3,4}"], 1,
                   "A − B = elementos de A que não estão em B = {1}.",
                   EASY),
            graded("conj-operacoes-q2", "conj-operacoes",
                   "Pela Lei de De Morgan, `(A ∪ B)ᶜ` é igual a:",
                   ["Aᶜ ∪ Bᶜ", "Aᶜ ∩ Bᶜ", "A ∩ B", "(A ∩ B)ᶜ"], 1,
                   "De Morgan: o complemento da união é a interseção dos complementos.",
                   MEDIUM),
            graded("conj-operacoes-q3", "conj-operacoes",
                   "A identidade de absorção `A ∩ (A ∪ B)` é igual a:",
                   ["A ∪ B", "A", "B", "∅"], 1,
                   "Todo elemento de A já está em A ∪ B, então A ∩ (A ∪ B) = A.",
                   MEDIUM),
            graded("conj-operacoes-q4", "conj-operacoes",
                   "Com `U = {1,…,10}`, `A = {1,2,3,4,5}`, qual é `Aᶜ`?",
                   ["{1,2,3,4,5}", "{6,7,8,9,10}", "{}", "{1,…,10}"], 1,
                   "Aᶜ = U − A = {6,7,8,9,10}.",
                   EASY),
            graded("conj-operacoes-q5", "conj-operacoes",
                   "Com `A = {1,2,3}`, `B = {3,4,5}`, `C = {5,6}`, `(A ∪ B) ∩ C` é:",
                   ["{5}", "{5,6}", "{1,2,3,4,5,6}", "{3,5}"], 0,
                   "A ∪ B = {1,2,3,4,5}. Interseção com C = {5,6}: {5}.",
                   MEDIUM),
            graded("conj-operacoes-q6", "conj-operacoes",
                   "`A ∩ Aᶜ` é sempre igual a:",
                   ["A", "U", "∅", "Aᶜ"], 2,
                   "Nenhum elemento pode pertencer a A e ao complementar de A simultaneamente: A ∩ Aᶜ = ∅.",
                   EASY),
            graded("conj-operacoes-q7", "conj-operacoes",
                   "`A ∪ Aᶜ` é sempre igual a:",
                   ["A", "∅", "Aᶜ", "U"], 3,
                   "Todo elemento do universo está em A ou fora de A: A ∪ Aᶜ = U.",
                   MEDIUM),
        ),
        practice=(
            practice("conj-operacoes-p1", "conj-operacoes",
                     "`(A ∩ B)ᶜ` é igual a:",
                     ["Aᶜ ∩ Bᶜ", "Aᶜ ∪ Bᶜ", "A ∪ B", "A − B"], 1,
                     "Segunda lei de De Morgan: o complemento da interseção é a união dos complementos.",
                     MEDIUM),
            practice("conj-operacoes-p2", "conj-operacoes",
                     "Se `A ⊆ B`, então `A ∪ B` é:",
                     ["A", "B", "∅", "Aᶜ"], 1,
                     "Se A já está contido em B, juntar A não acrescenta nada: A ∪ B = B.",
                     MEDIUM),
            practice("conj-operacoes-p3", "conj-operacoes",
                     "`A − (A ∩ B)` é igual a:",
                     ["A ∩ B", "A − B", "B − A", "∅"], 1,
                     "Tirar de A o que A tem em comum com B deixa exatamente A − B.",
                     HARD),
            practice("conj-operacoes-p4", "conj-operacoes",
                     "Com `A = {1,2,3}` e `B = {2,3,4}`, `A ∩ B` é:",
                     ["{1,4}", "{2,3}", "{1,2,3,4}", "∅"], 1,
                     "A ∩ B contém os elementos comuns: 2 e 3.",
                     EASY),
            practice("conj-operacoes-p5", "conj-operacoes",
                     "`∅ − A` é igual a:",
                     ["A", "∅", "Aᶜ", "U"], 1,
                     "Não há elementos em ∅ para remover de A, logo ∅ − A = ∅.",
                     EASY),
            practice("conj-operacoes-p6", "conj-operacoes",
                     "`(Aᶜ)ᶜ` é igual a:",
                     ["∅", "U", "Aᶜ", "A"], 3,
                     "Complementar duas vezes retorna ao original: (Aᶜ)ᶜ = A (involução do complemento).",
                     MEDIUM),
        ),
    ),
    # ───────────────────────── Funções (topic 4) ─────────────────────────
    concept(
        id="fun-definicao",
        title="Funções: domínio, contradomínio e imagem",
        unit=1,
        topic=4,
        prerequisites=("conj-produto",),
        content="""## Intuição
Uma **função** `f: A → B` associa a **cada** elemento de `A` **exatamente um** elemento de `B`. É um tipo especial de relação (subconjunto de `A × B`) que é **total** (todo `a` tem imagem) e **funcional** (a imagem é única).

## Definição formal
`f ⊆ A × B` é função (total) se, para todo `a ∈ A`, existe **exatamente um** `b ∈ B` com `(a,b) ∈ f`. Escreve-se `f(a) = b`.
- `A` = **domínio**; `B` = **contradomínio**.
- **Imagem:** `Img(f) = f(A) = {b ∈ B : ∃a ∈ A, f(a) = b}` ⊆ `B`.
Nem todo elemento de `B` precisa ser atingido — a imagem é um subconjunto do contradomínio.

## Exemplo resolvido
`f: ℝ → ℝ`, `f(x) = x²`. Domínio `ℝ`, contradomínio `ℝ`, mas `Img(f) = [0, ∞)` — os negativos não são atingidos.

## Erros comuns
- Confundir **contradomínio** (onde os valores *podem* cair) com **imagem** (onde *de fato* caem).
- Aceitar como função algo que deixa um elemento do domínio sem imagem, ou que dá dois valores a um mesmo `a`.""",
        questions=(
            graded("fun-definicao-q1", "fun-definicao",
                   "Para `f ⊆ A × B` ser função (total), exige-se que cada `a ∈ A` tenha:",
                   ["pelo menos um b", "exatamente um b",
                    "no máximo um b", "nenhum b"], 1,
                   "Função total: para todo a do domínio existe EXATAMENTE um b. (Total = existe; funcional = único.)",
                   MEDIUM),
            graded("fun-definicao-q2", "fun-definicao",
                   "A **imagem** de `f: A → B` é:",
                   ["sempre igual a B",
                    "o subconjunto de B efetivamente atingido por f",
                    "igual ao domínio A",
                    "o conjunto A × B"], 1,
                   "Img(f) = {b ∈ B : ∃a, f(a)=b} ⊆ B. Pode ser menor que o contradomínio.",
                   MEDIUM),
            graded("fun-definicao-q3", "fun-definicao",
                   "Para `f: ℝ → ℝ`, `f(x) = x²`, a imagem é:",
                   ["ℝ", "[0, ∞)", "(−∞, 0]", "{0}"], 1,
                   "Quadrados são ≥ 0 e todo não-negativo é atingido, então Img(f) = [0, ∞).",
                   MEDIUM),
            graded("fun-definicao-q4", "fun-definicao",
                   "`{(0,2),(2,4),(4,6),(6,0)}` com domínio `{0,2,4,6}` é função?",
                   ["Não, pois há imagem repetida",
                    "Não, pois falta algum elemento do domínio",
                    "Sim, pois cada elemento do domínio tem exatamente uma imagem",
                    "Não, pois 0 aparece no domínio e no contradomínio"], 2,
                   "Cada elemento 0, 2, 4, 6 aparece exatamente uma vez como primeira coordenada com imagem única. É função.",
                   MEDIUM),
            graded("fun-definicao-q5", "fun-definicao",
                   "Se `f: A → B` e `|A| = 5`, `|Img(f)| = 3`, então:",
                   ["f é injetora", "f não é injetora",
                    "f é sobrejetora", "f não é função"], 1,
                   "5 elementos do domínio mapeiam em apenas 3 imagens distintas: pelo menos dois compartilham imagem, violando injetividade.",
                   HARD),
            graded("fun-definicao-q6", "fun-definicao",
                   "A diferença entre contradomínio e imagem é que:",
                   ["são sempre iguais",
                    "o contradomínio é onde os valores podem cair; a imagem é onde de fato caem",
                    "a imagem é sempre maior",
                    "o contradomínio depende da injetividade"], 1,
                   "Contradomínio é o conjunto de chegada declarado; imagem é o subconjunto efetivamente atingido por f.",
                   EASY),
            graded("fun-definicao-q7", "fun-definicao",
                   "`{(1,a),(2,b),(3,a)}` é função de `{1,2,3}` em `{a,b}`?",
                   ["Não, pois a aparece duas vezes como imagem",
                    "Sim, pois cada elemento do domínio tem exatamente uma imagem",
                    "Não, pois 3 não tem imagem",
                    "Não, pois a ≠ b"], 1,
                   "Cada elemento do domínio (1, 2, 3) aparece exatamente uma vez como primeira coordenada. Imagens repetidas são permitidas — o que importa é unicidade por argumento.",
                   MEDIUM),
        ),
        practice=(
            practice("fun-definicao-p1", "fun-definicao",
                     "O conjunto de **partida** de `f: A → B` chama-se:",
                     ["imagem", "domínio", "contradomínio", "núcleo"], 1,
                     "A é o domínio; B é o contradomínio; Img(f) ⊆ B é a imagem.",
                     EASY),
            practice("fun-definicao-p2", "fun-definicao",
                     "`{(0,2),(2,4),(4,6),(6,0)}` com domínio {0,2,4,6}, contradomínio {0,2,4,6} é função?",
                     ["Não, falta imagem para algum elemento",
                      "Sim, cada elemento do domínio tem exatamente uma imagem",
                      "Não, há imagem repetida",
                      "Não é relação"], 1,
                     "Cada um de 0,2,4,6 aparece uma vez como primeira coordenada com imagem única — é função.",
                     MEDIUM),
            practice("fun-definicao-p3", "fun-definicao",
                     "Por que `{(2,3),(2,5)}` NÃO é função?",
                     ["domínio vazio", "o elemento 2 tem duas imagens (3 e 5)",
                      "contradomínio vazio", "não há pares"], 1,
                     "Função exige imagem única; aqui 2 ↦ 3 e 2 ↦ 5 viola a unicidade.",
                     EASY),
            practice("fun-definicao-p4", "fun-definicao",
                     "Se `f: ℕ → ℕ`, `f(n) = n + 1`, qual é `Img(f)`?",
                     ["ℕ", "{1, 2, 3, …} = ℕ \\ {0}",
                      "{0}", "{0, 1}"], 1,
                     "f(0) = 1, f(1) = 2, … Todo natural ≥ 1 é atingido, mas 0 não é imagem de nenhum n. Logo Img(f) = ℕ \\ {0}.",
                     MEDIUM),
            practice("fun-definicao-p5", "fun-definicao",
                     "Uma função `f: A → B` é um tipo especial de:",
                     ["conjunto", "subconjunto de A × B",
                      "subconjunto de B", "par ordenado"], 1,
                     "Formalmente, f ⊆ A × B com a propriedade de totalidade e funcionalidade.",
                     MEDIUM),
            practice("fun-definicao-p6", "fun-definicao",
                     "Se `f: {1,2,3} → {a,b,c,d}`, a imagem de f pode ter no máximo:",
                     ["2 elementos", "3 elementos", "4 elementos", "7 elementos"], 1,
                     "|Img(f)| ≤ |Dom(f)| = 3. A imagem não pode ter mais elementos que o domínio.",
                     EASY),
        ),
    ),
    concept(
        id="fun-injetora",
        title="Função injetora",
        unit=1,
        topic=4,
        prerequisites=("fun-definicao",),
        content="""## Intuição
Uma função é **injetora** (ou 1-1) quando elementos **diferentes** do domínio vão para imagens **diferentes** — nunca dois `a` colidem no mesmo `b`.

## Definição formal
`f` é injetora sse, para todos `x₁, x₂ ∈ Dom(f)`:
`f(x₁) = f(x₂) → x₁ = x₂` (equivalente: `x₁ ≠ x₂ → f(x₁) ≠ f(x₂)`).

## Exemplo resolvido
- `f: ℤ → ℤ`, `f(x) = 2x`: se `2x₁ = 2x₂` então `x₁ = x₂`. **Injetora.**
- `g: ℝ → ℝ`, `g(x) = x²`: `g(−2) = g(2) = 4` com `−2 ≠ 2`. **Não** injetora.

Técnica padrão: suponha `f(x₁) = f(x₂)` e mostre `x₁ = x₂`.

## Erros comuns
- Verificar injetividade só em alguns pontos (precisa valer para todos).
- Trocar a definição pela de sobrejetora.""",
        questions=(
            graded("fun-injetora-q1", "fun-injetora",
                   "`f` é injetora quando:",
                   ["Img(f) = B",
                    "f(x₁) = f(x₂) implica x₁ = x₂",
                    "todo a tem imagem",
                    "f tem inversa à direita"], 1,
                   "Injetora: imagens iguais forçam argumentos iguais (sem colisões).",
                   EASY),
            graded("fun-injetora-q2", "fun-injetora",
                   "Por que `f: ℝ → ℝ`, `f(x) = x²` **não** é injetora?",
                   ["não tem imagem para alguns x",
                    "f(−2) = f(2) com −2 ≠ 2",
                    "não atinge 4",
                    "é crescente"], 1,
                   "Dois argumentos distintos (−2 e 2) têm a mesma imagem (4): viola a injetividade.",
                   MEDIUM),
            graded("fun-injetora-q3", "fun-injetora",
                   "A função `f: ℤ → ℤ`, `f(x) = 2x` é:",
                   ["não injetora", "injetora",
                    "não é função", "constante"], 1,
                   "2x₁ = 2x₂ ⇒ x₁ = x₂, logo injetora (embora não seja sobrejetora em ℤ).",
                   MEDIUM),
            graded("fun-injetora-q4", "fun-injetora",
                   "`f: ℝ → ℝ`, `f(x) = |x|` é injetora?",
                   ["Sim", "Não, pois f(−3) = f(3) = 3",
                    "Sim, pois |x| ≥ 0", "Depende do domínio"], 1,
                   "f(−3) = f(3) = 3, mas −3 ≠ 3: dois argumentos distintos com a mesma imagem viola injetividade.",
                   EASY),
            graded("fun-injetora-q5", "fun-injetora",
                   "Para provar que `f` NÃO é injetora, basta:",
                   ["mostrar que todo b tem pré-imagem",
                    "exibir x₁ ≠ x₂ com f(x₁) = f(x₂)",
                    "mostrar que f é crescente",
                    "provar que Img(f) = B"], 1,
                   "Um único contraexemplo com dois argumentos distintos de mesma imagem refuta a injetividade.",
                   MEDIUM),
            graded("fun-injetora-q6", "fun-injetora",
                   "`f: ℝ → ℝ`, `f(x) = x³ − x` é injetora?",
                   ["Sim", "Não, pois f(0) = f(1) = f(−1) = 0",
                    "Sim, pois é cúbica", "Não, pois não é contínua"], 1,
                   "f(0) = 0, f(1) = 0, f(−1) = 0: três argumentos distintos com mesma imagem. Não é injetora.",
                   HARD),
            graded("fun-injetora-q7", "fun-injetora",
                   "Se `f: A → B` é injetora e `|A| = n` finito, então `|Img(f)|` é:",
                   ["n", "n²", "2ⁿ", "|B|"], 0,
                   "Injetora: argumentos distintos geram imagens distintas, logo |Img(f)| = |A| = n.",
                   MEDIUM),
        ),
        practice=(
            practice("fun-injetora-p1", "fun-injetora",
                     "A técnica padrão para provar injetividade é:",
                     ["supor f(x₁)=f(x₂) e concluir x₁=x₂",
                      "exibir um valor de f",
                      "mostrar que Img(f)=B",
                      "usar indução"], 0,
                     "Assume-se imagens iguais e deduz-se que os argumentos coincidem.",
                     MEDIUM),
            practice("fun-injetora-p2", "fun-injetora",
                     "`f(x) = 3x − 1` de ℝ em ℝ é injetora?",
                     ["Sim", "Não", "Só para x > 0", "Não é função"], 0,
                     "3x₁−1 = 3x₂−1 ⇒ 3x₁ = 3x₂ ⇒ x₁ = x₂. Injetora.",
                     EASY),
            practice("fun-injetora-p3", "fun-injetora",
                     "Uma função constante `f(x) = c` (domínio com ≥2 elementos) é injetora?",
                     ["Sim", "Não", "Sempre", "Só se c = 0"], 1,
                     "Todos os argumentos têm a mesma imagem c, então não é injetora.",
                     EASY),
            practice("fun-injetora-p4", "fun-injetora",
                     "`f: ℝ → ℝ`, `f(x) = 2x + 5` é injetora?",
                     ["Sim", "Não", "Só para x > 0", "Só para x inteiro"], 0,
                     "2x₁+5 = 2x₂+5 ⇒ 2x₁ = 2x₂ ⇒ x₁ = x₂. Funções afins com coeficiente angular não-nulo são injetoras.",
                     EASY),
            practice("fun-injetora-p5", "fun-injetora",
                     "A definição contrapositiva de injetividade é:",
                     ["f(x₁) = f(x₂) → x₁ = x₂",
                      "x₁ ≠ x₂ → f(x₁) ≠ f(x₂)",
                      "f(x₁) ≠ f(x₂) → x₁ ≠ x₂",
                      "x₁ = x₂ → f(x₁) = f(x₂)"], 1,
                     "A contrapositiva de 'f(x₁)=f(x₂) → x₁=x₂' é 'x₁≠x₂ → f(x₁)≠f(x₂)'. Ambas são equivalentes.",
                     MEDIUM),
            practice("fun-injetora-p6", "fun-injetora",
                     "Se `f: {1,2,3} → {a,b,c}` é injetora, quantas imagens distintas ela produz?",
                     ["1", "2", "3", "6"], 2,
                     "Injetora: cada argumento produz imagem distinta. Com 3 argumentos, temos 3 imagens distintas.",
                     EASY),
        ),
    ),
    concept(
        id="fun-sobre-bij",
        title="Sobrejetora, bijetora e inversa",
        unit=1,
        topic=4,
        prerequisites=("fun-injetora",),
        content="""## Intuição
**Sobrejetora**: a imagem cobre **todo** o contradomínio (nada sobra em `B`). **Bijetora**: injetora **e** sobrejetora — um casamento perfeito entre `A` e `B`, que admite **inversa**.

## Definição formal
- **Sobrejetora:** `∀b ∈ B, ∃a ∈ A` com `f(a) = b` (i.e., `Img(f) = B`).
- **Bijetora:** injetora e sobrejetora.
- **Inversa:** se `f` é bijetora, `f⁻¹: B → A` com `f⁻¹(y) = x ⟺ f(x) = y`. Vale `f⁻¹ ∘ f = ι_A` e `f ∘ f⁻¹ = ι_B` (identidades).

## Exemplo resolvido
`g: ℝ → ℝ`, `g(x) = x³`: injetora (estritamente crescente) e sobrejetora (cobre `ℝ`), logo **bijetora**; `g⁻¹(y) = ∛y`.
`f: ℤ → ℤ`, `f(x) = 2x`: injetora mas **não** sobrejetora (3 não é imagem), logo não bijetora.

## Erros comuns
- Sobrejetividade depende do **contradomínio** escolhido.
- Achar que injetora ⟹ bijetora (falta a sobrejetividade).
- Só funções **bijetoras** têm inversa (de duas mãos).""",
        questions=(
            graded("fun-sobre-bij-q1", "fun-sobre-bij",
                   "`f` é sobrejetora quando:",
                   ["f(x₁)=f(x₂) ⇒ x₁=x₂",
                    "Img(f) = contradomínio B",
                    "todo a tem imagem",
                    "é crescente"], 1,
                   "Sobrejetora: todo elemento de B é atingido, ou seja, a imagem é o contradomínio inteiro.",
                   EASY),
            graded("fun-sobre-bij-q2", "fun-sobre-bij",
                   "Uma função é bijetora se e somente se é:",
                   ["injetora ou sobrejetora", "injetora e sobrejetora",
                    "constante", "crescente"], 1,
                   "Bijetora = injetora E sobrejetora. Só então existe inversa de duas mãos.",
                   MEDIUM),
            graded("fun-sobre-bij-q3", "fun-sobre-bij",
                   "Qual função admite inversa `f⁻¹: B → A`?",
                   ["qualquer função", "apenas funções bijetoras",
                    "apenas injetoras", "apenas sobrejetoras"], 1,
                   "A inversa (de duas mãos) existe exatamente para bijeções.",
                   MEDIUM),
            graded("fun-sobre-bij-q4", "fun-sobre-bij",
                   "`f: ℤ → ℤ`, `f(x) = 2x` é sobrejetora?",
                   ["Sim", "Não, pois 3 não é imagem de nenhum inteiro",
                    "Sim, pois é injetora", "Depende do contradomínio"], 1,
                   "f(x) = 2x só produz pares. O ímpar 3 ∈ ℤ não é atingido, logo f não é sobrejetora em ℤ.",
                   MEDIUM),
            graded("fun-sobre-bij-q5", "fun-sobre-bij",
                   "Se `f` é bijetora, então `f⁻¹ ∘ f` é:",
                   ["f", "f⁻¹", "a identidade no domínio", "a função nula"], 2,
                   "Para bijeções, f⁻¹ ∘ f = ι_A (identidade no domínio): (f⁻¹∘f)(x) = f⁻¹(f(x)) = x.",
                   MEDIUM),
            graded("fun-sobre-bij-q6", "fun-sobre-bij",
                   "`f: ℝ → [0, ∞)`, `f(x) = x²` é sobrejetora?",
                   ["Sim, pois todo y ≥ 0 tem pré-imagem (±√y)",
                    "Não, pois não atinge negativos",
                    "Sim, pois é crescente",
                    "Não, pois não é injetora"], 0,
                   "Com contradomínio [0,∞), todo y ≥ 0 é atingido por x = √y. A sobrejetividade depende do contradomínio escolhido.",
                   HARD),
            graded("fun-sobre-bij-q7", "fun-sobre-bij",
                   "Se `f: A → B` é bijetora com `A` e `B` finitos, então:",
                   ["|A| > |B|", "|A| < |B|", "|A| = |B|", "|A| + |B| = 0"], 2,
                   "Bijeção entre conjuntos finitos implica que têm a mesma quantidade de elementos.",
                   EASY),
        ),
        practice=(
            practice("fun-sobre-bij-p1", "fun-sobre-bij",
                     "`g: ℝ → ℝ`, `g(x) = x³` é:",
                     ["apenas injetora", "apenas sobrejetora",
                      "bijetora", "nem injetora nem sobrejetora"], 2,
                     "x³ é estritamente crescente (injetora) e cobre todo ℝ (sobrejetora) ⇒ bijetora, com inversa ∛y.",
                     MEDIUM),
            practice("fun-sobre-bij-p2", "fun-sobre-bij",
                     "A inversa de `f(x) = 2x` (vista como bijeção ℝ→ℝ) é:",
                     ["2y", "y/2", "y − 2", "y²"], 1,
                     "f(x)=2x=y ⇒ x = y/2, logo f⁻¹(y) = y/2.",
                     EASY),
            practice("fun-sobre-bij-p3", "fun-sobre-bij",
                     "A sobrejetividade de uma função depende:",
                     ["só do domínio", "do contradomínio escolhido",
                      "da ordem dos pares", "de nada"], 1,
                     "Mudar o contradomínio pode tornar uma função sobrejetora (ex.: f(x)=x² é sobre [0,∞), não sobre ℝ).",
                     MEDIUM),
            practice("fun-sobre-bij-p4", "fun-sobre-bij",
                     "`f: {1,2,3} → {a,b,c}`, `f = {(1,a),(2,b),(3,c)}` é bijetora?",
                     ["Sim", "Não, falta sobrejetividade",
                      "Não, falta injetividade", "Não é função"], 0,
                     "Cada argumento tem imagem única e distinta, e todo elemento de {a,b,c} é atingido. É bijetora.",
                     EASY),
            practice("fun-sobre-bij-p5", "fun-sobre-bij",
                     "Se `f` é injetora mas NÃO sobrejetora, ela é bijetora?",
                     ["Sim", "Não", "Depende do domínio", "Sempre"], 1,
                     "Bijetora exige AMBAS: injetora E sobrejetora. Faltando uma, não é bijeção.",
                     EASY),
            practice("fun-sobre-bij-p6", "fun-sobre-bij",
                     "A inversa de `f(x) = x³` (de ℝ em ℝ) é:",
                     ["x^(1/3) (raiz cúbica)", "x³",
                      "1/x³", "não existe"], 0,
                     "f(x)=x³ é bijetora em ℝ (crescente e cobre todo ℝ). Sua inversa é f⁻¹(y) = ∛y.",
                     MEDIUM),
        ),
    ),
    concept(
        id="fun-composicao",
        title="Composição de funções",
        unit=1,
        topic=4,
        prerequisites=("fun-sobre-bij",),
        content="""## Intuição
**Compor** é encadear: `(g ∘ f)(x) = g(f(x))` — primeiro aplica `f`, depois `g`. A composição em geral **não** é comutativa (`f ∘ g ≠ g ∘ f`).

## Definição formal
Dadas `f: X → Y` e `g: Y → Z`, `g ∘ f: X → Z`, `(g ∘ f)(x) = g(f(x))`.
Propriedades (provadas no curso):
- Se `f` e `g` são injetoras, então `g ∘ f` é injetora.
- Se `f` e `g` são sobrejetoras, então `g ∘ f` é sobrejetora.
- Se `g ∘ f` é injetora, então `f` é injetora (mas não necessariamente `g`).
- Se `g ∘ f` é sobrejetora, então `g` é sobrejetora (mas não necessariamente `f`).

## Exemplo resolvido
`f(x) = x + 1`, `g(x) = 2x`. Então `(g ∘ f)(x) = 2(x+1) = 2x + 2`, enquanto `(f ∘ g)(x) = 2x + 1`. Diferentes — não comuta.

## Erros comuns
- Inverter a ordem: `(g ∘ f)(x) = g(f(x))`, não `f(g(x))`.
- Achar que `g ∘ f` injetora garante `g` injetora (garante só `f`).""",
        questions=(
            graded("fun-composicao-q1", "fun-composicao",
                   "`(g ∘ f)(x)` é igual a:",
                   ["f(g(x))", "g(f(x))", "f(x)·g(x)", "f(x) + g(x)"], 1,
                   "Composição: aplica-se f primeiro, depois g: (g∘f)(x) = g(f(x)).",
                   EASY),
            graded("fun-composicao-q2", "fun-composicao",
                   "Se `f` e `g` são ambas injetoras, então `g ∘ f` é:",
                   ["não injetora", "injetora",
                    "constante", "sobrejetora"], 1,
                   "A composição de injetoras é injetora (propriedade demonstrada na disciplina).",
                   MEDIUM),
            graded("fun-composicao-q3", "fun-composicao",
                   "Se `g ∘ f` é injetora, podemos garantir que:",
                   ["g é injetora", "f é injetora",
                    "ambas são injetoras", "nenhuma é injetora"], 1,
                   "g∘f injetora ⇒ f injetora; g pode não ser. (Contraexemplos clássicos do curso.)",
                   HARD),
            graded("fun-composicao-q4", "fun-composicao",
                   "Com `f(x) = x + 1` e `g(x) = 2x`, `(f ∘ g)(3)` vale:",
                   ["7", "8", "6", "9"], 0,
                   "(f∘g)(3) = f(g(3)) = f(6) = 7. Note: f∘g ≠ g∘f.",
                   EASY),
            graded("fun-composicao-q5", "fun-composicao",
                   "A composição de funções é comutativa?",
                   ["Sim, sempre", "Não, em geral f∘g ≠ g∘f",
                    "Sim, se ambas são injetoras", "Sim, se ambas são sobrejetoras"], 1,
                   "Em geral f∘g ≠ g∘f. Exemplo: f(x)=x+1, g(x)=2x dá (g∘f)(x)=2x+2, (f∘g)(x)=2x+1.",
                   MEDIUM),
            graded("fun-composicao-q6", "fun-composicao",
                   "Se `f` e `g` são bijetoras, então `g ∘ f` é:",
                   ["apenas injetora", "apenas sobrejetora",
                    "bijetora", "não é função"], 2,
                   "Composição de injetoras é injetora, de sobrejetoras é sobrejetora. Logo composição de bijetoras é bijetora.",
                   MEDIUM),
            graded("fun-composicao-q7", "fun-composicao",
                   "Se `g ∘ f` é sobrejetora e `f` é sobrejetora, podemos concluir que:",
                   ["g é injetora", "g é sobrejetora",
                    "f é injetora", "nada sobre g"], 1,
                   "g∘f sobrejetora já garante g sobrejetora (independentemente de f). Com f também sobrejetora, a conclusão se mantém.",
                   HARD),
        ),
        practice=(
            practice("fun-composicao-p1", "fun-composicao",
                     "Com `f(x)=x+1` e `g(x)=2x`, `(g ∘ f)(3)` vale:",
                     ["7", "8", "6", "9"], 1,
                     "(g∘f)(3) = g(f(3)) = g(4) = 8.",
                     EASY),
            practice("fun-composicao-p2", "fun-composicao",
                     "Se `f` e `g` são sobrejetoras, então `g ∘ f` é:",
                     ["injetora", "sobrejetora", "constante", "não é função"], 1,
                     "A composição de sobrejetoras é sobrejetora.",
                     MEDIUM),
            practice("fun-composicao-p3", "fun-composicao",
                     "Se `g ∘ f` é sobrejetora, garante-se que:",
                     ["f é sobrejetora", "g é sobrejetora",
                      "ambas são", "nenhuma é"], 1,
                     "g∘f sobrejetora ⇒ g sobrejetora; f pode não ser.",
                     HARD),
            practice("fun-composicao-p4", "fun-composicao",
                     "Com `f(x) = x²` e `g(x) = x + 3`, `(g ∘ f)(2)` vale:",
                     ["7", "25", "9", "5"], 0,
                     "(g∘f)(2) = g(f(2)) = g(4) = 4 + 3 = 7.",
                     EASY),
            practice("fun-composicao-p5", "fun-composicao",
                     "Para que `g ∘ f` esteja definida, é necessário que:",
                     ["Dom(g) = Dom(f)", "Img(f) ⊆ Dom(g)",
                      "g = f", "f seja bijetora"], 1,
                     "g∘f(x) = g(f(x)): a saída de f deve ser entrada válida de g, ou seja, Img(f) ⊆ Dom(g).",
                     MEDIUM),
            practice("fun-composicao-p6", "fun-composicao",
                     "Se `f` é bijetora, então `f ∘ f⁻¹` é:",
                     ["f", "f⁻¹", "a identidade no contradomínio", "indefinida"], 2,
                     "f ∘ f⁻¹ = ι_B (identidade no contradomínio): (f∘f⁻¹)(y) = f(f⁻¹(y)) = y.",
                     MEDIUM),
        ),
    ),
    concept(
        id="fun-imagem-inversa",
        title="Imagem direta e imagem inversa de conjuntos",
        unit=1,
        topic=4,
        prerequisites=("fun-definicao",),
        content="""## Intuição
Dada `f: A → B`, podemos aplicar `f` a um **conjunto** `E ⊆ A` (imagem direta) ou puxar de volta um `D ⊆ B` (imagem inversa). A imagem inversa **existe mesmo quando `f` não é invertível**.

## Definição formal
- **Imagem direta:** `f(E) = {f(x) : x ∈ E} = {y : ∃x ∈ E, f(x) = y}`.
- **Imagem inversa:** `f⁻¹(D) = {x ∈ A : f(x) ∈ D}`.
Propriedades: `f(C ∪ D) = f(C) ∪ f(D)`; `f(C ∩ D) ⊆ f(C) ∩ f(D)` (igualdade se `f` injetora); `f⁻¹(W ∪ Z) = f⁻¹(W) ∪ f⁻¹(Z)`; `f⁻¹(W ∩ Z) = f⁻¹(W) ∩ f⁻¹(Z)`.

## Exemplo resolvido
`f: ℝ → ℝ`, `f(x) = x²`. `f⁻¹({4}) = {−2, 2}` (todos os `x` com `x² = 4`). Aqui `f⁻¹` é a imagem inversa de um conjunto — não a função inversa (que nem existe, pois `f` não é injetora).

## Erros comuns
- Confundir imagem inversa `f⁻¹(D)` (sempre definida) com função inversa `f⁻¹` (só para bijeções).
- Supor `f(C ∩ D) = f(C) ∩ f(D)` sem injetividade (vale só `⊆` em geral).""",
        questions=(
            graded("fun-imagem-inversa-q1", "fun-imagem-inversa",
                   "A imagem inversa `f⁻¹(D)` é definida como:",
                   ["{f(x) : x ∈ D}",
                    "{x ∈ A : f(x) ∈ D}",
                    "{x : x ∉ D}",
                    "a função inversa de f"], 1,
                   "f⁻¹(D) = {x ∈ A : f(x) ∈ D} — os elementos cuja imagem cai em D.",
                   MEDIUM),
            graded("fun-imagem-inversa-q2", "fun-imagem-inversa",
                   "Para `f(x) = x²` em ℝ, `f⁻¹({4})` é:",
                   ["{2}", "{−2, 2}", "{4}", "{16}"], 1,
                   "São todos os x com x² = 4: x = 2 ou x = −2.",
                   MEDIUM),
            graded("fun-imagem-inversa-q3", "fun-imagem-inversa",
                   "Em geral, `f(C ∩ D)` está relacionado a `f(C) ∩ f(D)` por:",
                   ["igualdade sempre", "f(C ∩ D) ⊆ f(C) ∩ f(D)",
                    "f(C ∩ D) ⊇ f(C) ∩ f(D)", "não há relação"], 1,
                   "Vale apenas a inclusão ⊆ em geral; a igualdade requer f injetora.",
                   HARD),
            graded("fun-imagem-inversa-q4", "fun-imagem-inversa",
                   "Para `f(x) = x²` em ℝ, `f⁻¹({0, 1, 4})` é:",
                   ["{0, 1, 2}", "{0, 1, −1, 2, −2}",
                    "{0, 1, 4}", "{1, 4}"], 1,
                   "x²=0 ⇒ x=0; x²=1 ⇒ x=±1; x²=4 ⇒ x=±2. Logo f⁻¹({0,1,4}) = {−2,−1,0,1,2}.",
                   MEDIUM),
            graded("fun-imagem-inversa-q5", "fun-imagem-inversa",
                   "`f⁻¹(W ∩ Z)` é igual a:",
                   ["f⁻¹(W) ∪ f⁻¹(Z)", "f⁻¹(W) ∩ f⁻¹(Z)",
                    "f(W) ∩ f(Z)", "W ∩ Z"], 1,
                   "A imagem inversa preserva interseção: f⁻¹(W∩Z) = f⁻¹(W) ∩ f⁻¹(Z).",
                   MEDIUM),
            graded("fun-imagem-inversa-q6", "fun-imagem-inversa",
                   "Se `f` é injetora, então `f(C ∩ D)` é igual a:",
                   ["f(C) ∪ f(D)", "f(C) ∩ f(D)",
                    "f(C) − f(D)", "∅"], 1,
                   "Com f injetora, a inclusão f(C∩D) ⊆ f(C)∩f(D) se torna igualdade.",
                   HARD),
            graded("fun-imagem-inversa-q7", "fun-imagem-inversa",
                   "Para `f: ℝ → ℝ`, `f(x) = 2x`, a imagem direta `f({1, 2, 3})` é:",
                   ["{1, 2, 3}", "{2, 4, 6}", "{0.5, 1, 1.5}", "{3, 5, 7}"], 1,
                   "f(E) = {f(x) : x ∈ E} = {2·1, 2·2, 2·3} = {2, 4, 6}.",
                   EASY),
        ),
        practice=(
            practice("fun-imagem-inversa-p1", "fun-imagem-inversa",
                     "A imagem inversa de um conjunto está definida:",
                     ["só se f é bijetora", "para qualquer função f",
                      "só se f é injetora", "nunca"], 1,
                     "f⁻¹(D) faz sentido para qualquer f — não exige que f tenha inversa.",
                     MEDIUM),
            practice("fun-imagem-inversa-p2", "fun-imagem-inversa",
                     "`f⁻¹(W ∪ Z)` é igual a:",
                     ["f⁻¹(W) ∩ f⁻¹(Z)", "f⁻¹(W) ∪ f⁻¹(Z)",
                      "f(W) ∪ f(Z)", "∅"], 1,
                     "A imagem inversa preserva união (e também interseção): f⁻¹(W∪Z) = f⁻¹(W) ∪ f⁻¹(Z).",
                     MEDIUM),
            practice("fun-imagem-inversa-p3", "fun-imagem-inversa",
                     "A imagem direta `f(E)` é:",
                     ["{x : f(x) ∈ E}", "{f(x) : x ∈ E}",
                      "E", "Eᶜ"], 1,
                     "f(E) = conjunto das imagens dos elementos de E.",
                     EASY),
            practice("fun-imagem-inversa-p4", "fun-imagem-inversa",
                     "Para `f(x) = x + 1`, `f⁻¹({3, 5, 7})` é:",
                     ["{3, 5, 7}", "{2, 4, 6}",
                      "{4, 6, 8}", "{1, 3, 5}"], 1,
                     "x+1 ∈ {3,5,7} ⇒ x ∈ {2,4,6}. Logo f⁻¹({3,5,7}) = {2,4,6}.",
                     EASY),
            practice("fun-imagem-inversa-p5", "fun-imagem-inversa",
                     "`f(C ∪ D)` é igual a:",
                     ["f(C) ∩ f(D)", "f(C) ∪ f(D)",
                      "f(C) − f(D)", "C ∪ D"], 1,
                     "A imagem direta preserva a união: f(C∪D) = f(C) ∪ f(D).",
                     MEDIUM),
            practice("fun-imagem-inversa-p6", "fun-imagem-inversa",
                     "Para `f(x) = x²`, `f({−1, 0, 1})` é:",
                     ["{−1, 0, 1}", "{1, 0, 1}", "{0, 1}", "{0, 1, 2}"], 2,
                     "f(−1)=1, f(0)=0, f(1)=1. O conjunto de imagens é {0, 1} (sem repetição).",
                     MEDIUM),
        ),
    ),
    # ─────────────────── Sequências e Somatório (topic 5) ───────────────────
    concept(
        id="seq-sequencias",
        title="Sequências (PA e PG)",
        unit=1,
        topic=5,
        prerequisites=("fun-definicao",),
        content="""## Intuição
Uma **sequência** é uma lista *ordenada* de elementos (formalmente, uma função dos naturais). A ordem importa e pode haver repetição. `{aₙ}` denota a sequência; `aₙ` é um termo.

## Definição formal
- **Progressão aritmética (PA):** `a, a+d, a+2d, …` — termo inicial `a`, diferença comum `d`. Termo geral `aₙ = a + nd`.
- **Progressão geométrica (PG):** `a, ar, ar², …` — termo inicial `a`, razão `r`. Termo geral `aₙ = a·rⁿ`.

## Exemplo resolvido
- `0, 2, 4, 6, …` é PA com `a = 0`, `d = 2`: `aₙ = 2n`.
- `1, −1, 1, −1, …` é PG com `a = 1`, `r = −1`: `aₙ = (−1)ⁿ`.
- `2, 10, 50, 250, …` é PG com `a = 2`, `r = 5`: `aₙ = 2·5ⁿ`.

## Erros comuns
- Confundir `{aₙ}` (a sequência toda) com `aₙ` (um termo).
- Trocar PA (soma constante `d`) com PG (razão constante `r`).""",
        questions=(
            graded("seq-sequencias-q1", "seq-sequencias",
                   "Uma progressão **geométrica** tem a forma:",
                   ["a, a+d, a+2d, …", "a, ar, ar², …",
                    "a, a², a³, …", "a, 2a, 3a, …"], 1,
                   "PG: cada termo é o anterior vezes a razão r: a, ar, ar², …",
                   EASY),
            graded("seq-sequencias-q2", "seq-sequencias",
                   "A sequência `0, 2, 4, 6, …` é uma PA com termo geral:",
                   ["aₙ = 2ⁿ", "aₙ = 2n", "aₙ = n²", "aₙ = n + 2"], 1,
                   "Diferença comum d = 2 e a = 0, logo aₙ = 0 + 2n = 2n.",
                   MEDIUM),
            graded("seq-sequencias-q3", "seq-sequencias",
                   "A sequência `1, −1, 1, −1, …` pode ser escrita como:",
                   ["aₙ = nⁿ", "aₙ = (−1)ⁿ", "aₙ = −n", "aₙ = 1/n"], 1,
                   "Alterna 1 e −1 conforme a paridade de n: aₙ = (−1)ⁿ (PG de razão −1).",
                   MEDIUM),
            graded("seq-sequencias-q4", "seq-sequencias",
                   "A sequência `3, 7, 11, 15, …` é uma PA com diferença `d` igual a:",
                   ["3", "4", "7", "2"], 1,
                   "7−3 = 4, 11−7 = 4, 15−11 = 4. Diferença constante d = 4.",
                   EASY),
            graded("seq-sequencias-q5", "seq-sequencias",
                   "O 5º termo (a₄, com n iniciando em 0) da PG `3, 6, 12, 24, …` é:",
                   ["48", "30", "96", "36"], 0,
                   "PG com a=3, r=2. a₄ = 3·2⁴ = 3·16 = 48.",
                   MEDIUM),
            graded("seq-sequencias-q6", "seq-sequencias",
                   "Uma sequência difere de um conjunto porque:",
                   ["não tem elementos", "a ordem importa e pode haver repetição",
                    "não pode ser infinita", "é sempre finita"], 1,
                   "Em uma sequência a ordem importa e repetições são permitidas. Em um conjunto, não.",
                   EASY),
            graded("seq-sequencias-q7", "seq-sequencias",
                   "Qual das seguintes NÃO é uma PG?",
                   ["1, 2, 4, 8, …", "3, 9, 27, 81, …",
                    "1, 3, 5, 7, …", "5, −5, 5, −5, …"], 2,
                   "1, 3, 5, 7 é PA (d=2), não PG. As demais têm razão constante (2, 3 e −1, respectivamente).",
                   MEDIUM),
        ),
        practice=(
            practice("seq-sequencias-p1", "seq-sequencias",
                     "Em `{aₙ}`, a notação `aₙ` representa:",
                     ["a sequência inteira", "um termo da sequência",
                      "a soma dos termos", "a razão"], 1,
                     "{aₙ} é a sequência; aₙ é o n-ésimo termo.",
                     EASY),
            practice("seq-sequencias-p2", "seq-sequencias",
                     "`2, 10, 50, 250, …` é PG de razão:",
                     ["2", "5", "8", "10"], 1,
                     "Cada termo é 5× o anterior: razão r = 5 (aₙ = 2·5ⁿ).",
                     MEDIUM),
            practice("seq-sequencias-p3", "seq-sequencias",
                     "A diferença entre PA e PG é que na PA somamos uma constante e na PG:",
                     ["subtraímos uma constante", "multiplicamos por uma razão constante",
                      "elevamos ao quadrado", "nada muda"], 1,
                     "PA: termo seguinte = anterior + d. PG: termo seguinte = anterior × r.",
                     EASY),
            practice("seq-sequencias-p4", "seq-sequencias",
                     "O termo geral da PA `5, 8, 11, 14, …` é:",
                     ["aₙ = 5 + 3n", "aₙ = 3 + 5n",
                      "aₙ = 5·3ⁿ", "aₙ = 5n"], 0,
                     "Termo inicial a=5, d=3. Termo geral: aₙ = 5 + 3n (com n começando em 0).",
                     MEDIUM),
            practice("seq-sequencias-p5", "seq-sequencias",
                     "A razão de uma PG é obtida por:",
                     ["aₙ₊₁ − aₙ", "aₙ₊₁ / aₙ",
                      "aₙ · aₙ₊₁", "aₙ₊₁ + aₙ"], 1,
                     "Na PG, r = aₙ₊₁/aₙ (razão entre termos consecutivos).",
                     EASY),
            practice("seq-sequencias-p6", "seq-sequencias",
                     "A sequência `1, 1/2, 1/4, 1/8, …` é PG de razão:",
                     ["2", "1/2", "−1/2", "1/4"], 1,
                     "Cada termo é metade do anterior: r = (1/2)/(1) = 1/2.",
                     MEDIUM),
        ),
    ),
    concept(
        id="seq-recorrencia",
        title="Relações de recorrência",
        unit=1,
        topic=5,
        prerequisites=("seq-sequencias", "inducao"),
        content="""## Intuição
Uma **relação de recorrência** define um termo em função dos **anteriores**, junto com **condições iniciais**. É a forma recursiva de descrever uma sequência (a forma explícita dá o termo direto em função de `n`).

## Definição formal
Uma sequência satisfaz uma recorrência se cada termo (a partir de certo ponto) é dado por uma expressão dos anteriores; precisa de **condições iniciais** para ficar determinada.

## Exemplo resolvido
- `aₙ = aₙ₋₁ + 3`, `a₀ = 2`: dá `2, 5, 8, 11, …` (é uma PA de razão 3; forma explícita `aₙ = 2 + 3n`).
- **Fibonacci:** `f₀ = 0`, `f₁ = 1`, `fₙ = fₙ₋₁ + fₙ₋₂` (`n ≥ 2`): `0,1,1,2,3,5,8,…`.
- `aₙ = n·aₙ₋₁`, `a₀ = 1`: dá o **fatorial** `aₙ = n!`.

Para `{5,7,9,11,…}`: forma recursiva `a₁ = 5, aₙ = aₙ₋₁ + 2`; explícita `aₙ = 2n + 3`.

## Erros comuns
- Esquecer as **condições iniciais** (sem elas a recorrência não determina a sequência).
- Confundir forma **recursiva** (usa anteriores) com **explícita** (usa só `n`).""",
        questions=(
            graded("seq-recorrencia-q1", "seq-recorrencia",
                   "Para a recorrência ficar determinada, além da regra é preciso:",
                   ["uma forma explícita", "condições iniciais",
                    "que seja uma PG", "que seja injetora"], 1,
                   "Sem condições iniciais (ex.: a₀), a mesma regra gera infinitas sequências diferentes.",
                   EASY),
            graded("seq-recorrencia-q2", "seq-recorrencia",
                   "A sequência de Fibonacci é definida por `f₀=0, f₁=1` e:",
                   ["fₙ = fₙ₋₁ · fₙ₋₂", "fₙ = fₙ₋₁ + fₙ₋₂",
                    "fₙ = 2fₙ₋₁", "fₙ = n!"], 1,
                   "Cada termo é a soma dos dois anteriores: fₙ = fₙ₋₁ + fₙ₋₂.",
                   EASY),
            graded("seq-recorrencia-q3", "seq-recorrencia",
                   "A recorrência `aₙ = n·aₙ₋₁`, `a₀ = 1`, gera:",
                   ["a sequência 2ⁿ", "o fatorial n!",
                    "Fibonacci", "a PA de razão n"], 1,
                   "a₀=1, a₁=1, a₂=2, a₃=6, … = n!.",
                   MEDIUM),
            graded("seq-recorrencia-q4", "seq-recorrencia",
                   "Com `a₀ = 1` e `aₙ = 2aₙ₋₁`, a forma explícita é:",
                   ["aₙ = 2n", "aₙ = 2ⁿ", "aₙ = n²", "aₙ = n + 1"], 1,
                   "a₀=1, a₁=2, a₂=4, a₃=8, … Cada termo dobra: aₙ = 2ⁿ.",
                   MEDIUM),
            graded("seq-recorrencia-q5", "seq-recorrencia",
                   "O 6º termo de Fibonacci (f₆) é:",
                   ["5", "8", "13", "21"], 1,
                   "f₀=0, f₁=1, f₂=1, f₃=2, f₄=3, f₅=5, f₆=8.",
                   MEDIUM),
            graded("seq-recorrencia-q6", "seq-recorrencia",
                   "A recorrência `aₙ = aₙ₋₁ + aₙ₋₂` precisa de quantas condições iniciais?",
                   ["0", "1", "2", "3"], 2,
                   "Cada termo depende dos dois anteriores, logo precisamos de a₀ e a₁ (2 condições).",
                   EASY),
            graded("seq-recorrencia-q7", "seq-recorrencia",
                   "Se `aₙ = 3aₙ₋₁ − 2`, `a₀ = 4`, então `a₂` vale:",
                   ["10", "28", "8", "22"], 1,
                   "a₁ = 3·4 − 2 = 10; a₂ = 3·10 − 2 = 28.",
                   HARD),
        ),
        practice=(
            practice("seq-recorrencia-p1", "seq-recorrencia",
                     "A forma recursiva de `{5,7,9,11,…}` é:",
                     ["aₙ = 2n+3", "a₁=5, aₙ = aₙ₋₁ + 2",
                      "aₙ = 5ⁿ", "a₁=5, aₙ = 5aₙ₋₁"], 1,
                     "Recursiva usa o termo anterior: a₁=5 e soma 2 a cada passo. (2n+3 é a forma explícita.)",
                     MEDIUM),
            practice("seq-recorrencia-p2", "seq-recorrencia",
                     "Com `a₁ = 2` e `aₙ = 2aₙ₋₁ − 1`, o terceiro termo `a₃` é:",
                     ["3", "5", "7", "9"], 1,
                     "a₂ = 2·2 − 1 = 3; a₃ = 2·3 − 1 = 5.",
                     MEDIUM),
            practice("seq-recorrencia-p3", "seq-recorrencia",
                     "A forma **explícita** de uma sequência dá o termo em função de:",
                     ["termos anteriores", "n diretamente",
                      "condições iniciais só", "uma razão"], 1,
                     "Explícita: aₙ depende só de n (ex.: aₙ = 2n+3), sem precisar dos anteriores.",
                     EASY),
            practice("seq-recorrencia-p4", "seq-recorrencia",
                     "Com `a₁ = 3` e `aₙ = aₙ₋₁ + 5`, qual é `a₄`?",
                     ["18", "23", "13", "15"], 0,
                     "a₂ = 8, a₃ = 13, a₄ = 18. PA com d=5, a partir de 3.",
                     EASY),
            practice("seq-recorrencia-p5", "seq-recorrencia",
                     "A recorrência que gera `1, 2, 4, 8, 16, …` é:",
                     ["aₙ = aₙ₋₁ + 2, a₀ = 1", "aₙ = 2aₙ₋₁, a₀ = 1",
                      "aₙ = aₙ₋₁², a₀ = 1", "aₙ = aₙ₋₁ + aₙ₋₂"], 1,
                     "Cada termo é o dobro do anterior: 2·1=2, 2·2=4, … Recorrência: aₙ = 2aₙ₋₁ com a₀ = 1.",
                     MEDIUM),
            practice("seq-recorrencia-p6", "seq-recorrencia",
                     "Duas recorrências com a mesma regra mas condições iniciais diferentes geram:",
                     ["a mesma sequência", "sequências diferentes",
                      "erro", "sequências iguais a partir de n=2"], 1,
                     "As condições iniciais determinam a sequência. Mesma regra com valores iniciais distintos produz sequências distintas.",
                     MEDIUM),
        ),
    ),
    concept(
        id="seq-somatorio",
        title="Somatório",
        unit=1,
        topic=5,
        prerequisites=("seq-sequencias",),
        content="""## Intuição
O **somatório** `Σ` é uma notação compacta para somar termos de uma sequência. `Σ_{i=1}^{n} aᵢ = a₁ + a₂ + … + aₙ`.

## Definição formal
`Σ_{i=m}^{n} aᵢ = aₘ + aₘ₊₁ + … + aₙ` (índice `i`, limites `m` a `n`). Fórmulas fechadas úteis:
- `Σ_{i=1}^{n} i = n(n+1)/2`
- `Σ_{i=1}^{n} i² = n(n+1)(2n+1)/6`
- **PG:** `Σ_{i=0}^{n} arⁱ = a(rⁿ⁺¹ − 1)/(r − 1)` (`r ≠ 1`).
- Linearidade: `Σ(c·aᵢ + bᵢ) = c·Σaᵢ + Σbᵢ`.

## Exemplo resolvido
`Σ_{i=1}^{100} i = 100·101/2 = 5050` (a famosa soma de Gauss).
`Σ_{i=0}^{n} 2ⁱ = 2ⁿ⁺¹ − 1` (PG de razão 2).

## Erros comuns
- Errar os limites (quantos termos: de `m` a `n` são `n − m + 1` termos).
- Aplicar a fórmula de PG com `r = 1` (aí a soma é `(n+1)a`).""",
        questions=(
            graded("seq-somatorio-q1", "seq-somatorio",
                   "`Σ_{i=1}^{n} i` é igual a:",
                   ["n²", "n(n+1)/2", "n(n+1)(2n+1)/6", "2ⁿ − 1"], 1,
                   "Soma dos n primeiros naturais: n(n+1)/2 (soma de Gauss).",
                   EASY),
            graded("seq-somatorio-q2", "seq-somatorio",
                   "`Σ_{i=1}^{100} i` vale:",
                   ["10000", "5050", "5000", "10100"], 1,
                   "100·101/2 = 5050.",
                   MEDIUM),
            graded("seq-somatorio-q3", "seq-somatorio",
                   "`Σ_{i=0}^{n} 2ⁱ` é igual a:",
                   ["2ⁿ", "2ⁿ⁺¹ − 1", "n²", "2n"], 1,
                   "Soma de PG de razão 2 a partir de 1: 1+2+4+…+2ⁿ = 2ⁿ⁺¹ − 1.",
                   MEDIUM),
            graded("seq-somatorio-q4", "seq-somatorio",
                   "`Σ_{i=1}^{4} i²` vale:",
                   ["10", "30", "20", "14"], 1,
                   "1² + 2² + 3² + 4² = 1 + 4 + 9 + 16 = 30. Verificação: 4·5·9/6 = 30.",
                   MEDIUM),
            graded("seq-somatorio-q5", "seq-somatorio",
                   "A soma `Σ_{i=0}^{3} 3ⁱ` vale:",
                   ["40", "27", "13", "9"], 0,
                   "3⁰ + 3¹ + 3² + 3³ = 1 + 3 + 9 + 27 = 40. Fórmula: (3⁴−1)/(3−1) = 80/2 = 40.",
                   MEDIUM),
            graded("seq-somatorio-q6", "seq-somatorio",
                   "A propriedade `Σ(aᵢ + bᵢ) = Σaᵢ + Σbᵢ` chama-se:",
                   ["comutatividade", "associatividade",
                    "linearidade do somatório", "distributividade"], 2,
                   "A linearidade permite separar somas e fatorar constantes: Σ(caᵢ+bᵢ) = cΣaᵢ + Σbᵢ.",
                   EASY),
            graded("seq-somatorio-q7", "seq-somatorio",
                   "A fórmula de PG `Σ_{i=0}^{n} arⁱ = a(rⁿ⁺¹−1)/(r−1)` não se aplica quando:",
                   ["r > 1", "r < 0", "r = 1", "a = 0"], 2,
                   "Com r=1 temos divisão por zero. Nesse caso a soma é simplesmente (n+1)·a.",
                   HARD),
        ),
        practice=(
            practice("seq-somatorio-p1", "seq-somatorio",
                     "Quantos termos há em `Σ_{i=3}^{7} aᵢ`?",
                     ["4", "5", "7", "3"], 1,
                     "De 3 a 7 são 7 − 3 + 1 = 5 termos.",
                     MEDIUM),
            practice("seq-somatorio-p2", "seq-somatorio",
                     "`Σ_{i=1}^{n} i²` é igual a:",
                     ["n(n+1)/2", "n(n+1)(2n+1)/6", "n³", "(n(n+1)/2)²"], 1,
                     "Soma dos quadrados: n(n+1)(2n+1)/6.",
                     MEDIUM),
            practice("seq-somatorio-p3", "seq-somatorio",
                     "Pela linearidade, `Σ (3aᵢ)` é igual a:",
                     ["3 + Σaᵢ", "3·Σaᵢ", "Σaᵢ", "(Σaᵢ)³"], 1,
                     "Constantes saem do somatório: Σ(3aᵢ) = 3 Σaᵢ.",
                     EASY),
            practice("seq-somatorio-p4", "seq-somatorio",
                     "`Σ_{i=1}^{10} 1` vale:",
                     ["1", "10", "0", "100"], 1,
                     "Somar a constante 1 dez vezes: 1+1+…+1 = 10.",
                     EASY),
            practice("seq-somatorio-p5", "seq-somatorio",
                     "`Σ_{i=1}^{5} (2i − 1)` vale:",
                     ["15", "25", "20", "30"], 1,
                     "São os ímpares 1+3+5+7+9 = 25. Equivale a 5² = 25.",
                     MEDIUM),
            practice("seq-somatorio-p6", "seq-somatorio",
                     "`Σ_{i=0}^{n} arⁱ` com `r = 1` é igual a:",
                     ["a(n+1)", "a·rⁿ", "aⁿ⁺¹", "0"], 0,
                     "Com r = 1, cada termo vale a: a+a+…+a = a(n+1).",
                     MEDIUM),
        ),
    ),
    # ───────────────────────── Cardinalidade (topic 6) ─────────────────────────
    concept(
        id="card-cardinalidade",
        title="Cardinalidade: finito, infinito e enumerável",
        unit=1,
        topic=6,
        prerequisites=("fun-sobre-bij",),
        content="""## Intuição
Dois conjuntos têm a **mesma cardinalidade** quando existe uma **bijeção** entre eles (`A ∼ B`). Isso funciona mesmo para infinitos — e revela surpresas, como `ℕ` ter o mesmo "tamanho" que o conjunto dos pares.

## Definição formal
- `A ∼ B` (mesma cardinalidade) sse existe `f: A → B` bijetora; escreve-se `|A| = |B|`. A relação `∼` é reflexiva, simétrica e transitiva.
- `A` é **finito** se `A ∼ Iₙ` para algum `n`, onde `Iₙ = {0,1,…,n−1}`.
- `A` é **infinito** se `A ∼ B` para algum `B ⊊ A` (subconjunto próprio).
- **Enumerável:** mesma cardinalidade de `ℕ`. **Contável:** finito ou enumerável.

## Exemplo resolvido
`f: ℕ → P` (pares), `f(n) = 2n`, é bijeção: logo `ℕ ∼ P`, apesar de `P ⊊ ℕ`! (Hotel de Hilbert: um hotel lotado com infinitos quartos ainda acomoda novos hóspedes.)

## Erros comuns
- Achar que todo infinito tem o mesmo tamanho que `ℕ` (há infinitos "maiores", como `ℝ`).
- Supor que um subconjunto próprio sempre tem cardinalidade menor (falso no infinito).""",
        questions=(
            graded("card-cardinalidade-q1", "card-cardinalidade",
                   "Dois conjuntos têm a mesma cardinalidade quando existe entre eles:",
                   ["uma injeção qualquer", "uma bijeção",
                    "uma relação reflexiva", "uma função qualquer"], 1,
                   "|A| = |B| sse existe bijeção f: A → B.",
                   EASY),
            graded("card-cardinalidade-q2", "card-cardinalidade",
                   "Um conjunto é **enumerável** quando tem a mesma cardinalidade de:",
                   ["ℝ", "ℕ", "∅", "P(ℕ)"], 1,
                   "Enumerável = em bijeção com ℕ (seus elementos podem ser listados a₀, a₁, a₂, …).",
                   MEDIUM),
            graded("card-cardinalidade-q3", "card-cardinalidade",
                   "A função `f(n) = 2n` de ℕ nos pares mostra que:",
                   ["os pares são mais que ℕ",
                    "ℕ tem a mesma cardinalidade do conjunto dos pares",
                    "ℕ é finito",
                    "os pares são incontáveis"], 1,
                   "É uma bijeção ℕ → pares, então têm a mesma cardinalidade — um conjunto infinito pode ter subconjunto próprio de mesmo tamanho.",
                   HARD),
            graded("card-cardinalidade-q4", "card-cardinalidade",
                   "O conjunto `ℤ` dos inteiros é:",
                   ["incontável", "enumerável",
                    "finito", "do tamanho de ℝ"], 1,
                   "A bijeção f(0)=0, f(1)=1, f(2)=−1, f(3)=2, f(4)=−2, … mostra ℤ ∼ ℕ, logo ℤ é enumerável.",
                   MEDIUM),
            graded("card-cardinalidade-q5", "card-cardinalidade",
                   "Pelo argumento diagonal de Cantor, `ℝ` é:",
                   ["enumerável", "finito",
                    "incontável (|ℝ| > |ℕ|)", "equipotente a ℕ"], 2,
                   "Cantor mostrou que qualquer listagem de reais em (0,1) pode ser 'diagonalizada' para produzir um real fora da lista, logo ℝ não é enumerável.",
                   HARD),
            graded("card-cardinalidade-q6", "card-cardinalidade",
                   "Se `A ⊆ B` e `B` é contável, então `A` é:",
                   ["incontável", "contável",
                    "necessariamente infinito", "vazio"], 1,
                   "Subconjunto de contável é contável: se B é finito ou enumerável, A também é (herda a bijeção restrita).",
                   EASY),
            graded("card-cardinalidade-q7", "card-cardinalidade",
                   "`ℚ` (racionais) é enumerável. Qual técnica prova isso?",
                   ["diagonal de Cantor",
                    "argumento diagonal invertido",
                    "enumeração em zigue-zague (Cantor)",
                    "Hotel de Hilbert"], 2,
                   "Cantor listou os racionais percorrendo a tabela p/q em zigue-zague, pulando repetidos, mostrando ℚ ∼ ℕ.",
                   HARD),
        ),
        practice=(
            practice("card-cardinalidade-p1", "card-cardinalidade",
                     "Um conjunto **contável** é:",
                     ["sempre finito", "finito ou enumerável",
                      "sempre infinito", "do tamanho de ℝ"], 1,
                     "Contável = finito OU enumerável (em bijeção com ℕ).",
                     MEDIUM),
            practice("card-cardinalidade-p2", "card-cardinalidade",
                     "Um conjunto é **infinito** (def. do curso) quando:",
                     ["tem mais de 100 elementos",
                      "é equipotente a um subconjunto próprio dele mesmo",
                      "tem cardinalidade 0",
                      "é igual a ℕ"], 1,
                     "Definição: A é infinito se A ∼ B para algum B ⊊ A.",
                     HARD),
            practice("card-cardinalidade-p3", "card-cardinalidade",
                     "A anedota do Hotel de Hilbert ilustra que:",
                     ["hotéis são finitos",
                      "é possível acomodar novos hóspedes mesmo 'lotado' (infinito)",
                      "ℝ é enumerável",
                      "ℕ é finito"], 1,
                     "Com infinitos quartos, remanejar hóspedes abre vagas — propriedade dos conjuntos infinitos.",
                     MEDIUM),
            practice("card-cardinalidade-p4", "card-cardinalidade",
                     "A união de dois conjuntos enumeráveis é:",
                     ["incontável", "enumerável",
                      "sempre finita", "indefinida"], 1,
                     "Se A ∼ ℕ e B ∼ ℕ, intercalamos as listagens a₀,b₀,a₁,b₁,… e A ∪ B ∼ ℕ.",
                     MEDIUM),
            practice("card-cardinalidade-p5", "card-cardinalidade",
                     "`|P(ℕ)| = |ℝ|` é uma consequência de qual resultado?",
                     ["PCP", "Teorema de Cantor (|P(A)| > |A|)",
                      "Hotel de Hilbert", "Indução"], 1,
                     "Cantor provou |P(A)| > |A| para todo A. Para ℕ, P(ℕ) tem a cardinalidade do contínuo, igual a |ℝ|.",
                     HARD),
            practice("card-cardinalidade-p6", "card-cardinalidade",
                     "A notação `A ∼ B` significa:",
                     ["A ⊆ B", "A e B são disjuntos",
                      "existe bijeção de A em B", "A = B"], 2,
                     "A ∼ B (equipotência) significa que existe uma bijeção f: A → B.",
                     EASY),
        ),
    ),
    concept(
        id="card-pcp",
        title="Princípio da Casa dos Pombos",
        unit=1,
        topic=6,
        prerequisites=("card-cardinalidade",),
        content="""## Intuição
O **Princípio da Casa dos Pombos (PCP)**: se há mais pombos do que casas, **alguma** casa terá mais de um pombo. Simples, mas poderosíssimo em provas de existência.

## Definição formal
- **PCP (forma básica):** se `n+1` objetos são colocados em `n` caixas, alguma caixa tem ≥ 2 objetos.
- **Forma geral:** se mais de `k·n` objetos vão em `n` caixas, alguma caixa tem mais de `k` objetos.
- Consequência (com `f: A → B` finitos): se `|A| > |B|`, `f` não é injetora; se `|A| < |B|`, `f` não é sobrejetora.

## Exemplo resolvido
Entre **13** pessoas, duas nascem no mesmo mês (12 "caixas" / meses, 13 "pombos").
**Prova típica:** dados `n+1` inteiros quaisquer, dois têm o mesmo resto na divisão por `n` (há só `n` restos possíveis), logo sua diferença é múltipla de `n`.

## Erros comuns
- Errar quem é "pombo" e quem é "casa".
- Esquecer que o PCP garante existência, **sem** dizer *quais* objetos colidem.""",
        questions=(
            graded("card-pcp-q1", "card-pcp",
                   "Pelo PCP, ao colocar `n+1` objetos em `n` caixas:",
                   ["toda caixa fica vazia",
                    "alguma caixa tem pelo menos 2 objetos",
                    "cada caixa tem exatamente 1",
                    "sobra uma caixa vazia"], 1,
                   "Com mais objetos que caixas, ao menos uma caixa recebe 2 ou mais.",
                   EASY),
            graded("card-pcp-q2", "card-pcp",
                   "Quantas pessoas garantem que duas nasceram no mesmo mês?",
                   ["12", "13", "24", "365"], 1,
                   "12 meses são as caixas; com 13 pessoas (pombos), duas caem no mesmo mês.",
                   MEDIUM),
            graded("card-pcp-q3", "card-pcp",
                   "Para `f: A → B` finitos, se `|A| > |B|` então `f`:",
                   ["é sobrejetora", "não é injetora",
                    "é bijetora", "não é função"], 1,
                   "Mais elementos no domínio que no contradomínio força colisão de imagens: f não pode ser injetora.",
                   MEDIUM),
            graded("card-pcp-q4", "card-pcp",
                   "Em uma turma de 367 alunos, pelo PCP:",
                   ["algum mês tem pelo menos 31 alunos",
                    "todos os meses têm aniversariantes",
                    "pelo menos dois aniversariam no mesmo dia do ano",
                    "nenhum mês fica sem aniversariante"], 2,
                   "366 dias no ano (pior caso com bissexto); 367 alunos > 366, logo pelo PCP dois compartilham o mesmo dia.",
                   MEDIUM),
            graded("card-pcp-q5", "card-pcp",
                   "Se 5 pontos são escolhidos dentro de um quadrado 2×2, pelo PCP dois deles distam no máximo:",
                   ["`2`", "`√2`", "`1`", "`√8`"], 1,
                   "Divida o quadrado em 4 subquadrados 1×1. Pelo PCP (5 pontos, 4 caixas), dois caem no mesmo subquadrado, cuja diagonal mede √2.",
                   HARD),
            graded("card-pcp-q6", "card-pcp",
                   "Com 25 objetos em 8 caixas, pela forma geral do PCP (k=3), alguma caixa tem:",
                   ["exatamente 3 objetos",
                    "mais de 3 objetos (pelo menos 4)",
                    "pelo menos 2 objetos",
                    "exatamente 8 objetos"], 1,
                   "25 > 3×8=24, então alguma caixa tem mais de 3, ou seja, ao menos 4 objetos.",
                   MEDIUM),
            graded("card-pcp-q7", "card-pcp",
                   "Se `|A| < |B|` e `f: A → B`, pelo PCP `f`:",
                   ["é injetora", "é bijetora",
                    "não é sobrejetora", "não é função"], 2,
                   "Se |A| < |B|, não há como cobrir todos os elementos de B com imagens vindas de A — faltam 'pombos' para todas as 'casas'.",
                   EASY),
        ),
        practice=(
            practice("card-pcp-p1", "card-pcp",
                     "Pela forma geral do PCP, com mais de `k·n` objetos em `n` caixas:",
                     ["alguma caixa tem mais de k objetos",
                      "todas têm k objetos",
                      "alguma fica vazia",
                      "nada se conclui"], 0,
                     "Generalização: se há mais de k·n objetos, alguma caixa supera k.",
                     MEDIUM),
            practice("card-pcp-p2", "card-pcp",
                     "Entre `n+1` inteiros, o PCP garante dois com:",
                     ["o mesmo valor",
                      "o mesmo resto na divisão por n (diferença múltipla de n)",
                      "soma par",
                      "produto ímpar"], 1,
                     "Há n restos possíveis mod n; com n+1 inteiros, dois compartilham resto, e sua diferença é múltipla de n.",
                     HARD),
            practice("card-pcp-p3", "card-pcp",
                     "O PCP é uma ferramenta típica de provas:",
                     ["construtivas (exibe o objeto)",
                      "de existência (garante sem exibir quais)",
                      "por indução",
                      "por contraexemplo"], 1,
                     "Ele afirma que existe colisão, mas não diz quais objetos colidem.",
                     MEDIUM),
            practice("card-pcp-p4", "card-pcp",
                     "Em um baralho de 52 cartas, quantas cartas garantem 2 do mesmo naipe?",
                     ["4", "5", "13", "14"], 1,
                     "4 naipes = caixas. Com 5 cartas (pombos), pelo PCP duas são do mesmo naipe.",
                     EASY),
            practice("card-pcp-p5", "card-pcp",
                     "Dados 10 inteiros entre 1 e 60, o PCP garante dois com diferença divisível por:",
                     ["2", "5", "9", "10"], 2,
                     "Os restos mod 9 são 0..8 (9 caixas). Com 10 inteiros, dois têm o mesmo resto mod 9, logo sua diferença é múltipla de 9.",
                     HARD),
            practice("card-pcp-p6", "card-pcp",
                     "O PCP pode determinar *quais* dois objetos colidem?",
                     ["Sim, sempre indica quais",
                      "Não — garante apenas a existência da colisão",
                      "Só quando n ≤ 10",
                      "Sim, pelo método construtivo"], 1,
                     "O PCP é um argumento de existência não-construtivo: garante que há colisão, mas não aponta quais elementos.",
                     EASY),
        ),
    ),
)
