"""Unidade 2 — Relações.

Baseado em Menezes (Relações, Endorrelações, Ordenação e Equivalência) e Rosen.
unit = 2. topics: 7 = Relações, 8 = Ordem e Equivalência.
"""
from __future__ import annotations

from app.seed.blocks._shared import EASY, HARD, MEDIUM, concept, graded, practice

UNIDADE_2 = (
    # ───────────────────────── Relações (topic 7) ─────────────────────────
    concept(
        id="rel-definicao",
        title="Relações e funções como caso particular",
        unit=2,
        topic=7,
        prerequisites=("conj-produto", "fun-definicao"),
        content="""## Intuição
Uma **relação** binária de `A` em `B` é simplesmente um conjunto de pares ordenados — um subconjunto de `A × B`. Toda **função é uma relação** (especial: total e funcional). Relações são mais gerais: podem deixar elementos sem par ou dar vários pares a um mesmo `a`.

## Definição formal
`R ⊆ A × B`. Escreve-se `a R b` para `(a,b) ∈ R`. Uma relação **n-ária** é `R ⊆ A₁ × … × Aₙ`. Uma relação sobre `A` (endorrelação) é `R ⊆ A × A`. A **identidade** é `ι_A = {(a,a) : a ∈ A}`.

## Exemplo resolvido
Em `A = {1,2,3}`, `R = {(1,1),(1,2),(2,3)}` é uma relação sobre `A`. Note que `1` se relaciona com `1` e com `2` (dois pares) — isso é permitido numa relação, mas **não** numa função.

## Erros comuns
- Achar que toda relação é função (função exige imagem única e total).
- Esquecer que `R` é um **conjunto** de pares (operações de conjunto se aplicam).""",
        questions=(
            graded("rel-definicao-q1", "rel-definicao",
                   "Uma relação binária de `A` em `B` é formalmente:",
                   ["um elemento de A × B", "um subconjunto de A × B",
                    "uma função de A em B", "o conjunto das partes de A"], 1,
                   "Relação = subconjunto de A × B (um conjunto de pares ordenados).",
                   EASY),
            graded("rel-definicao-q2", "rel-definicao",
                   "A afirmação correta sobre funções e relações é:",
                   ["toda relação é função",
                    "toda função é uma relação (total e funcional)",
                    "são conceitos sem relação",
                    "nenhuma função é relação"], 1,
                   "Função é um caso particular de relação: aquela que é total (todo a tem par) e funcional (par único).",
                   MEDIUM),
            graded("rel-definicao-q3", "rel-definicao",
                   "Por que `R = {(1,1),(1,2)}` sobre {1,2} **não** é função?",
                   ["porque é vazia",
                    "porque 1 se relaciona com dois elementos (imagem não única)",
                    "porque 2 não aparece",
                    "porque não é subconjunto de A×A"], 1,
                   "Função exige imagem única; aqui 1 ↦ 1 e 1 ↦ 2. Como relação, porém, é perfeitamente válida.",
                   MEDIUM),
            graded("rel-definicao-q4", "rel-definicao",
                   "Quantas relações binárias distintas existem de `A` em `B` quando `|A| = 2` e `|B| = 3`?",
                   ["6", "8", "64", "32"], 2,
                   "Uma relação é um subconjunto de A × B. Como |A × B| = 6, há 2⁶ = 64 subconjuntos possíveis.",
                   HARD),
            graded("rel-definicao-q5", "rel-definicao",
                   "Seja `A = {a, b}`. A relação `R = ∅` (vazia) sobre `A` é:",
                   ["inválida — toda relação precisa de pares",
                    "válida — o conjunto vazio é subconjunto de A × A",
                    "igual à identidade",
                    "igual a A × A"], 1,
                   "∅ ⊆ A × A, logo ∅ é uma relação sobre A (a relação vazia, onde nenhum par está relacionado).",
                   EASY),
            graded("rel-definicao-q6", "rel-definicao",
                   "Se `R ⊆ A × B` e `|R| = |A × B|`, então `R` é:",
                   ["a relação vazia", "a relação total (A × B)",
                    "a identidade", "necessariamente uma função"], 1,
                   "Se R tem todos os pares de A × B, então R = A × B, chamada de relação total ou completa.",
                   MEDIUM),
            graded("rel-definicao-q7", "rel-definicao",
                   "Uma relação binária `R ⊆ A × B` pode ser representada como:",
                   ["um número real", "um grafo bipartido ou uma matriz booleana",
                    "apenas uma lista de elementos", "um único par ordenado"], 1,
                   "Relações podem ser representadas por matrizes booleanas (M[i][j] = 1 se (aᵢ, bⱼ) ∈ R) ou grafos bipartidos.",
                   MEDIUM),
        ),
        practice=(
            practice("rel-definicao-p1", "rel-definicao",
                     "A relação identidade `ι_A` sobre A é:",
                     ["∅", "{(a,a) : a ∈ A}", "A × A", "{(a,b) : a ≠ b}"], 1,
                     "ι_A relaciona cada elemento consigo mesmo: {(a,a) : a ∈ A}.",
                     EASY),
            practice("rel-definicao-p2", "rel-definicao",
                     "Uma relação **n-ária** é um subconjunto de:",
                     ["A × A", "A₁ × A₂ × … × Aₙ", "P(A)", "A ∪ B"], 1,
                     "Generaliza pares para n-uplas: R ⊆ A₁ × … × Aₙ.",
                     MEDIUM),
            practice("rel-definicao-p3", "rel-definicao",
                     "Uma endorrelação (relação sobre um conjunto A) é subconjunto de:",
                     ["A × B", "A × A", "P(A)", "A − A"], 1,
                     "Endorrelação: relação de A em A, ou seja, R ⊆ A × A.",
                     EASY),
            practice("rel-definicao-p4", "rel-definicao",
                     "Se `A = {1, 2}`, quantos pares ordenados tem `A × A`?",
                     ["2", "4", "8", "1"], 1,
                     "|A × A| = |A|² = 2² = 4. Os pares são (1,1), (1,2), (2,1), (2,2).",
                     EASY),
            practice("rel-definicao-p5", "rel-definicao",
                     "A notação `a R b` significa:",
                     ["a pertence a B", "(a, b) ∈ R",
                      "a = b", "R é uma função"], 1,
                     "`a R b` é notação infixada para dizer que o par (a, b) pertence à relação R.",
                     EASY),
            practice("rel-definicao-p6", "rel-definicao",
                     "A relação `R = {(1,2), (3,4)}` de `{1,3}` em `{2,4,6}` é uma função?",
                     ["Não, pois não é subconjunto de A × B",
                      "Sim, é total e funcional",
                      "Não, pois 6 não é atingido",
                      "Não, pois não é injetiva"], 1,
                     "Todo elemento do domínio {1,3} tem exatamente uma imagem (1↦2, 3↦4), logo é total e funcional — é função. O fato de 6 não ser atingido torna-a não sobrejetiva, mas ainda é função.",
                     MEDIUM),
        ),
    ),
    concept(
        id="rel-tipos",
        title="Relações funcionais, injetivas, totais e sobrejetivas",
        unit=2,
        topic=7,
        prerequisites=("rel-definicao", "fun-sobre-bij"),
        content="""## Intuição
As propriedades que definem tipos de função se enunciam para relações em geral. Uma relação `R ⊆ A × B` pode ser **funcional**, **injetiva**, **total** e/ou **sobrejetiva**; uma função é uma relação **total e funcional**, e uma bijeção é total, funcional, injetiva e sobrejetiva.

## Definição formal
Para `R ⊆ A × B`:
- **Funcional:** cada `a` se relaciona com **no máximo um** `b` (`a R b ∧ a R b' → b = b'`).
- **Injetiva:** cada `b` é imagem de **no máximo um** `a`.
- **Total:** cada `a ∈ A` se relaciona com **algum** `b`.
- **Sobrejetiva:** cada `b ∈ B` é atingido por **algum** `a`.

## Exemplo resolvido
- Função = total + funcional.
- Função injetora = total + funcional + injetiva.
- Bijeção = total + funcional + injetiva + sobrejetiva.
`R = {(1,a),(2,a)}` em `{1,2}→{a,b}` é total e funcional (é função), mas **não** injetiva (`a` vem de `1` e `2`) nem sobrejetiva (`b` não é atingido).

## Erros comuns
- Misturar **funcional** (unicidade na saída) com **injetiva** (unicidade na entrada).
- Esquecer que "função" já embute total + funcional.""",
        questions=(
            graded("rel-tipos-q1", "rel-tipos",
                   "Uma relação é **funcional** quando cada elemento do domínio se relaciona com:",
                   ["pelo menos um b", "no máximo um b",
                    "exatamente dois b", "nenhum b"], 1,
                   "Funcional = imagem única (no máximo um b por a). Com 'total' adicionado, vira função.",
                   MEDIUM),
            graded("rel-tipos-q2", "rel-tipos",
                   "Uma **função** é uma relação que é:",
                   ["injetiva e sobrejetiva", "total e funcional",
                    "apenas funcional", "apenas total"], 1,
                   "Função = total (todo a tem imagem) + funcional (imagem única).",
                   MEDIUM),
            graded("rel-tipos-q3", "rel-tipos",
                   "Uma relação **injetiva** garante unicidade:",
                   ["na saída (cada a tem um b)",
                    "na entrada (cada b vem de no máximo um a)",
                    "de domínio",
                    "de contradomínio"], 1,
                   "Injetiva olha para o lado do contradomínio: cada b é atingido por no máximo um a.",
                   HARD),
            graded("rel-tipos-q4", "rel-tipos",
                   "`R = {(1,a),(2,b),(3,c)}` de `{1,2,3}` em `{a,b,c}` é:",
                   ["total, funcional, injetiva e sobrejetiva (bijeção)",
                    "total e funcional, mas não injetiva",
                    "apenas funcional",
                    "apenas injetiva"], 0,
                   "Todo elemento do domínio tem exatamente uma imagem (total + funcional), imagens distintas (injetiva) e todo elemento do contradomínio é atingido (sobrejetiva). Logo é bijeção.",
                   MEDIUM),
            graded("rel-tipos-q5", "rel-tipos",
                   "`R = {(1,a),(1,b)}` em `{1} → {a,b}` **não** é funcional porque:",
                   ["1 não tem imagem",
                    "1 se relaciona com dois elementos distintos",
                    "a e b são iguais",
                    "R é vazia"], 1,
                   "Funcional exige que cada elemento do domínio se relacione com no máximo um b. Aqui 1 tem dois pares: (1,a) e (1,b).",
                   EASY),
            graded("rel-tipos-q6", "rel-tipos",
                   "Uma relação **sobrejetiva** de `A` em `B` garante que:",
                   ["todo a ∈ A tem imagem",
                    "todo b ∈ B é atingido por algum a ∈ A",
                    "a relação é funcional",
                    "|A| = |B|"], 1,
                   "Sobrejetiva = para cada b ∈ B, existe pelo menos um a ∈ A com (a,b) ∈ R.",
                   MEDIUM),
            graded("rel-tipos-q7", "rel-tipos",
                   "Se `R ⊆ A × B` é total e funcional (função), mas `|A| > |B|`, então R:",
                   ["pode ser injetiva",
                    "não pode ser injetiva (pelo princípio da casa dos pombos)",
                    "é necessariamente sobrejetiva",
                    "é bijeção"], 1,
                   "Se |A| > |B| e R é total, pelo princípio da casa dos pombos, pelo menos dois elementos de A compartilham a mesma imagem — impossível ser injetiva.",
                   HARD),
        ),
        practice=(
            practice("rel-tipos-p1", "rel-tipos",
                     "Uma bijeção é uma relação:",
                     ["apenas funcional",
                      "total, funcional, injetiva e sobrejetiva",
                      "apenas injetiva",
                      "apenas total e sobrejetiva"], 1,
                     "Bijeção reúne as quatro propriedades.",
                     MEDIUM),
            practice("rel-tipos-p2", "rel-tipos",
                     "`R = {(1,a),(2,a)}` em {1,2}→{a,b} é:",
                     ["injetiva", "não injetiva (a vem de 1 e 2)",
                      "não funcional", "não total"], 1,
                     "a é imagem de dois elementos, logo não injetiva. É total e funcional (é função).",
                     MEDIUM),
            practice("rel-tipos-p3", "rel-tipos",
                     "Uma relação **total** exige que cada elemento do domínio:",
                     ["tenha no máximo um par", "se relacione com algum elemento",
                      "não se relacione", "seja único"], 1,
                     "Total = todo a do domínio tem pelo menos um par.",
                     EASY),
            practice("rel-tipos-p4", "rel-tipos",
                     "`R = {(1,a),(2,a),(3,b)}` de `{1,2,3}` em `{a,b}` é sobrejetiva?",
                     ["Não, pois a é atingido duas vezes",
                      "Sim, pois a e b são atingidos",
                      "Não, pois não é injetiva",
                      "Não, pois |A| ≠ |B|"], 1,
                     "Sobrejetiva exige que todo b ∈ B seja atingido. Aqui a é atingido por 1 e 2, e b por 3 — ambos atingidos, logo sobrejetiva.",
                     MEDIUM),
            practice("rel-tipos-p5", "rel-tipos",
                     "Uma relação pode ser injetiva sem ser funcional?",
                     ["Não, injetividade exige funcionalidade",
                      "Sim — injetividade fala apenas que cada b vem de no máximo um a",
                      "Só se for total",
                      "Só em conjuntos infinitos"], 1,
                     "Injetividade é uma propriedade independente: cada b é imagem de no máximo um a. A relação pode ter a's com múltiplas imagens (não funcional) e ainda ser injetiva.",
                     HARD),
            practice("rel-tipos-p6", "rel-tipos",
                     "A relação vazia `∅ ⊆ A × B` (com A e B não-vazios) é funcional?",
                     ["Não, pois não tem pares",
                      "Sim — nenhum a viola a unicidade de imagem (verdade por vacuidade)",
                      "Só se A for vazio",
                      "Depende de B"], 1,
                     "Funcional diz: se a R b e a R b', então b = b'. Sem pares, a condição é satisfeita vacuamente. Porém ∅ não é total (se A ≠ ∅), então não é função.",
                     HARD),
        ),
    ),
    concept(
        id="rel-composicao",
        title="Composição de relações",
        unit=2,
        topic=7,
        prerequisites=("rel-definicao",),
        content="""## Intuição
Compor relações é encadeá-las: `a (S ∘ R) c` se existe um intermediário `b` com `a R b` e `b S c`. Generaliza a composição de funções.

## Definição formal
Para `R ⊆ A × B` e `S ⊆ B × C`:
`S ∘ R = {(a, c) ∈ A × C : ∃b ∈ B, (a,b) ∈ R ∧ (b,c) ∈ S}`.
(Atenção à ordem: aplica-se `R` primeiro, depois `S` — como nas funções.)

## Exemplo resolvido
`R = {(1,2),(2,3)}`, `S = {(2,5),(3,7)}`.
`S ∘ R`: de `1`, via `2`, chega a `5`; de `2`, via `3`, chega a `7`. Logo `S ∘ R = {(1,5),(2,7)}`.

## Erros comuns
- Inverter a ordem da composição.
- Esquecer que precisa **existir** um intermediário `b` ligando os dois pares.""",
        questions=(
            graded("rel-composicao-q1", "rel-composicao",
                   "`(a, c) ∈ S ∘ R` quando:",
                   ["a S b e b R c para algum b",
                    "existe b com a R b e b S c",
                    "a R c diretamente",
                    "a = c"], 1,
                   "Composição: existe intermediário b com (a,b) ∈ R e (b,c) ∈ S.",
                   MEDIUM),
            graded("rel-composicao-q2", "rel-composicao",
                   "Com `R = {(1,2),(2,3)}` e `S = {(2,5),(3,7)}`, `S ∘ R` é:",
                   ["{(1,5),(2,7)}", "{(1,2),(2,3)}",
                    "{(2,5),(3,7)}", "{(1,7),(2,5)}"], 0,
                   "1→2→5 e 2→3→7, então S∘R = {(1,5),(2,7)}.",
                   MEDIUM),
            graded("rel-composicao-q3", "rel-composicao",
                   "A composição de relações generaliza:",
                   ["a união de conjuntos", "a composição de funções",
                    "o produto cartesiano", "o complemento"], 1,
                   "Como funções são relações, S ∘ R estende a ideia de (g ∘ f)(x) = g(f(x)).",
                   EASY),
            graded("rel-composicao-q4", "rel-composicao",
                   "Com `R = {(a,1),(b,2)}` e `S = {(1,x),(2,x)}`, `S ∘ R` é:",
                   ["{(a,x),(b,x)}", "{(1,a),(2,b)}",
                    "{(a,1),(b,2),(1,x),(2,x)}", "∅"], 0,
                   "a→1→x e b→2→x, logo S∘R = {(a,x),(b,x)}.",
                   MEDIUM),
            graded("rel-composicao-q5", "rel-composicao",
                   "A composição de relações é **associativa**: `(T ∘ S) ∘ R =`",
                   ["T ∘ (R ∘ S)", "T ∘ (S ∘ R)",
                    "(R ∘ S) ∘ T", "R ∘ S ∘ T (indefinido)"], 1,
                   "A composição de relações é associativa: (T ∘ S) ∘ R = T ∘ (S ∘ R). A ordem das relações é mantida.",
                   HARD),
            graded("rel-composicao-q6", "rel-composicao",
                   "Se `R = {(1,2),(2,1)}` sobre `{1,2}`, `R ∘ R` é:",
                   ["{(1,1),(2,2)}", "{(1,2),(2,1)}",
                    "∅", "{(1,2)}"], 0,
                   "1→2→1 dá (1,1); 2→1→2 dá (2,2). Logo R∘R = {(1,1),(2,2)} = ι_A.",
                   MEDIUM),
            graded("rel-composicao-q7", "rel-composicao",
                   "A composição de relações é comutativa (S ∘ R = R ∘ S)?",
                   ["Sim, sempre", "Não, em geral S ∘ R ≠ R ∘ S",
                    "Sim, se R e S são não-vazias", "Sim, se forem sobre o mesmo conjunto"], 1,
                   "A composição de relações NÃO é comutativa em geral. Exemplo: R = {(1,2)}, S = {(2,3)}; S∘R = {(1,3)}, mas R∘S = ∅.",
                   HARD),
        ),
        practice=(
            practice("rel-composicao-p1", "rel-composicao",
                     "Em `S ∘ R`, aplica-se primeiro:",
                     ["S", "R", "as duas juntas", "a identidade"], 1,
                     "A ordem segue as funções: R primeiro, depois S.",
                     EASY),
            practice("rel-composicao-p2", "rel-composicao",
                     "Se não há intermediário ligando R e S, então `S ∘ R` é:",
                     ["A × C", "∅ (vazia para esses pares)",
                      "R ∪ S", "a identidade"], 1,
                     "Sem b conectando, não se forma par (a,c); a composição é vazia.",
                     MEDIUM),
            practice("rel-composicao-p3", "rel-composicao",
                     "Compor `R ⊆ A×B` com `ι_B` (identidade em B) dá:",
                     ["∅", "R", "B × B", "ι_A"], 1,
                     "ι_B ∘ R = R: compor com a identidade não muda a relação.",
                     HARD),
            practice("rel-composicao-p4", "rel-composicao",
                     "Se `R = {(1,2)}` e `S = {(3,4)}`, qual é `S ∘ R`?",
                     ["{(1,4)}", "{(1,2),(3,4)}",
                      "∅", "{(2,3)}"], 2,
                     "Para existir (a,c) em S∘R, é preciso b com (a,b) ∈ R e (b,c) ∈ S. O único b de R é 2, mas S não tem par começando em 2. Logo S∘R = ∅.",
                     MEDIUM),
            practice("rel-composicao-p5", "rel-composicao",
                     "`R²` (R composta consigo mesma) para `R = {(1,2),(2,3),(3,1)}` contém o par:",
                     ["(1,1)", "(1,3)", "(3,3)", "(2,1)"], 1,
                     "R² = R∘R: 1→2→3, logo (1,3) ∈ R². Verificando: 2→3→1 dá (2,1); 3→1→2 dá (3,2).",
                     HARD),
            practice("rel-composicao-p6", "rel-composicao",
                     "Se `R` e `S` são funções, `S ∘ R` também é função?",
                     ["Não necessariamente", "Sim, a composição de funções é função",
                      "Só se forem bijeções", "Nunca"], 1,
                     "Se R é total e funcional, e S é total e funcional, então S∘R também é total e funcional — portanto é função.",
                     MEDIUM),
        ),
    ),
    concept(
        id="rel-inversa",
        title="Relação inversa",
        unit=2,
        topic=7,
        prerequisites=("rel-definicao",),
        content="""## Intuição
A **inversa** de uma relação troca a ordem de cada par: o que ia de `a` para `b` passa a ir de `b` para `a`. Toda relação tem inversa (diferente de funções, onde a inversa só é função se houver bijeção).

## Definição formal
Para `R ⊆ A × B`, `R⁻¹ = {(b, a) : (a, b) ∈ R} ⊆ B × A`.
Propriedades: `(R⁻¹)⁻¹ = R`; `(S ∘ R)⁻¹ = R⁻¹ ∘ S⁻¹`.

## Exemplo resolvido
`R = {(1,a),(2,b),(2,c)}` ⟹ `R⁻¹ = {(a,1),(b,2),(c,2)}`.
Note que `R⁻¹` pode não ser funcional mesmo que `R` seja.

## Erros comuns
- Confundir relação inversa (sempre existe) com função inversa (só para bijeções).
- Errar a ordem em `(S ∘ R)⁻¹ = R⁻¹ ∘ S⁻¹`.""",
        questions=(
            graded("rel-inversa-q1", "rel-inversa",
                   "A inversa de `R ⊆ A × B` é:",
                   ["{(a,b) : (a,b) ∈ R}", "{(b,a) : (a,b) ∈ R}",
                    "{(a,a) : a ∈ A}", "A × B"], 1,
                   "R⁻¹ inverte cada par: (a,b) vira (b,a).",
                   EASY),
            graded("rel-inversa-q2", "rel-inversa",
                   "`(R⁻¹)⁻¹` é igual a:",
                   ["∅", "R", "R × R", "ι_A"], 1,
                   "Inverter duas vezes devolve a relação original: (R⁻¹)⁻¹ = R.",
                   MEDIUM),
            graded("rel-inversa-q3", "rel-inversa",
                   "`(S ∘ R)⁻¹` é igual a:",
                   ["S⁻¹ ∘ R⁻¹", "R⁻¹ ∘ S⁻¹", "R ∘ S", "(R ∘ S)⁻¹"], 1,
                   "A inversa da composição inverte a ordem: (S∘R)⁻¹ = R⁻¹ ∘ S⁻¹.",
                   HARD),
            graded("rel-inversa-q4", "rel-inversa",
                   "Se `R ⊆ A × B`, então `R⁻¹` é subconjunto de:",
                   ["A × B", "B × A", "A × A", "B × B"], 1,
                   "R⁻¹ troca a ordem dos pares: de (a,b) para (b,a). Logo R⁻¹ ⊆ B × A.",
                   EASY),
            graded("rel-inversa-q5", "rel-inversa",
                   "Se `R` é uma função bijetora, então `R⁻¹`:",
                   ["não existe", "é uma relação mas não uma função",
                    "também é uma função bijetora", "é a identidade"], 2,
                   "Para bijeções, a inversa é total e funcional (cada b tem exatamente um a). Também é injetiva e sobrejetiva — logo bijeção.",
                   MEDIUM),
            graded("rel-inversa-q6", "rel-inversa",
                   "A inversa de `ι_A` (identidade sobre A) é:",
                   ["∅", "A × A", "ι_A (ela mesma)", "A − ι_A"], 2,
                   "ι_A = {(a,a) : a ∈ A}. Invertendo cada par: (a,a) → (a,a). Logo ι_A⁻¹ = ι_A.",
                   EASY),
            graded("rel-inversa-q7", "rel-inversa",
                   "Se `R = {(1,2),(2,3),(3,2)}`, então `R⁻¹` é:",
                   ["{(2,1),(3,2),(2,3)}", "{(1,2),(2,3),(3,2)}",
                    "{(2,1),(2,3),(3,2)}", "{(2,1),(3,2)}"], 0,
                   "Invertendo cada par: (1,2)→(2,1), (2,3)→(3,2), (3,2)→(2,3). Logo R⁻¹ = {(2,1),(3,2),(2,3)}.",
                   MEDIUM),
        ),
        practice=(
            practice("rel-inversa-p1", "rel-inversa",
                     "`R = {(1,a),(2,b)}` tem inversa:",
                     ["{(1,a),(2,b)}", "{(a,1),(b,2)}",
                      "{(a,b),(1,2)}", "∅"], 1,
                     "Trocando a ordem de cada par: {(a,1),(b,2)}.",
                     EASY),
            practice("rel-inversa-p2", "rel-inversa",
                     "Toda relação tem inversa?",
                     ["Não, só funções", "Sim, sempre",
                      "Só bijeções", "Só relações de equivalência"], 1,
                     "A inversa de uma relação sempre existe (basta trocar a ordem dos pares).",
                     MEDIUM),
            practice("rel-inversa-p3", "rel-inversa",
                     "A inversa de uma relação funcional:",
                     ["é sempre funcional", "pode não ser funcional",
                      "é sempre vazia", "é sempre total"], 1,
                     "Se dois a's tinham a mesma imagem, a inversa relaciona essa imagem a dois elementos — não funcional.",
                     MEDIUM),
            practice("rel-inversa-p4", "rel-inversa",
                     "Se `R` é simétrica (R ⊆ A × A), então `R⁻¹` é:",
                     ["∅", "ι_A", "igual a R", "o complemento de R"], 2,
                     "Se R é simétrica, (a,b) ∈ R implica (b,a) ∈ R. Logo R⁻¹ = R.",
                     MEDIUM),
            practice("rel-inversa-p5", "rel-inversa",
                     "`|R⁻¹|` comparado com `|R|` é:",
                     ["sempre maior", "sempre menor",
                      "sempre igual", "pode ser maior ou menor"], 2,
                     "A inversa apenas troca a ordem dos pares, sem adicionar ou remover nenhum. Logo |R⁻¹| = |R|.",
                     EASY),
            practice("rel-inversa-p6", "rel-inversa",
                     "Se `R` é injetiva, `R⁻¹` é:",
                     ["injetiva", "funcional",
                      "total", "sobrejetiva"], 1,
                     "R injetiva: cada b é imagem de no máximo um a. Na inversa, cada 'a' (agora na saída) aparece no máximo uma vez — isso é exatamente a definição de funcional.",
                     HARD),
        ),
    ),
    concept(
        id="rel-propriedades",
        title="Propriedades: reflexiva, simétrica, transitiva, antissimétrica",
        unit=2,
        topic=7,
        prerequisites=("rel-definicao",),
        content="""## Intuição
Endorrelações (`R ⊆ A × A`) são classificadas por propriedades. Estas quatro são a base de **ordens** e **equivalências**.

## Definição formal
Para `R ⊆ A × A`:
- **Reflexiva:** `∀a, (a,a) ∈ R`.
- **Simétrica:** `(a,b) ∈ R → (b,a) ∈ R`.
- **Antissimétrica:** `(a,b) ∈ R ∧ (b,a) ∈ R → a = b`.
- **Transitiva:** `(a,b) ∈ R ∧ (b,c) ∈ R → (a,c) ∈ R`.

## Exemplo resolvido
- `=` (igualdade): reflexiva, simétrica, antissimétrica e transitiva.
- `≤` em ℤ: reflexiva, antissimétrica, transitiva, mas **não** simétrica.
- `<` em ℤ: transitiva, antissimétrica, mas **não** reflexiva.

## Erros comuns
- Confundir **antissimétrica** com **não-simétrica**: antissimetria permite `(a,a)` e só proíbe pares `(a,b),(b,a)` com `a ≠ b`.
- Verificar reflexividade em só alguns elementos (precisa valer para todos).""",
        questions=(
            graded("rel-propriedades-q1", "rel-propriedades",
                   "`R` é **reflexiva** sobre A quando:",
                   ["(a,b) ∈ R → (b,a) ∈ R",
                    "para todo a, (a,a) ∈ R",
                    "(a,b),(b,c) ∈ R → (a,c) ∈ R",
                    "(a,b),(b,a) ∈ R → a = b"], 1,
                   "Reflexiva: todo elemento se relaciona consigo mesmo.",
                   EASY),
            graded("rel-propriedades-q2", "rel-propriedades",
                   "A relação `≤` em ℤ é reflexiva, antissimétrica e transitiva, mas NÃO é:",
                   ["reflexiva", "transitiva", "simétrica", "antissimétrica"], 2,
                   "≤ não é simétrica: 2 ≤ 3 mas 3 ≤ 2 é falso.",
                   MEDIUM),
            graded("rel-propriedades-q3", "rel-propriedades",
                   "Uma relação é **antissimétrica** quando:",
                   ["(a,b) ∈ R → (b,a) ∈ R",
                    "(a,b),(b,a) ∈ R → a = b",
                    "todo (a,a) ∈ R",
                    "nunca há (a,a)"], 1,
                   "Antissimetria: se a se relaciona com b E b com a, então a = b. (Permite (a,a).)",
                   MEDIUM),
            graded("rel-propriedades-q4", "rel-propriedades",
                   "Sobre `A = {1,2,3}`, a relação `R = {(1,1),(2,2),(3,3),(1,2)}` é reflexiva?",
                   ["Não, pois (1,2) quebra a reflexividade",
                    "Sim, pois (a,a) ∈ R para todo a ∈ A",
                    "Não, pois falta (2,1)",
                    "Não, pois não é simétrica"], 1,
                   "Reflexiva exige apenas que (a,a) ∈ R para todo a. Os pares (1,1),(2,2),(3,3) estão presentes. Pares adicionais como (1,2) não atrapalham.",
                   EASY),
            graded("rel-propriedades-q5", "rel-propriedades",
                   "A relação `R = {(1,2),(2,1),(1,1),(2,2)}` sobre `{1,2}` é simétrica e transitiva?",
                   ["Simétrica mas não transitiva",
                    "Transitiva mas não simétrica",
                    "Sim, é ambas",
                    "Não é nenhuma das duas"], 2,
                   "Simétrica: (1,2) e (2,1) presentes. Transitiva: (1,2)+(2,1)→(1,1) presente; (2,1)+(1,2)→(2,2) presente. Logo ambas.",
                   HARD),
            graded("rel-propriedades-q6", "rel-propriedades",
                   "Uma relação pode ser simultaneamente simétrica e antissimétrica?",
                   ["Não, são mutuamente exclusivas",
                    "Sim — nesse caso R ⊆ ι_A (só contém pares (a,a))",
                    "Sim, mas somente se R = ∅",
                    "Só em conjuntos unitários"], 1,
                   "Se (a,b) ∈ R, por simetria (b,a) ∈ R; por antissimetria a = b. Logo R só contém pares (a,a), ou seja R ⊆ ι_A. A igualdade é um exemplo.",
                   HARD),
            graded("rel-propriedades-q7", "rel-propriedades",
                   "`R = {(1,2),(2,3)}` sobre `{1,2,3}` é transitiva?",
                   ["Sim", "Não — falta (1,3)",
                    "Não — falta (3,1)", "Transitiva não se aplica aqui"], 1,
                   "Transitividade exige: (1,2) ∈ R e (2,3) ∈ R → (1,3) ∈ R. Como (1,3) ∉ R, não é transitiva.",
                   MEDIUM),
        ),
        practice=(
            practice("rel-propriedades-p1", "rel-propriedades",
                     "A relação `<` em ℤ NÃO é:",
                     ["transitiva", "reflexiva", "antissimétrica", "uma relação"], 1,
                     "a < a é falso, então < não é reflexiva (é transitiva e antissimétrica).",
                     MEDIUM),
            practice("rel-propriedades-p2", "rel-propriedades",
                     "Antissimétrica é o mesmo que 'não simétrica'?",
                     ["Sim", "Não — antissimetria permite (a,a) e só proíbe (a,b),(b,a) com a≠b",
                      "Sim, sempre", "Só em conjuntos finitos"], 1,
                     "São conceitos distintos: a igualdade é simétrica E antissimétrica ao mesmo tempo.",
                     HARD),
            practice("rel-propriedades-p3", "rel-propriedades",
                     "Qual relação é simétrica?",
                     ["≤ em ℤ", "'tem o mesmo aniversário que'",
                      "< em ℤ", "'é mãe de'"], 1,
                     "'Mesmo aniversário' é simétrica (e reflexiva e transitiva — uma equivalência). As de ordem não são simétricas.",
                     EASY),
            practice("rel-propriedades-p4", "rel-propriedades",
                     "A relação vazia `∅` sobre `A = {1,2}` é simétrica?",
                     ["Não, pois não tem pares simétricos",
                      "Sim, a condição é satisfeita vacuamente",
                      "Depende dos elementos de A",
                      "Só se A = ∅"], 1,
                     "A condição (a,b) ∈ R → (b,a) ∈ R é satisfeita vacuamente quando R = ∅: não há par que viole a simetria.",
                     MEDIUM),
            practice("rel-propriedades-p5", "rel-propriedades",
                     "A relação `A × A` (todos os pares) sobre um conjunto A é reflexiva?",
                     ["Não", "Sim, pois contém todos os (a,a)",
                      "Só se |A| = 1", "Depende de A"], 1,
                     "A × A contém todos os pares possíveis, incluindo (a,a) para todo a ∈ A. Logo é reflexiva (e também simétrica e transitiva).",
                     EASY),
            practice("rel-propriedades-p6", "rel-propriedades",
                     "Para verificar que R sobre A **não** é transitiva, basta encontrar:",
                     ["um par (a,a) ausente",
                      "(a,b) e (b,c) em R com (a,c) fora de R",
                      "um par (a,b) sem (b,a)",
                      "dois pares quaisquer"], 1,
                     "Transitividade falha se existem a,b,c com (a,b) ∈ R e (b,c) ∈ R mas (a,c) ∉ R. Um único contraexemplo é suficiente.",
                     MEDIUM),
        ),
    ),
    concept(
        id="rel-fechos",
        title="Fechos reflexivo, simétrico e transitivo",
        unit=2,
        topic=7,
        prerequisites=("rel-propriedades",),
        content="""## Intuição
O **fecho** de `R` em relação a uma propriedade é a **menor** relação que contém `R` e tem aquela propriedade. É "completar" `R` com o mínimo de pares necessário.

## Definição formal
- **Fecho reflexivo:** `R ∪ ι_A` (acrescenta os pares `(a,a)`).
- **Fecho simétrico:** `R ∪ R⁻¹` (acrescenta os pares inversos).
- **Fecho transitivo (`R⁺`):** acrescenta todos os pares forçados pela transitividade (caminhos de qualquer comprimento). `R* = R⁺ ∪ ι_A` é o fecho reflexivo-transitivo.

## Exemplo resolvido
`A = {1,2,3}`, `R = {(1,2),(2,3)}`.
- Fecho reflexivo: `R ∪ {(1,1),(2,2),(3,3)}`.
- Fecho simétrico: `R ∪ {(2,1),(3,2)}`.
- Fecho transitivo: `R ∪ {(1,3)}` (pois `1→2→3`).

## Erros comuns
- Acrescentar pares demais: o fecho é o **menor** que satisfaz a propriedade.
- Esquecer pares de transitividade indiretos (caminhos longos).""",
        questions=(
            graded("rel-fechos-q1", "rel-fechos",
                   "O fecho de R em relação a uma propriedade é:",
                   ["a maior relação com a propriedade",
                    "a menor relação que contém R e tem a propriedade",
                    "R menos os pares ruins",
                    "a inversa de R"], 1,
                   "Fecho = menor relação ⊇ R que satisfaz a propriedade.",
                   MEDIUM),
            graded("rel-fechos-q2", "rel-fechos",
                   "O fecho **reflexivo** de R é:",
                   ["R ∪ R⁻¹", "R ∪ ι_A", "R⁺", "R ∩ ι_A"], 1,
                   "Acrescenta os pares (a,a): R ∪ ι_A.",
                   MEDIUM),
            graded("rel-fechos-q3", "rel-fechos",
                   "Para `R = {(1,2),(2,3)}`, o fecho **transitivo** acrescenta:",
                   ["(2,1)", "(1,3)", "(1,1)", "(3,1)"], 1,
                   "1→2→3 força (1,3) pela transitividade.",
                   MEDIUM),
            graded("rel-fechos-q4", "rel-fechos",
                   "Se `R` já é reflexiva, o fecho reflexivo de `R` é:",
                   ["∅", "R (ela mesma)",
                    "R ∪ R⁻¹", "R − ι_A"], 1,
                   "Se R já contém todos os (a,a), então R ∪ ι_A = R — nada é acrescentado.",
                   EASY),
            graded("rel-fechos-q5", "rel-fechos",
                   "Para `R = {(1,2),(2,3),(3,1)}` sobre `{1,2,3}`, o fecho transitivo `R⁺` contém quantos pares?",
                   ["3", "6", "9", "5"], 2,
                   "R tem ciclo 1→2→3→1. Transitividade gera todos os caminhos: (1,2),(1,3),(1,1),(2,3),(2,1),(2,2),(3,1),(3,2),(3,3). R⁺ = A × A com 9 pares.",
                   HARD),
            graded("rel-fechos-q6", "rel-fechos",
                   "O fecho simétrico de `R = {(1,2),(2,3)}` sobre `{1,2,3}` é:",
                   ["{(1,2),(2,3),(2,1),(3,2)}", "{(1,2),(2,3),(1,1),(2,2),(3,3)}",
                    "{(1,2),(2,3),(1,3)}", "{(2,1),(3,2)}"], 0,
                   "Fecho simétrico = R ∪ R⁻¹ = {(1,2),(2,3)} ∪ {(2,1),(3,2)} = {(1,2),(2,3),(2,1),(3,2)}.",
                   MEDIUM),
            graded("rel-fechos-q7", "rel-fechos",
                   "O fecho transitivo de `R = {(1,2),(2,3),(3,4)}` sobre `{1,2,3,4}` é:",
                   ["{(1,2),(2,3),(3,4),(1,3)}",
                    "{(1,2),(2,3),(3,4),(1,3),(2,4),(1,4)}",
                    "{(1,2),(2,3),(3,4),(1,4)}",
                    "{(1,4)}"], 1,
                   "Caminhos: 1→2→3 dá (1,3); 2→3→4 dá (2,4); 1→2→3→4 dá (1,4). R⁺ = R ∪ {(1,3),(2,4),(1,4)}.",
                   HARD),
        ),
        practice=(
            practice("rel-fechos-p1", "rel-fechos",
                     "O fecho **simétrico** de R é:",
                     ["R ∪ ι_A", "R ∪ R⁻¹", "R⁺", "R⁻¹"], 1,
                     "Acrescenta os inversos de cada par: R ∪ R⁻¹.",
                     MEDIUM),
            practice("rel-fechos-p2", "rel-fechos",
                     "O fecho reflexivo de `{(1,2)}` sobre {1,2} é:",
                     ["{(1,2)}", "{(1,2),(1,1),(2,2)}",
                      "{(1,2),(2,1)}", "{(1,1)}"], 1,
                     "Adiciona (1,1) e (2,2): {(1,2),(1,1),(2,2)}.",
                     EASY),
            practice("rel-fechos-p3", "rel-fechos",
                     "`R*` (fecho reflexivo-transitivo) é:",
                     ["R⁻¹", "R⁺ ∪ ι_A", "R ∩ ι_A", "R ∪ R⁻¹"], 1,
                     "Combina o fecho transitivo R⁺ com a identidade: R* = R⁺ ∪ ι_A.",
                     HARD),
            practice("rel-fechos-p4", "rel-fechos",
                     "Existe fecho **antissimétrico** (acrescentar pares para obter antissimetria)?",
                     ["Sim, basta remover pares simétricos",
                      "Não — obter antissimetria pode exigir remover pares, e fecho só acrescenta",
                      "Sim, acrescenta ι_A",
                      "Sim, acrescenta R⁻¹"], 1,
                     "Fecho é a menor relação que CONTÉM R e tem a propriedade. Antissimetria pode exigir REMOVER pares (a,b) e (b,a) com a≠b, o que contradiz 'conter R'. Logo o fecho antissimétrico não é definido em geral.",
                     HARD),
            practice("rel-fechos-p5", "rel-fechos",
                     "O fecho reflexivo de `∅` sobre `A = {1,2}` é:",
                     ["∅", "{(1,1),(2,2)}", "{(1,2),(2,1)}", "A × A"], 1,
                     "∅ ∪ ι_A = {(1,1),(2,2)}. Adiciona apenas os pares reflexivos.",
                     EASY),
            practice("rel-fechos-p6", "rel-fechos",
                     "Se `R ⊆ S` e `S` é transitiva, então o fecho transitivo `R⁺` satisfaz `R⁺ ⊆ S`?",
                     ["Não necessariamente", "Sim, pois R⁺ é a menor relação transitiva contendo R",
                      "Só se S = A × A", "Depende de A"], 1,
                     "R⁺ é a MENOR relação transitiva que contém R. Se S é transitiva e contém R, então R⁺ ⊆ S por definição de menor.",
                     MEDIUM),
        ),
    ),
    # ──────────────────── Ordem e Equivalência (topic 8) ────────────────────
    concept(
        id="rel-ordem",
        title="Relações de ordem: parcial e total",
        unit=2,
        topic=8,
        prerequisites=("rel-propriedades",),
        content="""## Intuição
Uma **ordem parcial** organiza elementos numa hierarquia (quem vem "antes"), permitindo que alguns sejam **incomparáveis**. Se *todos* os pares são comparáveis, a ordem é **total** (uma cadeia).

## Definição formal
- **Ordem parcial:** relação **reflexiva, antissimétrica e transitiva** (notação `≤`). O par `(A, ≤)` é um **conjunto parcialmente ordenado (poset)**.
- **Ordem total:** ordem parcial em que, para quaisquer `a, b`, vale `a ≤ b` ou `b ≤ a` (todos comparáveis).

## Exemplo resolvido
- `≤` em ℕ: ordem **total**.
- `⊆` sobre `P({1,2})`: ordem **parcial** — `{1}` e `{2}` são **incomparáveis** (`{1} ⊄ {2}` e `{2} ⊄ {1}`).
- Divisibilidade `|` em ℕ: ordem parcial (`2 | 6`, mas `2` e `3` são incomparáveis).

## Erros comuns
- Supor que toda ordem é total (existem incomparáveis).
- Trocar antissimetria (ordem) por simetria (equivalência).""",
        questions=(
            graded("rel-ordem-q1", "rel-ordem",
                   "Uma **ordem parcial** é uma relação:",
                   ["reflexiva, simétrica e transitiva",
                    "reflexiva, antissimétrica e transitiva",
                    "apenas transitiva",
                    "simétrica e total"], 1,
                   "Ordem parcial = reflexiva + antissimétrica + transitiva.",
                   EASY),
            graded("rel-ordem-q2", "rel-ordem",
                   "A relação `⊆` sobre `P({1,2})` é parcial (e não total) porque:",
                   ["não é transitiva",
                    "{1} e {2} são incomparáveis",
                    "não é reflexiva",
                    "tem ciclos"], 1,
                   "Nem {1} ⊆ {2} nem {2} ⊆ {1}: são incomparáveis, logo a ordem é parcial.",
                   MEDIUM),
            graded("rel-ordem-q3", "rel-ordem",
                   "Numa **ordem total**, quaisquer dois elementos a, b satisfazem:",
                   ["a = b", "a ≤ b ou b ≤ a",
                    "a ≤ b e b ≤ a", "nem a ≤ b nem b ≤ a"], 1,
                   "Total = todos comparáveis: sempre a ≤ b ou b ≤ a.",
                   MEDIUM),
            graded("rel-ordem-q4", "rel-ordem",
                   "O **elemento mínimo** de um poset `(A, ≤)` é um `m ∈ A` tal que:",
                   ["m ≤ a para todo a ∈ A",
                    "a ≤ m para todo a ∈ A",
                    "m não é comparável com nenhum elemento",
                    "m é o maior elemento"], 0,
                   "Elemento mínimo: m ≤ a para todo a ∈ A. É o menor dentre todos os elementos do poset.",
                   MEDIUM),
            graded("rel-ordem-q5", "rel-ordem",
                   "No poset `(P({1,2}), ⊆)`, os elementos **minimais** são:",
                   ["{1} e {2}", "∅",
                    "{1,2}", "{1}, {2} e ∅"], 1,
                   "∅ é subconjunto de todos, logo ∅ ⊆ X para todo X ∈ P({1,2}). Ele é o único minimal (e também o mínimo).",
                   HARD),
            graded("rel-ordem-q6", "rel-ordem",
                   "Uma **cadeia** num poset é:",
                   ["um subconjunto onde nenhum par é comparável",
                    "um subconjunto totalmente ordenado",
                    "o conjunto de todos os elementos minimais",
                    "uma partição do poset"], 1,
                   "Cadeia = subconjunto C onde quaisquer dois elementos são comparáveis (ordem total restrita a C).",
                   MEDIUM),
            graded("rel-ordem-q7", "rel-ordem",
                   "Uma **anticadeia** num poset é um subconjunto onde:",
                   ["todos os pares são comparáveis",
                    "nenhum par de elementos distintos é comparável",
                    "todos são iguais",
                    "existe um máximo"], 1,
                   "Anticadeia: quaisquer dois elementos distintos são incomparáveis. No poset (P({1,2}), ⊆), {1} e {2} formam uma anticadeia.",
                   HARD),
        ),
        practice=(
            practice("rel-ordem-p1", "rel-ordem",
                     "Um **poset** é:",
                     ["um conjunto com uma equivalência",
                      "um conjunto com uma ordem parcial",
                      "um conjunto finito",
                      "uma função bijetora"], 1,
                     "Poset = 'partially ordered set' = conjunto + ordem parcial.",
                     EASY),
            practice("rel-ordem-p2", "rel-ordem",
                     "A divisibilidade `|` em ℕ é:",
                     ["ordem total", "ordem parcial (há incomparáveis, p.ex. 2 e 3)",
                      "equivalência", "não é relação"], 1,
                     "É reflexiva, antissimétrica e transitiva; mas 2 e 3 são incomparáveis, então é parcial.",
                     MEDIUM),
            practice("rel-ordem-p3", "rel-ordem",
                     "`≤` em ℕ é exemplo de ordem:",
                     ["parcial não-total", "total",
                      "de equivalência", "simétrica"], 1,
                     "Em ℕ quaisquer dois números são comparáveis: ordem total.",
                     EASY),
            practice("rel-ordem-p4", "rel-ordem",
                     "No poset `({1,2,3,6}, |)` (divisibilidade), `2` e `3` são:",
                     ["comparáveis (2 | 3)", "comparáveis (3 | 2)",
                      "incomparáveis", "iguais"], 2,
                     "2 não divide 3 e 3 não divide 2, logo são incomparáveis na ordem de divisibilidade.",
                     EASY),
            practice("rel-ordem-p5", "rel-ordem",
                     "Um **diagrama de Hasse** de um poset finito omite:",
                     ["todos os arcos", "arcos dedutíveis por reflexividade e transitividade",
                      "os elementos minimais", "os arcos de incomparabilidade"], 1,
                     "O diagrama de Hasse simplifica: remove laços (reflexividade), arcos dedutíveis por transitividade, e orienta de baixo para cima.",
                     MEDIUM),
            practice("rel-ordem-p6", "rel-ordem",
                     "Se todo par de elementos de um poset é comparável, o poset é chamado de:",
                     ["anticadeia", "cadeia (ou ordem total)",
                      "reticulado", "poset vazio"], 1,
                     "Quando todos os pares são comparáveis, temos uma ordem total — também chamada de cadeia.",
                     EASY),
        ),
    ),
    concept(
        id="rel-equivalencia",
        title="Relações de equivalência, classes e partições",
        unit=2,
        topic=8,
        prerequisites=("rel-propriedades",),
        content="""## Intuição
Uma **relação de equivalência** agrupa elementos "iguais sob algum critério". Ela quebra o conjunto em **classes** disjuntas que cobrem tudo — uma **partição**.

## Definição formal
- **Equivalência:** relação **reflexiva, simétrica e transitiva**.
- **Classe de `a`:** `[a] = {x : x ~ a}`.
- As classes formam uma **partição** de `A` (não vazias, disjuntas duas a duas, e a união é `A`). O conjunto das classes é o **quociente** `A/~`.

## Exemplo resolvido
Congruência módulo 3 em ℤ (`a ~ b ⟺ 3 | (a − b)`) é equivalência. Suas classes são `[0], [1], [2]` (os restos), que particionam ℤ. Outra: "ter o mesmo aniversário" particiona pessoas por data.

## Erros comuns
- Usar **antissimetria** (isso é ordem) no lugar de **simetria**.
- Esquecer que classes distintas são **disjuntas** (não se sobrepõem).""",
        questions=(
            graded("rel-equivalencia-q1", "rel-equivalencia",
                   "Uma relação de **equivalência** é:",
                   ["reflexiva, antissimétrica e transitiva",
                    "reflexiva, simétrica e transitiva",
                    "simétrica e total",
                    "apenas transitiva"], 1,
                   "Equivalência = reflexiva + simétrica + transitiva.",
                   EASY),
            graded("rel-equivalencia-q2", "rel-equivalencia",
                   "As classes de uma relação de equivalência sobre A formam sempre:",
                   ["uma cadeia", "uma partição de A",
                    "uma ordem total", "um único conjunto"], 1,
                   "Classes de equivalência são não-vazias, disjuntas e cobrem A: uma partição.",
                   MEDIUM),
            graded("rel-equivalencia-q3", "rel-equivalencia",
                   "Agrupar pessoas pelo mês de nascimento define uma relação de:",
                   ["ordem total", "equivalência",
                    "ordem parcial estrita", "função bijetora"], 1,
                   "'Mesmo mês' é reflexiva, simétrica e transitiva — equivalência; as classes (meses) particionam o conjunto.",
                   MEDIUM),
            graded("rel-equivalencia-q4", "rel-equivalencia",
                   "Se `[a] = [b]` numa equivalência `~`, então:",
                   ["a e b estão em classes distintas",
                    "a ~ b",
                    "a = b",
                    "a e b são incomparáveis"], 1,
                   "Duas classes são iguais se e somente se a ~ b. Logo [a] = [b] implica a ~ b (e vice-versa).",
                   MEDIUM),
            graded("rel-equivalencia-q5", "rel-equivalencia",
                   "Sobre `A = {1,2,3,4}`, a partição `{{1,2},{3,4}}` corresponde à equivalência:",
                   ["{(1,2),(3,4)}",
                    "{(1,1),(2,2),(3,3),(4,4),(1,2),(2,1),(3,4),(4,3)}",
                    "{(1,1),(2,2),(3,3),(4,4)}",
                    "A × A"], 1,
                   "Cada classe gera todos os pares entre seus membros: {1,2} gera (1,1),(1,2),(2,1),(2,2) e {3,4} gera (3,3),(3,4),(4,3),(4,4).",
                   HARD),
            graded("rel-equivalencia-q6", "rel-equivalencia",
                   "Se `~` tem exatamente uma classe de equivalência, então:",
                   ["~ = ∅", "~ = ι_A", "~ = A × A", "A tem um único elemento"], 2,
                   "Uma única classe significa que todos os elementos são equivalentes entre si, logo ~ contém todos os pares: ~ = A × A.",
                   HARD),
            graded("rel-equivalencia-q7", "rel-equivalencia",
                   "O número de classes da congruência módulo `n` em ℤ é:",
                   ["n − 1", "n", "2n", "infinito"], 1,
                   "Os restos possíveis na divisão por n são 0, 1, …, n−1: exatamente n classes.",
                   EASY),
        ),
        practice=(
            practice("rel-equivalencia-p1", "rel-equivalencia",
                     "Duas classes de equivalência distintas são:",
                     ["iguais", "disjuntas",
                      "sempre unitárias", "comparáveis"], 1,
                     "Classes distintas não se sobrepõem (são disjuntas) — propriedade central da partição.",
                     MEDIUM),
            practice("rel-equivalencia-p2", "rel-equivalencia",
                     "A congruência módulo 3 em ℤ tem quantas classes?",
                     ["1", "2", "3", "infinitas"], 2,
                     "Os restos possíveis na divisão por 3 são 0, 1, 2: três classes [0], [1], [2].",
                     MEDIUM),
            practice("rel-equivalencia-p3", "rel-equivalencia",
                     "O conjunto das classes de `~` sobre A é chamado de:",
                     ["fecho de A", "quociente A/~",
                      "partição inversa", "poset"], 1,
                     "O conjunto quociente A/~ reúne todas as classes de equivalência.",
                     EASY),
            practice("rel-equivalencia-p4", "rel-equivalencia",
                     "Se `A = {1,2,3}` e `~ = ι_A` (identidade), as classes de equivalência são:",
                     ["{A}", "{{1},{2},{3}}", "{{1,2,3}}", "{∅}"], 1,
                     "Com ι_A, cada elemento só é equivalente a si mesmo: [1]={1}, [2]={2}, [3]={3}. A partição é em singletons.",
                     MEDIUM),
            practice("rel-equivalencia-p5", "rel-equivalencia",
                     "Toda partição de A define uma única relação de equivalência sobre A?",
                     ["Não, pode definir várias",
                      "Sim — a correspondência partição ↔ equivalência é bijetiva",
                      "Só para conjuntos finitos",
                      "Não, partições e equivalências são independentes"], 1,
                     "Há uma correspondência bijetiva entre partições de A e relações de equivalência sobre A: cada partição define exatamente uma equivalência (e vice-versa).",
                     MEDIUM),
            practice("rel-equivalencia-p6", "rel-equivalencia",
                     "A relação 'ter o mesmo resto na divisão por 2' sobre ℤ tem quantas classes?",
                     ["1", "2", "3", "infinitas"], 1,
                     "Os restos possíveis na divisão por 2 são 0 e 1: duas classes — os pares e os ímpares.",
                     EASY),
        ),
    ),
)
